### ISSUE TITLE
componentWillReceiveProps deprecated

### ISSUE THREAD

**Issue by getaaron** [lawnstarter/react-native-picker-select#10]
https://github.com/lawnstarter/react-native-picker-select/blob/8d77e8d481130b5e6377edefb067d4a4acce624f/src/index.js#L36-L38

needs to be replaced with `getDerivedStateFromProps` instead

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops
https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

**Comment by getaaron** [comment]
@lfkwtz Any updates on this?

**Comment by lfkwtz** [comment]
On it

**Comment by lfkwtz** [comment]
Closed #13
