### ISSUE TITLE
Add custom `Icon` component as prop

### ISSUE THREAD

**Issue by luizParreira** [lawnstarter/react-native-picker-select#104]
**Is your feature request related to a problem? Please describe.**
At work, we would like to be able to add a custom icon component to be rendered by the picker select.

**Describe the solution you'd like**
The solution is simple, just add an extra `prop`, called `Icon` to be rendered instead of the current `Icon` used.

**Describe alternatives you've considered**
I couldn't think of any other way of solving this in this context, apart from the current way, which is to style the view that is used as an Icon.

**Additional context**
Here is a screenshot of how we would like the component to look.
![screen shot 2018-10-23 at 17 58 28](https://user-images.githubusercontent.com/8305710/47665316-9a3fc480-db7f-11e8-971e-494ff6ab075a.png)

**Comment by lfkwtz** [comment]
Seems reasonable, but heads up you could just do this to achieve that desired look:

````
style={
    icon: {
        borderLeftWidth: 0,
        borderLeftColor: 'transparent',
        borderTopWidth: 2,
        borderTopColor: 'gray',
        borderRightWidth: 2,
        borderRightColor: 'gray',
        width: 9,
        height: 9,
        right: 15,
        top: 5,
        transform: [{ translateY: 8 }, { rotate: '135deg' }],
    }
}
````

**Comment by lfkwtz** [comment]
Closing this active issue as it'll live on the feature request board
