### ISSUE TITLE
Forward picker `ref`

### ISSUE THREAD

**Issue by luizParreira** [lawnstarter/react-native-picker-select#106]
**Is your feature request related to a problem? Please describe.**
We need to have the reference of the Picker available for our `Form` component. To do that, we need to forward the reference of `RNPickerSelect` to the clients components. That way, we can pass a function that will have access to the picker `ref`.

**Describe the solution you'd like**
Export `React.createRef(...)` as the default picker component. That way, clients can use it to get the components ref.

**Describe alternatives you've considered**
I am not sure how to go about this without forwarding this ref, would be happy to consider other options, if anyone has one.

**Additional context**
This is done, so that form components can get the reference of the input and toggle the picker on the `next` button or on other action decided by the user.

**Comment by lfkwtz** [comment]
Closing this active issue as it'll live on the feature request board
