### ISSUE TITLE
When useNativeAndroidPickerStyle={false}, the below area after the Picker gets bugged

### ISSUE THREAD

**Issue by mgcostaParedes** [lawnstarter/react-native-picker-select#113]
When I use the useNativeAndroidPickerStyle={false}, the area below the <RNPickerSelect> gets Bugged, for example if i click on an empty space from a margin, it will focus the Picker Over the area.

The below code which reproduces the bug is:

`<Text style={{textAlign:"left", fontSize: 13, paddingLeft:5, marginTop:10 }}>Currency</Text>
                    <RNPickerSelect
                        items={this.state.currencies}
                        useNativeAndroidPickerStyle={false}
                        placeholder={{label: "Picke the Currency..", value: null}}
                        disabled = {false}
                        style={{ ...stylesForm }}
                        value={this.state.currencyId}
                        onValueChange={(value) => {
                            this.setState({
                                currencyId: value,
                            });
                        }}/>
                    <Text style={{textAlign:"left", fontSize: 13, paddingLeft:5, marginTop:10, marginBottom:20 }}>Type of Discount</Text>`

**Comment by lfkwtz** [comment]
#110
