### ISSUE TITLE
[Android]: Picker items do not have a fallback color

### ISSUE THREAD

**Issue by sgolovine** [lawnstarter/react-native-picker-select#114]
**Describe the bug**

When displaying a picker list on Android, if an item does not have a color it will fallback on colors of other items or render grey if no item has a color assigned to it.

**To Reproduce**

1.  Create a project with react-native-picker-select

2. Provide a large data set to render (ie. 50 US States)

3. When opening the picker list on  Android, some items will be greyed out

Additionally:

If you give one item in the list a color, random items in the list will also be that color even though there is no color assigned to them

**Expected behavior**

When rendering the picker list, items with a set color should the color they were assigned and items without a color should render black.

**Screenshots**

![screenshot_1543273519](https://user-images.githubusercontent.com/5214877/49048305-3f15e780-f1a8-11e8-9402-b6d5c8bd0c1b.png)
![screenshot_1543273516](https://user-images.githubusercontent.com/5214877/49048312-42a96e80-f1a8-11e8-91f7-ec79dab058c0.png)
![screenshot_1543273274](https://user-images.githubusercontent.com/5214877/49048317-44733200-f1a8-11e8-99b3-4e54a2adedc5.png)
![screenshot_1543273258](https://user-images.githubusercontent.com/5214877/49048321-4937e600-f1a8-11e8-9e50-947db430851e.png)

**Smartphone:**

-   Device: Pixel 2 (Android Emulator)
-   OS: Android 9.0 (Pie)
-   react-native-picker-select version: 5.1.0
-   react-native version: 0.57.3
-   react version: 16.5.0

**Reproduction and/or code sample**

Expo: https://expo.io/@glvn/react-native-picker-select-bug

Data Set Used: https://gist.github.com/sgolovine/f473d8a210c1ae53d85f31ea5300f6dc

**Comment by lfkwtz** [comment]
That's a weird one. Can you put this on snack.expo.io -- just expo.io doesn't let me see the code.

**Comment by lfkwtz** [comment]
https://snack.expo.io/@lfkwtz/rn-picker-bug

looks like an issue with the Native picker and not necessarily this library

**Comment by incorelabs** [comment]
In this case, you need to add color to all the items and then it shows up correctly.

I let the red color be then I added blue color to all the items. That seemed to work perfectly.

**Comment by lfkwtz** [comment]
this was an upstream issue - not sure if it's been fixed.
