### ISSUE TITLE
Add option to set fontFamily for placeholder

### ISSUE THREAD

**Issue by davidajnered** [lawnstarter/react-native-picker-select#119]
It would be nice to have the option to use a custom font family in the same way you can set the placeholder color.

**Comment by lfkwtz** [comment]
I'll throw this on the feature request board

**Comment by lfkwtz** [comment]
moved to todo if the implementation is done as mentioned in this comment: https://github.com/lawnstarter/react-native-picker-select/pull/155#issuecomment-469028508
