### ISSUE TITLE
Bug in Android Placeholder

### ISSUE THREAD

**Issue by quent176** [lawnstarter/react-native-picker-select#121]
**Describe the bug**
Only for Android, the value is getting the color of the placeholder randomly. This happens for lists of more than 10 elements.
This bug happens with or without the native androidpickerstyle

**To Reproduce**
Just make a list with many elements and place it in the picker as items.

**Expected behavior**
Only the placeholder can get this color.

**Smartphone (please complete the following information):**

-   Device: [nexus5 - simulator]
-   OS: [9]
-   react-native-picker-select version: [5.1.1]
-   react-native version: [0.57.5]
-   react version: [e.g. 16.6.0-alpha.8af6728]

**Reproduction and/or code sample**
https://snack.expo.io/B1urSOhyE

Thank you !

**Comment by lfkwtz** [comment]
#114
