### ISSUE TITLE
On Close of Picker return on previous input focus

### ISSUE THREAD

**Issue by jriiringan** [lawnstarter/react-native-picker-select#123]
**Describe the bug**
It does not lose focus of previous input when you open a picker.(I've been trying to figure this thing, might be fall on the question)

**To Reproduce**

Open a picker while a keyboard is focused on a certain input.
After the keyboard is closed and a picker is opened, when you selected a certain item and close it
using "done" button it will return to the previous focused input.
(Unless you close the keyboard first and open a picker this will not happen.)

**Expected behavior**
All focus on previous input will be remove.

**Smartphone (please complete the following information):**

-   Device: iPhone6
-   OS: iOS12
-   react-native-picker-select version: 5.0.1
-   react-native version: 0.57.4
-   react version: 16.6

**Reproduction and/or code sample**
https://snack.expo.io/@jriiringan/pickerkeyboard
![picker_issue](https://user-images.githubusercontent.com/16267435/49981904-2887d280-ff95-11e8-8bca-88a9fa137dff.gif)

**Comment by lfkwtz** [comment]
Can you attach a snack.expo.io reproduction of the issue?

**Comment by jriiringan** [comment]
here it is https://snack.expo.io/@jriiringan/pickerkeyboard

**Comment by lfkwtz** [comment]
@jriiringan does #125 solve this for you?

**Comment by jriiringan** [comment]
#125 solve this issue.

**Comment by Avanikothari22** [comment]
The above solution seems for IOS, what about Android ? I am facing this issue on android, keyboard does not dismiss when picker opens.

**Comment by lfkwtz** [comment]
can you share a screenshot of what that looks like? is that with the dialog or dropdown picker?

**Comment by Avanikothari22** [comment]
its a dialogue picker.
![Screenshot_2019-12-12-11-48-43](https://user-images.githubusercontent.com/30333802/70687888-6cabd100-1cd6-11ea-806f-1eb38883ae9d.png)

**Comment by lfkwtz** [comment]
that's an upstream "issue" (wouldn't say it's necessarily a bug)
https://snack.expo.io/rJmgxylRB

there may be a way to handle it within this library though - feel free to submit a pr
