### ISSUE TITLE
Appium Automation is not able to recognize TextField inside the TouchableWithoutFeedback for iOS

### ISSUE THREAD

**Issue by SunilKrishna1234** [lawnstarter/react-native-picker-select#124]
**Describe the bug**
While doing automation to the application using RNPickerSelect, Android UIAutomator is able to identify the textfield inside the TouchableWithoutFeedback but in iOS, iOS inspector is hiding the controls inside the TouchableWithoutFeedback and grouping all the controls to a single object which doesn't serve the purpose. 

When I researched about this issue, I got to know that setting "accessible={false}" to TouchableWithoutFeedback will fix the issue. It will make the controls accessible to iOS inspector. Can you please add this prop to the TouchableWithoutFeedback above the TextInput in your component?

**Comment by lfkwtz** [comment]
Want to open a PR for this?

**Comment by lfkwtz** [comment]
going to close this out - feel free to open a pr
