### ISSUE TITLE
Placeholder problem

### ISSUE THREAD

**Issue by pani7** [lawnstarter/react-native-picker-select#127]
**Describe the bug**
Hi, it says in the placeholder documentation that - An empty object can be used if you'd like to disable the placeholder entirely - but when i set placeholder= {{}} inside jsx, i get a crash saying  - cannot read property label of undefined. So clearly it needs placeholder object to have key for label, and i want not to have placeholder at all because i have default value selected on start.

**Comment by lfkwtz** [comment]
Please edit your post with the full bug report template filled out

**Comment by ionut-movila** [comment]
This is still a problem and the original description is quite accurate.

@lfkwtz Can you please re-open this?

**Comment by lfkwtz** [comment]
It didn’t follow the template so it won’t be reopened. Feel free to open a new one though. Thanks.
