### ISSUE TITLE
placeholder prop doesnt overwrite the setState of 1st item.

### ISSUE THREAD

**Issue by Rajdeepc** [lawnstarter/react-native-picker-select#132]
**Describe the bug**<br />
placeholder prop doesnt overwrite the setState of 1st item.

**To Reproduce**<br />
1.Place placeholder prop as placeholder={{}}
2.Select 1st item from the dropdown. It wont do setState.
3. If you swipe to second and swipe up to first and then select it will do setState.

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   react-native-picker-select version: [e.g. 4.3.0]
-   react-native version: [e.g. 0.56]
-   react version: [e.g. 16.3]

**Reproduction and/or code sample**<br />
```
<RNPickerSelect
             // value={this.state.branch}
              //placeholder={{}}
              items={this.state.branchItems}
              onValueChange={this.setBranchValue}
              style={{ ...pickerSelectStyles }}
              onDonePress={this.onDoneBranchSelected}
            >
              <View style={styles.drowdownstyle}>
                <View style={styles.dropdownTextContainer}>
                  <TextRegular style={styles.drowdownTextStyle}>
                    {this.state.branch}
                  </TextRegular>
                </View>
                <View style={styles.drowdownArrowContainer}>
                  <Image style={styles.arrowimagestyle} source={expandImg} />
                </View>
              </View>
            </RNPickerSelect>
```

**Comment by lfkwtz** [comment]
If there is no placeholder, the first item will not trigger an onValueChange because you have never changed the value. That is intentional and how the native Picker is built. 

You should be setting the first item in your array to state as the selected value, because that is what you’re displaying to your users as the selected value.
