### ISSUE TITLE
onClose and onOpen events are not firing when trying to open dropdown

### ISSUE THREAD

**Issue by Anshu8405** [lawnstarter/react-native-picker-select#137]
### YOU MUST FILL OUT THE ENTIRE BUG REPORT

**Describe the bug**<br />

**To Reproduce**<br />

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**<br />

**Screenshots**<br />

**Smartphone (please complete the following information):**<br />
-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   react-native-picker-select version: [e.g. 4.3.0]
-   react-native version: [e.g. 0.56]
-   react version: [e.g. 16.3]

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or a good explanation on why you can not**. Not including a link will result in a significant delay in our ability to address this issue.

**Comment by Anshu8405** [comment]
Here is my dropdown related code.Not able to see console messages.

`<RNPickerSelect
        hideDoneBar={false}
        placeholder={{ label: 'All', value: 'All' }}
        placeholderTextColor={'black'}
        items={this.state.List}
        onValueChange={(value) => {
            this.setState({
                selectedOption: value,
            });
        }}
        style={{
            ...pickerSelectStyles,
            inputIOS: {
                ...pickerSelectStyles.inputIOS,
                height: 40
            }
        }}
        onOpen={() => console.log('open dropdown')}
        onClose={() => console.log('open dropdown')}
        value={this.state.selectedOption}
        ref={(el) => {
            this.inputRefs.picker2 = el;
        }}
/>`

**Comment by lfkwtz** [comment]
You need to fill out the entire bug report. Just like it says on it.

**Comment by cYee992** [comment]
If you are using android. Try set useNativeAndroidPickerStyle={false}
