### ISSUE TITLE
Can we remove placeholder text from modal?

### ISSUE THREAD

**Issue by maharjanaman** [lawnstarter/react-native-picker-select#138]
Can we remove placeholder text from modal?

**Comment by lfkwtz** [comment]
‘placeholder={{}}’

**Comment by lfkwtz** [comment]
If you want to remove the placeholder from JUST the modal - you could possibly dynamically update the value onOpen for iOS.

Also see #98

**Comment by kaantyy** [comment]
> ‘placeholder={{}}’

It doesn't works... both iOS and Android saying: 

TypeError: undefined is not an object (evaluating 'this.state.selectedItem.label')
This error is located at:
in RNPickerSelect (etc...)

**Comment by lfkwtz** [comment]
works fine on the sample app https://snack.expo.io/@lfkwtz/react-native-picker-select

feel free to open a full bug report if you see otherwise

**Comment by maharjanaman** [comment]
From sample app, is there way to show text on text input field but not on modal? Sorry for making this so confusing.

**Comment by lfkwtz** [comment]
@maharjanaman

If you want to remove the placeholder from JUST the modal - you could possibly dynamically update the value onOpen for iOS.

Also see #98

**Comment by gluons** [comment]
@lfkwtz I face the same error as @kaantyy.

See https://snack.expo.io/@illuminator/react-native-picker-select-|-placeholder-problem

**Comment by lfkwtz** [comment]
@gluons you're initializing with an empty `items` array. This is not currently supported.

Feel free to open a feature request ticket (and submit a PR if you want to).

**Comment by gluons** [comment]
@lfkwtz OK. I create #161.

**Comment by BogdanTaranenko** [comment]
> If you want to remove the placeholder from JUST the modal - you could possibly dynamically update the value onOpen for iOS.
> 
> Also see #98

what about android?

**Comment by lfkwtz** [comment]
@BogdanTaranenko - added support for `onOpen` in 6.4.0 on android

notes:
- will not work when `useNativeAndroidPickerStyle={true}`
- no easy way to detect picker close on android, so callback currently isn't supported

**Comment by smile-and-code** [comment]
Hi guys! I hope you can find this helpful✌️ this solution worked for me.

```
placeholderStyle={{ display: 'none' }}
labelStyle={{ display: 'none' }}
```
