### ISSUE TITLE
Weird Background when using borders

### ISSUE THREAD

**Issue by husnaingoldev** [lawnstarter/react-native-picker-select#14]
Hello guys, first of all thanks for the great library.

I want to bring this into your attention, that when i try to use **RNPickerSelect** with borders

```
<View style={{
                            flex: 1,
                            paddingLeft: 8,
                            justifyContent: "center",
                             borderRadius:0.5,
                             borderWidth: 0.5,
                             borderColor:"#999"
                        }} >
                            <RNPickerSelect
                                items={this.state.filter_items}
                                placeholder={{}}
                                value={this.state.filter_items.value}    
                                onValueChange={(item) => { this.selectedPickerItem(item) }}
                            >
                                <Text style={{ justifyContent: "center", fontSize: 16 }}>
                                    {this.state.PickerValueHolder}
                                </Text>
                            </RNPickerSelect>
                        </View>
```

There appears a strange background on PLUS variants of iPhones i-e iPhone 6Plus, 7Plus and 8Plus as well as in iPhoneX.

Look at the following image for better understanding
![screen shot 2018-04-23 at 3 03 11 pm](https://user-images.githubusercontent.com/22097139/39120318-9064e786-4707-11e8-9412-59d90847230a.png)

There is a strange background  around "OPEN" word.

**Comment by lfkwtz** [comment]
Odd. Will take a look, thanks.

**Comment by lfkwtz** [comment]
Tried on an iPhone X and wasn't able to reproduce. If you can spin up an example repo for me I'll take another look - but until then I'm going to close this.

Also - are you passing an object into the `items` prop? It should be an array.

**Comment by husnaingoldev** [comment]
I am passing array to `items` props.

i have tried it in a new project and i am also not able to reproduce it. I don't know why it happened in my real project.

Anyhow Thanks for response.
