### ISSUE TITLE
On Android, onValueChange is triggered on render when an item has a value of empty string

### ISSUE THREAD

**Issue by zaytrix** [lawnstarter/react-native-picker-select#141]
**Describe the bug**<br />
`onValueChange` triggers immediately upon render, without having made any change.
This only occurs on Android, with react-native-picker-select v5.2.3 and above

**To Reproduce**<br />
In the `items` array passed to `RNPickerSelect`, if one of the items has a value of empty string, then `onValueChange` will trigger immediately upon render. 

items array example for triggering the issue:
```
[
  { label: 'item', value: '3' },
  { label: 'item 2', value: '' },
]
```

**Expected behavior**<br />
`onValueChange` should only trigger when a value changes.

**Smartphone:**<br />
-   OS: Android 5.1
-   react-native-picker-select version: 5.2.4
-   react-native version: 0.55.4
-   react version: 16.3.1

**Reproduction and/or code sample**<br />
https://snack.expo.io/SyFyj2DN4

**Comment by lfkwtz** [comment]
Hey @zaytrix - thanks for the bug report. Having an empty items array is definitely an edge case I never considered. 

Do you mind finishing the full bug report, especially including a code sample and/or expo.io reproduction

**Comment by zaytrix** [comment]
Update!
I was finally able to create a snack that reproduces this issue. As it turns out, it did not have to do with an empty array, but instead with a value of empty string, as I've now explained above.
I've also figured out that it was a change in 5.2.3 that caused this issue to occur.
I hope this helps!

**Comment by lfkwtz** [comment]
How bizarre - looks like the culprit was `left: 0` when using the headless mode -- which isn't needed anyways.

Verify that #144 fixes it for you and i'll merge it in.

There are some [upstream](https://github.com/facebook/react-native/pull/22821) picker issues on Android that have been fixed recently - this one may be related.
