### ISSUE TITLE
Toggling Dropdown Exits Android Fullscreen

### ISSUE THREAD

**Issue by JPStrydom** [lawnstarter/react-native-picker-select#142]
**Bug Description**<br />
We're using the latest version of this package with React Native v0.55.3 along with [react-native-media-suite](https://www.npmjs.com/package/react-native-media-suite) v0.2.8. The media suite package allows one to switch Android into fullscreen mode (i.e. hiding the Android bottom controls and the Android top status bar) by using their `this.videoRef.presentFullscreenPlayer();` methood. Whenever I toggle this package's dropdown while the video is in fullscreen, it jumps out of fullscreen mode. I'm not sure if this is related to this package or to the media-suite-package, but perhaps your package is doing something to the android fullscreen?

**To Reproduce**<br />
Steps to reproduce the behavior (Android only):

1.  Fullscreen and video with an overlaying dropdown
2.  Toggle the dropdown
3.  See the device jump out of fullscreen mode

**Expected behavior**<br />
It would be desirable that the dropdown does not toggle the device's fullscreen state

**Smartphone (please complete the following information):**<br />
-   Device: Android devices (tested on Samsung S8 and LG G5)
-   OS: Android
-   react-native-picker-select version: 5.2.4
-   react-native version: 0.55.3
-   react version: 16.5.2

**Comment by lfkwtz** [comment]
Need a code sample or reproduction. Please follow the template.

**Comment by JPStrydom** [comment]
A basic example will look something like this:
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Video from 'react-native-media-suite';
import RNPickerSelect from 'react-native-picker-select';

export default class VideoPlayerView extends Component {
    render() {
        return (
            <View style={styles.fullScreen}>
                <Video
                    style={styles.fullScreen}
                    fullscreen
                    src="https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd"
                />
                <View style={styles.dropdownWrapper}>
                    <RNPickerSelect
                        items={[
                            { label: 'Orange', value: 'orange', key: 'orange', color: 'orange' },
                            { label: 'Blue', value: 'blue', key: 'blue', color: 'blue' }
                        ]}
                        onValueChange={value => console.log('Value set to:', value)}
                        mode="dropdown"
                        style={styles.dropdown}
                    />
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    fullScreen: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
        flex: 1,
        zIndex: 10
    },
    dropdownWrapper: {
        height: 200,
        position: 'absolute',
        left: 0,
        bottom: 0,
        right: 0,
        display: 'flex',
        justify: 'center',
        alignItems: 'center',
        zIndex: 100,
        backgroundColor: '#500'
    },
    dropdown: {
        height: 50,
        width: 400
    }
});
```
Pressing the dropdown will take the device out of fullscreen mode.

**Comment by lfkwtz** [comment]
Thanks -- have you tried inserting the native `Picker` in place of this component to see if it still occurs?

**Comment by JPStrydom** [comment]
So I couldn't get the behaviour to replicate using the native picker, but I noticed that the previous version of `react-native-picker-select` that we had installed (`4.1.0`) did not have this issue. Maybe something changed between v4 and v5 that would cause this?

**Comment by lfkwtz** [comment]
Can you create a reproduction of the issue via snack.expo.io ?

**Comment by JPStrydom** [comment]
The media suite requires native code changes, so I don't think it'll run on expo?

**Comment by lfkwtz** [comment]
Ah, those dropdowns on the readme hid that from me on quick glance

**Comment by lfkwtz** [comment]
Can you create a sample repo where the problem exists that I can clone down and debug?

**Comment by JPStrydom** [comment]
I'll see what I can do 👍

**Comment by lfkwtz** [comment]
gunna close this out -- i'll reopen if you send me a sample repo.
