### ISSUE TITLE
onValueChange parameter value is wrong

### ISSUE THREAD

**Issue by caioedut** [lawnstarter/react-native-picker-select#146]
When I change the value once, the parameter value in onValueChange be right.
But when I change again, the parameter gives the previous selected value.

Eg:
Rendered with null value.
I changed to 1.
Then I get 1 in parameter.
Then, I changed again to 2.
Now the parameter gives 1 (instead of 2).
Then, I changed again to 3.
Now the parameter gives 2 (instead of 3).

**Comment by lfkwtz** [comment]
Please don’t ignore the bug report template. It exists for a reason.

**Comment by lfkwtz** [comment]
Please don’t ignore the bug report template. Feel free to reopen or edit following the template.
