### ISSUE TITLE
Using subscripts or superscripts in picker items

### ISSUE THREAD

**Issue by DevonTomatoSandwich** [lawnstarter/react-native-picker-select#148]
**Is your feature request related to a problem? Please describe.**
Thanks for making a great component! I'd like to add subscripts or superscripts in my picker. At the moment i think you can only put strings into each picker option. 

**Describe the solution you'd like**
Would be great if you could put Views into each picker item so i could add subscript styling to my strings

**Describe alternatives you've considered**
using the Icon prop (but this wouldn't come up in the list)
Modal
Alert
Tried to make my own picker component but was glitchy

**Additional context**
Instead of using  the ^ symbol in my strings below it would be cool to superscript the text afterwards
![screenshot_20190223-160156_expo](https://user-images.githubusercontent.com/35514332/53281934-b4339180-3784-11e9-916e-9d8d3f62fa3b.jpg)

**Comment by lfkwtz** [comment]
if that's a limitation, it's a limitation of the native Picker component and not something this library would be able to override.

you may be able to get away with what you're attempting using ascii though
https://lingojam.com/SuperscriptGenerator

**Comment by DevonTomatoSandwich** [comment]
That SuperscriptGenerator should work for now.
Thanks !
