### ISSUE TITLE
Selecting the placeholder item causes a crash/duplicate placeholder items

### ISSUE THREAD

**Issue by ylac** [lawnstarter/react-native-picker-select#149]
**Describe the bug**<br />
The app crashes if you select the placeholder item after selecting another item.

This occurs regardless of whether a placeholder is provided.

Adding an item object with `value: null` results in duplicate placeholder items appearing in the dropdown.

**To Reproduce**<br />
### Crash
1.  Select a non-placeholder item
2.  Select the placeholder item
3.  See error: `TypeError: TypeError: Cannot read property 'label' of undefined`.

### 
1. Add an item object with a value of `null` to the `items` array.

**Expected behaviour**<br />
The placeholder item should just be selected. There should only be one placeholder item.

**Screenshots**<br />
See below.

**Smartphone (please complete the following information):**<br />
-   Device: Samsung S6
-   OS: Android 7.0
-   react-native-picker-select version: 6.0.0
-   react-native version: 0.55
-   react version: 16.3.1

**Reproduction and/or code sample**<br />
### Crash
```
      const items = [
           {
              label: 'Packed By Owner',
              value: 'packed_owner'
           }
       ]
      <RNPickerSelect
        items={items}
        onValueChange={onChange}
        value={value}
      />
```

### Duplicate placeholders
```
const items = [
           {
               label: 'Select items...',
               value: null
           },
           {
              label: 'Packed By Owner',
              value: 'packed_owner'
           }
       ]
```
![screenshot_20190225-162208](https://user-images.githubusercontent.com/25894581/53315918-ba0eab80-3919-11e9-9e9d-01b051b125e5.png)

**Comment by lfkwtz** [comment]
So you’re passing a placeholder in to the items array?

**Comment by ylac** [comment]
If I use the placeholder prop, and select a non-placeholder item, then the placeholder item, I trigger an exception as described above.

**Comment by lfkwtz** [comment]
Can you produce a reproduction on snack.expo.io?

**Comment by lfkwtz** [comment]
@ylac

**Comment by ylac** [comment]
Can't repro, closing thanks.

**Comment by ArturCherkanov** [comment]
I faced with the same problem, I downgraded react native version to 0.63.0, it resolved the problem
