### ISSUE TITLE
Picker title

### ISSUE THREAD

**Issue by gogumai** [lawnstarter/react-native-picker-select#153]
Hi @lfkwtz !

Is there a way to have a title in the Done bar?

Like this:

![image](https://user-images.githubusercontent.com/16405232/53423285-dbc26e00-39bf-11e9-8790-64133e272afd.png)

Are you planning on adding that? Thanks!

**Comment by francoSimeone** [comment]
@gogumai maybe an option could be changing the 'Done' styles to show that text as your title.

![image](https://user-images.githubusercontent.com/17005927/53425203-5a6cda80-39c3-11e9-903e-203908a3efa6.png)

**Comment by lfkwtz** [comment]
@francoSimeone is right. you could change the "Done" text and styles easily enough to match that.

**Comment by gogumai** [comment]
ok @lfkwtz, but the DONE and the title would have 2 different purposes right?

Are you up to accept a contribution/PR for adding this feature?

**Comment by lfkwtz** [comment]
yeah doing this would basically be replacing the DONE text with your custom needs.

unfortunately i'm not interested in opening up that space for another element or component, as that breaks the original intention of this component which is to replicate the native picker.

if you need to modify the modal to that level, you'd be better off forking the project to meet your needs
