### ISSUE TITLE
I am trying to change the style of Picker Item on both ios and andriod but with no luck.

### ISSUE THREAD

**Issue by karajaNaji** [lawnstarter/react-native-picker-select#154]
I am trying to change the style of Picker Item on both ios and andriod but with no luck. sample of the code I use

 textStyle={{ color: "#5cb85c" }}
 itemStyle={{
                        backgroundColor: "#d3d3d3",
                        marginLeft: 0,
                        paddingLeft: 10
                      }}
 itemTextStyle={{ color: '#788ad2' }}

-   Device: [e.g. Note5]

-   react-native-picker-select version: [^6.0.0]
-   react-native version: ["https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"]
-   react version: [16.5.0]

**Comment by lfkwtz** [comment]
This question belongs on stackoverflow

**Comment by sboudouk** [comment]
Seriously ? lol.

**Comment by lfkwtz** [comment]
Not sure who that's directed to, but it adds nothing of value
