### ISSUE TITLE
Items and/or the placeholder not displaying in the picker

### ISSUE THREAD

**Issue by alandoni** [lawnstarter/react-native-picker-select#157]
### YOU MUST FILL OUT THE ENTIRE BUG REPORT

**Describe the bug**<br />
I am unable to correctly display the items or the placeholder in the picker

**To Reproduce**<br />
I  added this code:
`<RNPickerSelect
        placeholder={{label: 'Selecione um produto', value: null}}
        style={pickerStyle}
        selectedValue={this.state.product.categoryId}
        onValueChange={this.setCategory}
        items={[ {label: 'test 1', value: 1}, {label: 'test 2', value: 2} ]}
/>

const pickerStyle = {
	inputIOS: {
		color: 'white',
		paddingTop: 13,
		paddingHorizontal: 10,
		paddingBottom: 12,
	},
	inputAndroid: {
		color: 'white',
	},
	placeholderColor: 'white',
	underline: { borderTopWidth: 0 },
	icon: {
		position: 'absolute',
		backgroundColor: 'transparent',
		borderTopWidth: 5,
		borderTopColor: '#00000099',
		borderRightWidth: 5,
		borderRightColor: 'transparent',
		borderLeftWidth: 5,
		borderLeftColor: 'transparent',
		width: 0,
		height: 0,
		top: 20,
		right: 15,
	},
};
`

**Expected behavior**<br />
The items and the placeholder should display properly

**Screenshots**<br />
![whatsapp image 2019-03-05 at 13 14 51](https://user-images.githubusercontent.com/12752268/53819746-4851e580-3f49-11e9-8c59-586519fc0936.jpeg)

**Smartphone (please complete the following information):**<br />
-   Device: Xiaomi Redmi Note 5
-   OS: Android 8.1.0
-   react-native-picker-select version: 6.0.0
-   react-native version: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
-   react version: 16.5.0

**Reproduction and/or code sample**<br />
I don't know why, but on snack.expo, the code works, maybe it's a problem with my smartphone

**Comment by lfkwtz** [comment]
from what i can see, your font color is white and your background is white

**Comment by lfkwtz** [comment]
gunna close this out. let me know if that didn't solve it
