### ISSUE TITLE
Replace chevrons with "Cancel" text

### ISSUE THREAD

**Issue by jakebloom** [lawnstarter/react-native-picker-select#160]
**Is your feature request related to a problem? Please describe.**
At the moment we are required to have chevrons on the left hand side of the done bar, or get rid of the done bar totally.

**Describe the solution you'd like**
I'd like to have an option of having a "Cancel" button there that closes the picker, similar to how the date selector is implemented in iOS. 

Maybe we could have a prop, similar to `Icon` that allows us to specify content for the left side of the done bar

**Describe alternatives you've considered**
We haven't considered alternatives, this seems like a fairly trivial UI change.

**Comment by lfkwtz** [comment]
Sounds reasonable -- Ideally I'd like a solution so this and #164 can be solved in one universal/flexible way.

**Comment by JaWoGit** [comment]
Is there any possibility to add this in the near future? I would love to use this in my application.
This would be awesome! 
Cheers 👍

**Comment by lfkwtz** [comment]
@JaWoGit if you have suggestions and/or a PR on how we could combine this and #164 into one feature i'm open to them

**Comment by lfkwtz** [comment]
closing for now as this will live in the feat. req board

**Comment by jrapala** [comment]
I created a [pull request](https://github.com/lawnstarter/react-native-picker-select/pull/188) that is on it's way to solving this issue.
Anyone have any suggestions on how to make this more universal?
