### ISSUE TITLE
[Feature Request] Support empty items array

### ISSUE THREAD

**Issue by gluons** [lawnstarter/react-native-picker-select#161]
**Is your feature request related to a problem? Please describe.**

[Problem here](https://github.com/lawnstarter/react-native-picker-select/issues/138#issuecomment-469966354).

@lfkwtz:
> you're initializing with an empty items array. This is not currently supported.

<br>

As @lfkwtz said, I can't initialize `items` with empty array now.

**Describe the solution you'd like**

Able to initialize `items` with empty array without error.

**Describe alternatives you've considered**

**Additional context**

See [#138 (comment)](https://github.com/lawnstarter/react-native-picker-select/issues/138#issuecomment-469966354)

**Comment by lfkwtz** [comment]
added to feature request board
