### ISSUE TITLE
Android always dropdown mode

### ISSUE THREAD

**Issue by sinodko** [lawnstarter/react-native-picker-select#163]
Hello, I'm encountering weird issue. In your examples there is always "modal" mode of picker ( when I run examples from expo on my Xiaomi mi 8, I'm getting modal mode),  but when I copy/paste examples into my app, on android I always get "dropdown" mode picker. Even if I set prop `{pickerProps: {mode: "modal"}}` it is not doing anything and I'm always getting dropdown type of picker. 

Is this normal behaviour?

Enclosing my code:

```
<RNPickerSelect
        placeholder={placeholderObject}
        items={itemsList}
        onValueChange={this.onValueChange}
        onClose={this.onDonePress}
        style={styles.pickerClassic}
        useNativeAndroidPickerStyle={false} // there is no difference when i set this to true
        value={this.state.currentValue}
        Icon={icon}
        pickerProps={{ mode: "dialog" }}
      />
```

**Comment by lfkwtz** [comment]
there is no `mode: "modal"` - it's either `dialog` or `dropdown` --- can you clarify which isn't working as expected?

**Comment by sinodko** [comment]
I meant `mode: "dialog"`,, sorry for that.. I would expect to get modal window, not dropdown menu when i open the picker. Even when I'm running example from expo, when I open the picker, modal is shown. But in my app, it always open picker items in dropdown instead of modal.

**Comment by lfkwtz** [comment]
Not sure. Can you update your original message to use the bug template?

And include a link to a github repo where this problem can easily be reproduced on an android device

**Comment by sinodko** [comment]
Yep i will update it tomorow :) thanks for following up!

**Comment by lfkwtz** [comment]
Also - have you verified the issue occurs only on this package and not also on the native RN Picker?

**Comment by sinodko** [comment]
My problem is related to this issue https://github.com/facebook/react-native/issues/24055

**Comment by lfkwtz** [comment]
Good find on the upstream issue. This is precisely why we always stay [one major version behind](https://medium.com/lawnstarter-engineering/react-native-one-year-later-what-weve-learned-c23dc13cec80).

**Comment by dantenol** [comment]
Any updates? it still opens as dropdpwn on RN v0.61.5 on an android device

**Comment by lfkwtz** [comment]
https://github.com/facebook/react-native/issues/24055
