### ISSUE TITLE
Add support to caption

### ISSUE THREAD

**Issue by helielson** [lawnstarter/react-native-picker-select#164]
**Is your feature request related to a problem? Please describe.**
No. The layout I'm developing defines a picker with a caption that looks like a [InputAccessoryView](https://facebook.github.io/react-native/docs/inputaccessoryview)

**Describe the solution you'd like**
A prop like `caption` in order to render a custom text between the arrows and the done button.

**Describe alternatives you've considered**
I didn't find any a better alternative than add this prop.

**Additional context**
![image](https://user-images.githubusercontent.com/1201847/55030055-46c88a00-4fea-11e9-8e0a-476be5bd0e77.png)

**Comment by KoAi** [comment]
Caption option is a very good idea

**Comment by lfkwtz** [comment]
closing for now as this will live in the feat. req board
