### ISSUE TITLE
Add support to initial index or value props

### ISSUE THREAD

**Issue by maykonmichel** [lawnstarter/react-native-picker-select#166]
**Is your feature request related to a problem? Please describe.**
No. I'm just trying to set initial props.

**Describe the solution you'd like**
Add two news props: initialIndex and intialProps.

**Describe alternatives you've considered**
Sync prop value of lib's state with the state of my component, but this it's so hard to implement.

**Comment by lfkwtz** [comment]
if you set the `value` prop to the value of one of your picker items, it will handle this as is. is that not working for you?
