### ISSUE TITLE
run after interactions

### ISSUE THREAD

**Issue by tjbenton** [lawnstarter/react-native-picker-select#168]
This is related to your [todo comment](https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L171) about running callbacks after animations. It's just a suggestion since i saw it while looking through the code.

Easiest way to do something after animations is to use the built in [`InteractionManager`](https://facebook.github.io/react-native/docs/interactionmanager#docsNav)

```js
import { InteractionManager } from 'react-native'

InteractionManager.runAfterInteractions(() => {
  // when called this will run after all interactions are finished running on the page
}) 
```

The other suggestion is to update `togglePicker` to accept a callback so you can pass the `callback` into the [`setState`](https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L238) on [238](https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L238). 

These 2 things will help with any issues in trying to prevent those callbacks from running too soon. 

Hope this helps, sorry I don't have more time to make a PR

**Comment by jgrocott** [comment]
@tjbenton Full credit to you sir for the suggestions above. PR created with callback solution. InteractionManager was a little inconsistent for me on iOS. Callbacks seem to be solid.

**Comment by lfkwtz** [comment]
looks like #177 handles this
