### ISSUE TITLE
Multiple items highlighted/grey after 2nd + attempt to select

### ISSUE THREAD

**Issue by bosz** [lawnstarter/react-native-picker-select#169]
### YOU MUST FILL OUT THE ENTIRE BUG REPORT

**Describe the bug**<br />
After the second attempt to select an item, when the item is clicked and i come back to open up the picker, it shows the current item selected(grey) which is ok but then shows about 2-4 other items selected(grey-ed out). This creates a lot of confusion with the user as they won't know which is actually selected/active

**To Reproduce**<br />

1.  Go to https://snack.expo.io/@fongoh/react-native-picker-select
2.  Click on any of the dropdown (selects)
3.  Scroll down to select an item
4.  Click on same dropdown as in (2)
4.  Notice the selected item in (3) is highlighted (grey) but also, 1-4 other items are selected(grey); the error

**Expected behavior**<br />
I expect only 1 item on the list to be selected(grey/active) at any time making it very easy ui/ux wise for the user to know which item he has currently selected

**Screenshots**<br />
![Screenshot of multiple selected(grey-ed) items](https://user-images.githubusercontent.com/6331902/56405548-a1a97600-6264-11e9-85e1-8fc6efbccc87.png)

**Smartphone (please complete the following information):**<br />
Expo

**Reproduction and/or code sample**<br />
https://snack.expo.io/@fongoh/react-native-picker-select

**Comment by lfkwtz** [comment]
without looking into this - my assumption is it's related to #114

**Comment by bosz** [comment]
> without looking into this - my assumption is it's related to #114

@lfkwtz  is right, that's the same issue. Thanks for pointing it out to me. 

To solve it, i just had to add a color attribute to each of the objects like so 
```
{
    label: 'Football',
    value: null,
    color: 'black', // this does the job
  },
```

Thanks again for the pointer.

**Comment by bosz** [comment]
BTW, great plugin here, its really helping me.

**Comment by lfkwtz** [comment]
no problem - glad it's helping you.

IIRC the last time I looked for an upstream issue on this one in the react-native repo I couldn't find one, but I had forgotten to create one. so -- you may want to open one up.

**Comment by BananZGan** [comment]
This occurs on latest version when the options is longer than your screen on Android.
I had to set custom color to fix it as well.

**Comment by SolYakir** [comment]
Hi, isn't explicitly setting the color on a native list like this one could cause accessibility issues (contrasts and stuff)?
Also, by the way, the solution here doesn't solve the issue when dark mode is on.. I added a 'white' option when dark mode is on..
