### ISSUE TITLE
onDonePress on IOS emulator 

### ISSUE THREAD

**Issue by abdelwehed** [lawnstarter/react-native-picker-select#171]
**Describe the bug**<br />
Hello,

I trying to add onDonePress to my picker on IOS but the callback is not triggered.
Any one is having same issue ?

Thank you :).

**To Reproduce**<br />

1.  Add onDonePress props to the picker
2.  Open the picker and click done

**Expected behavior**<br />
onDonePress triggered.

**Smartphone (please complete the following information):**<br />
-   Device: Iphone X
-   OS: IOS 12.1
-   react-native-picker-select version: 3.1.2
-   react-native version: 0.58.3
-   react version: 16.6.3

**Comment by lfkwtz** [comment]
Provide a link to a reproduction of this issue on https://snack.expo.io **or a good explanation on why you can not**. Not including a link will result in a significant delay in our ability to address this issue.
