### ISSUE TITLE
onDonePress on IOS simulator

### ISSUE THREAD

**Issue by abdelwehed** [lawnstarter/react-native-picker-select#174]
**Describe the bug**<br />
I am trying to add onDonePress to my picker on IOS but it is not triggered.

**To Reproduce**<br />

1.  Add onDonePress prop to the picker
2.  Open the picker and click done

**Expected behavior**<br />
onDonePress triggered (for my code sample it should display the console log).

**Smartphone (please complete the following information):**<br />
-   Device:  Iphone X
-   OS: IOS 12.1
-   react-native-picker-select version: 3.1.2
-   react-native version: 0.58.3
-   react version: 16.6.3

**Reproduction and/or code sample**<br />
```
<RNPickerSelect
          placeholder={RNPlaceholder}
          items={data}
          onValueChange={(val) => {});
          value={selectedValue}
          onDonePress={() => { console.log('onDonePress clicked') }}
        />
```

**Comment by lfkwtz** [comment]
https://github.com/lawnstarter/react-native-picker-select/releases/tag/4.3.0
