### ISSUE TITLE
Placeholder does not seem to update even if objects are different

### ISSUE THREAD

**Issue by dextermb** [lawnstarter/react-native-picker-select#178]
### YOU MUST FILL OUT THE ENTIRE BUG REPORT

**Describe the bug**<br />
I seem to be having issues with updating the placeholder after the component is mounted.

**To Reproduce**<br />

1.  Have a managed loading state
2.  Set input to be loading
3.  Have a ternary to switch between placeholders
4.  See error

**Expected behavior**<br />
The placeholder should update to the _loading_ placeholder and back to the given placeholder

**Smartphone (please complete the following information):**<br />
-   Device: `iPad Mini`
-   OS: `iOS 12.2`
-   react-native-picker-select version: `^6.1.0`
-   react-native version: `https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz`
-   react version: `16.5.0`

**Reproduction and/or code sample**<br />
##### Investigation:
```jsx
export default class RNPickerSelect extends PureComponent {
    // <snip>

    static getDerivedStateFromProps(nextProps, prevState) {
        // <snip>

        // update selectedItem if value prop is defined and differs from currently selected item
        const { selectedItem, idx } = RNPickerSelect.getSelectedItem({
            items,
            key: nextProps.itemKey,
            value: nextProps.value,
        });

        const selectedItemChanged =
            !isEqual(nextProps.value, undefined) && !isEqual(prevState.selectedItem, selectedItem);

        console.log(selectedItem, selectedItemChanged) // <-- Logging here

        if (itemsChanged || selectedItemChanged) {
            if (selectedItemChanged) {
                nextProps.onValueChange(selectedItem.value, idx);
            }

            return {
                ...(itemsChanged ? { items } : {}),
                ...(selectedItemChanged ? { selectedItem } : {}),
            };
        }

        return null;
    }

    // <snip>
}
```

###### Output:
```
Object {
  "color": "#9EA0A4",
  "label": "Select an item...",
  "value": null,
} false
Object {
  "label": "Loading...",
  "value": null,
} false
```

##### JSX:
```jsx
<Select
    {...props}
    placeholder={(
        this.isLoading(name)
            ? {
                label: 'Loading...',
                value: null,
            }
            : null
    )}
    disabled={disabled}
    value={this.getValue(name)}
    items={options}
    style={{
        inputIOS: newStyle,
        inputAndroid: newStyle,
    }}
    onValueChange={text => call([this.onChange, onChange], { field, text })}
/>
```

**Comment by dextermb** [comment]
After investigating the issue it seems to be down to the input not having a `string` value. But once the placeholder updates (value of `null`) then it fires an `onValueChange` that then clears the `string` value.

I think there should be a prop or similar to disable resetting of the value if the new selected item's value is `null`.

**Comment by lfkwtz** [comment]
Why not just have the ternary switch between an empty string and “Loading”?

On mobile and just taking a quick glance at this - so I may have missed something.

**Comment by dextermb** [comment]
> Why not just have the ternary switch between an empty string and “Loading”?

Just an example to show that the placeholder object is completely different. This is not how it is in practice.

**Comment by dextermb** [comment]
> Why not just have the ternary switch between an empty string and “Loading”?

I wasn't aware that it should just be a string? I assume it'd still have the same issue though.

**Comment by lfkwtz** [comment]
The placeholder prop expects and empty object or an object in the proper format. You’re passing in null instead - not sure how that’s going to react.

**Comment by dextermb** [comment]
> The placeholder prop expects an empty object or an object in the proper format. You’re passing in null instead - not sure how that’s going to react.

Interesting. I'm passing in the value `null` as seen by the default placeholder. I can change that.

**Comment by lfkwtz** [comment]
i mean

```js
placeholder="{}"
```

or

```js
placeholder="{ label: '', value: null }"
```

are correct.

```js
placeholder="null"
```

^ this may break something. Also - can you fill out the entire bug report? You left off the versions.

**Comment by dextermb** [comment]
> ```js
> placeholder="null"
> ```

The placeholder of _null_ becomes `placeholder={null}` which I assume is the same as not passing anything. As mentioned the _null_ is just to show that there's no pointers between the changing placeholder.

> ```js
> placeholder="{ label: '', value: null }"
> ```

This is what is currently being done.

---

I'll update the report to include versions.

**Comment by dextermb** [comment]
```json
{
	"main": "node_modules/expo/AppEntry.js",
	"scripts": {
		"start": "expo start",
		"android": "expo start --android",
		"ios": "expo start --ios",
		"eject": "expo eject",
		"postinstall": "node ./quiet-console.js"
	},
	"dependencies": {
		"@expo/vector-icons": "latest",
		"@ninetynine/call": "^1.1.0",
		"@ninetynine/noop": "^1.1.1",
		"expo": "^32.0.0",
		"lodash": "^4.17.11",
		"prop-types": "latest",
		"react": "16.5.0",
		"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
		"react-native-datepicker": "^1.7.2",
		"react-native-picker-select": "^6.1.0",
		"react-navigation": "^3.11.0",
		"react-navigation-header-buttons": "^2.3.1",
		"sentry-expo": "^1.12.0"
	},
	"devDependencies": {
		"babel-preset-expo": "^5.0.0"
	},
	"private": true
}
```

Seemingly setting `placeholder` as a string crashes the app.
```
placeholder="Text"
```

**Comment by lfkwtz** [comment]
I’m sure it does - it expects an object.

So the ternary of “Loading” to “” didn’t work?

**Comment by lfkwtz** [comment]
I'll look into this and get back to you

**Comment by lfkwtz** [comment]
Related to #112 - placeholder won't update because it's the currently selected value and `selectedItemChanged` doesn't fire in this instance. Would be fixed if this is made into a controlled component - or could potentially be specialcased.

**Comment by bikashsahucbnits** [comment]
Warning: value prop on select should not be null. Consider using an empty string to clear the component or undefined for uncontrolled components.

**Comment by Lopatovas** [comment]
An easy approach to fixing the placeholder issue is to change the key of the picker component when the placeholder object changes. This forces the React DOM to re render the element.

**Comment by HarshitMadhav** [comment]
**Set the placeholder like this**
`placeholder={{ label: 'Select Gender', value: null, color: '#909090', }}`

It works for me.

**Comment by yl-flyer** [comment]
Same bug here
When i reset the select it still remember the old value:
`
             <RNPickerSelect
                    key="csp"
                    onValueChange={(value): void => SetSalePointsFilter({ key: 'csp', value })}
                    Icon={(): React.ReactNode => <Unicons name="angle-down" size={22} />}
                    useNativeAndroidPickerStyle={false}
                    placeholder={{
                        label: 'CSP',
                        value: null,
                        ...styles.placeholderColor,
                    }}
                    value={listing.filters.csp}
                    style={styles.select}
                    items={items.csp}
                />
`

**Comment by yl-flyer** [comment]
> 
> 
> Same bug here
> When i reset the select it still remember the old value:
> 
> ```
> <RNPickerSelect
>      key="csp"
>      onValueChange={(value): void => SetSalePointsFilter({ key: 'csp', value })}
>      Icon={(): React.ReactNode => <Unicons name="angle-down" size={22} />}
>      useNativeAndroidPickerStyle={false}
>      placeholder={{
>           label: 'CSP',
>           value: null,
>           ...styles.placeholderColor,
>       }}
>       value={listing.filters.csp}
>       style={styles.select}
>       items={items.csp}
>  />
> ```

Ok, it works for me.
To reset the select, set the component value to null and the value of placeholder also null

**Comment by usfslk** [comment]
I don't understand how this placeholder works, it display it fine using  `placeholder={ {label: studio.room_type, value: studio.room_type} }` but then the item get added to picker list? why a placeholder is added to the list? I don't get it 

also when I try using the value prop i can no longer interact with the picker it stuck on value item, this library is so confusing, why does react native provide the native picker? I tried react-native-picker it don't show at the bottom (on ios) like this one

**Comment by shaheer912** [comment]
In my case, placeholder was not getting updated if it is based on state, I solved this using a hack.
In index.js file of the react-native-picker-select
Change following line
`const selectedItemChanged =
            !isEqual(nextProps.value, undefined) && !isEqual(prevState.selectedItem, selectedItem);`
to
`const selectedItemChanged =
            !isEqual(nextProps.value, undefined) || !isEqual(prevState.selectedItem, selectedItem)
|| prevState.selectedItem.valued != selectedItem.value
;`

Its a hack but it works.
