### ISSUE TITLE
How to remove placeholder and there space also

### ISSUE THREAD

**Issue by Ektasahusahu** [lawnstarter/react-native-picker-select#179]
Right now i am passing blank in place holder but it's take a row space  but i want to remove placeholder row also please help me.

Thanks.

**Comment by kristoff2016** [comment]
Any solution on this?

**Comment by lfkwtz** [comment]
`An empty object can be used if you'd like to disable the placeholder entirely`

**Comment by kristoff2016** [comment]
Yes, I just fount it `placeholder={{}}` thanks

**Comment by kristoff2016** [comment]
@lfkwtz thanks for great plugin it's saved my times. thanks for great works.
