### ISSUE TITLE
onValueChange is called many times.

### ISSUE THREAD

**Issue by Achilles718611** [lawnstarter/react-native-picker-select#180]
Following is code. 
onValueChange={value => {
            this.setState({
              favSport0: value,
            });
          }}

When we change value in iOS, onValueChange is called many times and app is crashed.

![image](https://user-images.githubusercontent.com/31845458/58271846-8f6cab80-7dbf-11e9-9ba3-1c6c2b939e9e.png)

When select value first time it works, but from second time it doesn't work.

**Comment by lfkwtz** [comment]
update with the proper bug template

**Comment by Achilles718611** [comment]
Hello, how are you?
Nice to meet you.
How about change code like followings?
this.setState({
    selectedItem: this.state.items[index],
}, () => onValueChange(value, index));

Thanks for your time.

**Comment by SAHITYASAI** [comment]
I'm working on loading forms dynamically. When trying to update dropdown object in array of objects using redux, i'm facing the same issue. I even tried using the solution mentioned by @Achilles718611 but with no effect. Can someone help me please. Thanks in advance.
