### ISSUE TITLE
No option to remove/hide arrow buttons.

### ISSUE THREAD

**Issue by ravindraguptainfogain** [lawnstarter/react-native-picker-select#181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lfkwtz** [comment]
Use css and match the background color

**Comment by ravindraguptainfogain** [comment]
This does not seem to be the fix, rather a work around. Can you please introduce an option to conditionally render arrow buttons.

**Comment by lfkwtz** [comment]
#190

**Comment by andi-lis** [comment]
you can add 
```
chevronDown: {
    display: "none",
  },
  chevronUp: {
    display: "none",
  },
```

in the StyleSheet

**Comment by marrow1** [comment]
Matching drop down will certainly hide is display but if you closely notice when you select the picker to actually select any item there a ripple effect which then highlight the drop down which is located at the extreme right, so it gives a sens out of nowhere where the hell that ripple effect comes from, so kindly fix this

**Comment by fujifujifuji** [comment]
I use this css

```
inputAndroid: {
  backgroundColor: '#FFFFFF',
}
```

**Comment by hapo-duongdv** [comment]
@fujifujifuji Good for android :D
