### ISSUE TITLE
After a specific height the color of value of drop down is greyed and sometime those value can't be selected.

### ISSUE THREAD

**Issue by yadav-durgesh** [lawnstarter/react-native-picker-select#182]
### After a specific height the color of the value of dropdown is greyed and sometime those value can't be selected.

**Describe the bug**<br />
Random value are grey in color (Height specific may be). and those value sometimes doesn't get selected 

**To Reproduce**<br />

1.  Go to 'https://snack.expo.io/@durgesh199/react-native-picker-select'
2.  Click on 'In android mobile drag/scroll the select box'
3.  Scroll down to 'You will see some grey text'
4.  See error 'Sometimes this value can't be selected. I don't know why? '

**Expected behavior**<br />
Those value must not be greyed and it should allow them to get selected.

**Screenshots**<br />
Just add more option {label,value} for select picker to view error.

**Smartphone (please complete the following information):**<br />
-   Device:Any Android Phone
-   OS: Any Android OS
-   react-native-picker-select version: 6.1.0
-   react-native version: 0.58.6
-   react version: 16.6.3

**Reproduction and/or code sample**<br />
https://snack.expo.io/@durgesh199/react-native-picker-select
Just add more option {label,value} for select picker to view error.

If you can help me as soon as possible it will be a great effort. Thanks

**Comment by lfkwtz** [comment]
#114
