### ISSUE TITLE
onFocus not triggered

### ISSUE THREAD

**Issue by idoor88** [lawnstarter/react-native-picker-select#186]
I am trying to add highlight feature to the component when the RNPickerSelect component is clicked, but the onFocus() is never triggered:
<RNPickerSelect
                                placeholder={placeholder5}
                                items={countryItem}
                                editable={true}
                                onValueChange={(value) => this.setState({ country: value })}
                                value={this.state.country}
                                useNativeAndroidPickerStyle={false}
                                style={borderColorDistrict}
                                ref={(ref) => this.countryRef = ref}
                                onFocus={()=> {
                                  console.log("countryRef onFocus")
                                  this.setState({ isFocused:true});
                                }}
                            />

react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 52.70 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.6 => 0.59.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-cn-richtext-editor: 1.0.33
      react-native-git-upgrade: 0.2.7

**Comment by lfkwtz** [comment]
update with the proper bug template

**Comment by liplylie** [comment]
use `onOpen` instead of `onFocus`

**Comment by ibrag474** [comment]
onOpen does not work either
