### ISSUE TITLE
how put chevron on left

### ISSUE THREAD

**Issue by sootood** [lawnstarter/react-native-picker-select#192]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lfkwtz** [comment]
this question belongs on stackoverflow

**Comment by mqtik** [comment]
With all due respect, @lfkwtz, In StackOverflow might pass 6 months without an answer.

I understand the need to separate places, but I'm almost certain you would never see the question.

This question belongs anywhere it can be answered.

I'm trying to find a solution for this and "this questions belongs on stackoverflow" it's not helpful at all. Easier to just answer and close the issue.

(please, don't take this the wrong way)
