### ISSUE TITLE
useNativeAndroidPickerStyle outside Expo

### ISSUE THREAD

**Issue by Unforgiven-wanda** [lawnstarter/react-native-picker-select#194]
**Describe the bug**<br />
Using the `useNativeAndroidPickerStyle` in a react-native-cli project (without Expo) I run into the following error: 
![screenshot-2019-07-15_14 02 51 68](https://user-images.githubusercontent.com/4499783/61218160-4a069380-a709-11e9-98b8-3949c3c4233d.png)
You can see the exact code that triggers this in this [snack](https://snack.expo.io/@unforgiven/suspicious-chocolate)

This piece of code works well in an Expo project, but not in a project that does not rely on Expo.

**To Reproduce**<br />
Changing the value from null to some value, or else from a certain value to null. Strangely enough, changing between different values (e.g: football to baseball) doesn't trigger this error.

**Expected behavior**<br />
For it work well, as it does in the expo snack.

**Smartphone (please complete the following information):**<br />
-   Device: Android (both emulator and real device)
-   OS: Android 6 and 8
-   react-native-picker-select version: 6.3.0
-   react-native version: 0.59.9
-   react version: 16.8.3

**Reproduction and/or code sample**<br />
This [snack](https://snack.expo.io/@unforgiven/suspicious-chocolate) works well. however, the same code in a react-native-cli project (without expo) fails with the error mentioned before

Any fix would be most helpful.
Thank you.

**Comment by pravinjohn** [comment]
this worked for me
`style={
{
inputAndroid:{color:'black'}
}
}`

**Comment by csmtcy** [comment]
> this worked for me
> `style={ { inputAndroid:{color:'black'} } }`

this worked for me too, thanks for the solution.

**Comment by lfkwtz** [comment]
Will look into this one when I get a moment - we don't use Expo, so this is an odd one.

**Comment by lfkwtz** [comment]
just ran your expo code on a fresh install of `react-native init` - works fine. if you can reproduce the error and share a github repo let me know
