### ISSUE TITLE
The component is not entirely clickable 

### ISSUE THREAD

**Issue by ramonscampos** [lawnstarter/react-native-picker-select#196]
**Describe the bug**<br />
The component is not entirely clickable in a specific device and inside TeouchableWithoutFeedback and a View.

**To Reproduce**<br />

1.  Create a TouchableWithoutFeedback
2. Create a View inside.
3. Put the picker inside de View.

**Expected behavior**<br />
The picker works independently where I click (inside it, obviously).

**Smartphone (please complete the following information):**<br />
-   Device: Samsung Galaxy S6 (Only. It works perfectly in other devices and emulators)
-   OS: Android 7.0
-   react-native-picker-select version: 6.1.0
-   react-native version: 0.59.10
-   react version: 16.8.3

**Reproduction and/or code sample**<br />
 ```
<TouchableWithoutFeedback onPress={() => { DismissKeyboard(); }}>
                <View>
                    <RNPickerSelect
                        useNativeAndroidPickerStyle={false}
                        placeholder={{
                            label: 'Selecione...',
                            value: null,
                        }}
                        value={this.state.ordemId}
                        items={ordens}
                        onValueChange={(ordemId) => { this.setState({ ordemId }) }}
                        style={{ ...styles }}
                        Icon={() => {
                            return <Icon name="ios-arrow-dropdown" size={30} color={colors.secundary} style={{ marginRight: 5, marginTop: 6 }} />;
                        }}
                    />
                </View>
</TouchableWithoutFeedback>
```

If I remove the view outside RNPickerSelect or the TouchableWithoutFeedback, it works.

**Comment by ramonscampos** [comment]
Well, putting a fragment around the view (just above TouchableWithoutFeedback) worked well.
It's a workaround, but I don't know if is the best way.
If you think is correct you can close this issue.

![image](https://user-images.githubusercontent.com/2568091/61327015-66303080-a7ee-11e9-8239-f56a788da654.png)

**Comment by lfkwtz** [comment]
The component itself is touchable, or you can wrap a touchable component within it. Looks like you're wrapping the component in a touchable element. Not sure how that will affect it but outside the scope of intended use.
