### ISSUE TITLE
Add Item disable option in items would be great

### ISSUE THREAD

**Issue by shubhanus** [lawnstarter/react-native-picker-select#197]
**Is your feature request related to a problem? Please describe.**
There will be some options which we have to show but should not allow to select. Better we allow it to be disabled.

**Describe the solution you'd like**
Add Disable prop for item

**Describe alternatives you've considered**
No

**Comment by lfkwtz** [comment]
this will live on the feature request board

**Comment by bogdandevlpr** [comment]
Is this feature currently available ?

**Comment by codingslash76** [comment]
@lfkwtz Is it possible?

**Comment by alexchencr** [comment]
any update for this feature?

**Comment by lfkwtz** [comment]
looks like you _may_ be able to use it on android. see here: https://github.com/react-native-picker/picker#enabled-1

but would require a pr to support it

https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L285
