### ISSUE TITLE
Make the item on the picker show all the content for long values

### ISSUE THREAD

**Issue by gomesbreno** [lawnstarter/react-native-picker-select#198]
I'm still looking on the documentation, but i didn't find a way to show all the content of a long value on the item of the picker, because on the end of the item display, the part of the string who doesn't fit on a single line doesn't appear.
as shown below
<img width="320" alt="Captura de Tela 2019-07-25 às 14 18 03" src="https://user-images.githubusercontent.com/26438217/61894613-36b4ae80-aee7-11e9-8a67-9f1092655126.png">

**Comment by lfkwtz** [comment]
unfortunately that's a limitation outside the scope of this library

**Comment by programmaker** [comment]
How to decrease items' font size to match width of the screen?

**Comment by karloluis** [comment]
More information on where to the problem lies may help resolve the issue or open a ticket where necessary.
