### ISSUE TITLE
Is there a way to imperatively control the open/closed state of the picker?

### ISSUE THREAD

**Issue by cipriancaba** [lawnstarter/react-native-picker-select#199]
**Is your feature request related to a problem? Please describe.**
I am trying to display the content of the picker on the press of a button.. 

**Describe the solution you'd like**
An imperative way to control opening/closing of the container.. Even a prop like modal uses would be nice

**Describe alternatives you've considered**
I could probably do it with a simple list, but want to have the nice native selector

**Comment by lfkwtz** [comment]
#22
