### ISSUE TITLE
Get Error when setting 'items' dynamically after a axios request in ComponentDidMount

### ISSUE THREAD

**Issue by muzlee1113** [lawnstarter/react-native-picker-select#200]
I'm making an education app and want to create a picker in which the options (items) are classes coming from the database. I got the following error message when using react-native-picker-select

TypeError: TypeError: Attempting to store accessor property on a typed array at index: 0

## What I did was:
In componentDidMount method, I simply got data (which is an array of objects) from mongodb

Then, I mapped the data array into the label-value format that the package requires and push them into a new array

Next, I set the state 'classes' as the new array

Here is the Code

~~~~~
classes
      .find({})
      .asArray()
      .then(docs => {
        console.log("=======get classes to fill picker!!!=========")
        docs.map(item=>{
        let classesPickerData = [] 
        // format the data and push it to 'classesPickerData' array     
        classesPickerData.push({label:item['title'],value:item['_id']})
        })
        console.log(classesPickerData)
        // set the state 'classes' as the new array
       this.setState({ classes: [...classesPickerData], loading: false });
        console.log(this.state.classes)
      })
      .catch(err => {
        console.warn(err);
      });
~~~~~~

In the render function, 

~~~~~~
render() {

    const {classes} = this.state
    console.log(classes)

    return (
……
<RNPickerSelect
              placeholder={placeholder}
              items={[...classes]}
              onValueChange={value => {
                console.log("I reach here!I reach here!I reach here!I reach here!I reach here!I reach here!")
                this.setState({
                  selectedClass: value,
                });
              }}
              style={{
                ...pickerSelectStyles,
                iconContainer: {
                  top: 10,
                  right: 12,
                },
              }}
              value={this.state.selectedClass}
              useNativeAndroidPickerStyle={false}

/>

……
)
~~~~~~~~

## What happened when I ran it
When the page renders, everything runs smoothly and nothing special happened. But when I clicked the component (an input that supposed to open the picker), I didn't get the picker supposed to show up from below, but the error message indicating (I think) something wrong with the line `items={[...classes]}`.

## What I got in my console
In my console, 
1. I got the array I wanted from console.log(classesPickerData) and console.log(this.state.classes) in the componentDidMount function 
2. I got the array I wanted from console.log(classes) in the render function 
3. I didn't get the console.log("I reach here!I reach here!I reach here!I reach here!I reach here!I reach here!") which supposed to be triggered by onValueChange

## What else I've tried
I've tried `items={classes}`, `items={this.state.classes},` and also declaring classesPickerData as a global variable and a key in this.state and using `items={classesPickerData}` and `items={this.state.classesPickerData}` here, but with no luck.

**Comment by lfkwtz** [comment]
This type of question is more appropriate for stackoverflow
