### ISSUE TITLE
RNPickerSelect picker wrap in TouchableOpacity is not working in android

### ISSUE THREAD

**Issue by hassanShahzadW** [lawnstarter/react-native-picker-select#206]
**Issue**<br />
TouchableOpacity is not showing RNPickerSelect in android
When I press on TouchableOpacity sometimes it does not show the picker but show the opacity effect and sometimes it shows the picker but does not show the opacity effect. 

**Expected behavior**<br />
I would like to show to user the picker but also the opacity effect for better user experience

** Code sample**<br />

render() {
  return this.wrapInOpacity(this.picker())
}
wrapInOpacity = children => {
  return (
    <TouchableOpacity
      onPress={this.openPicker}
      style={styles.userSelectContainer}
    >
      {children}
    </TouchableOpacity>
  )
}

picker() {
  const { teamMembersList, pickerWidth } = this.props
  const { selectedUserId } = this.state
  const user = teamMembersList.find(u => u && u.value === selectedUserId)
  return (
    <View style={styles.userSelectInput}>
      <RNPickerSelect
        doneText={i18n.t('Done')}
        // removing the placeholder - it's necessary to have empty object!
        placeholder={{}}
        ref={ref => {
          this.rnPickerRef = ref
        }}
        textInputProps={{
          numberOfLines: 1,
          ellipsizeMode: 'tail'
        }}
        onValueChange={this.onValueChange}
        items={teamMembersList}
        value={selectedUserId}
        useNativeAndroidPickerStyle={false}
        style={{
          headlessAndroidPicker: {
            width: scale(pickerWidth)
          },
          inputAndroid: styles.inlineText,
          inputIOS: styles.inlineText
        }}
      />
  </View>
 )
}

**Comment by lfkwtz** [comment]
the component is already a touchable element. i'm not certain what side effects may occur if you choose to wrap it in additional elements - but it's not something i can help you debug.

**Comment by lfkwtz** [comment]
the component is already a touchable element. i'm not certain what side effects may occur if you choose to wrap it in additional elements - stackoverflow would be a better place for debugging this.
