### ISSUE TITLE
Cannot call this.inputRefs.picker.togglePicker() on Android

### ISSUE THREAD

**Issue by sethnkruse** [lawnstarter/react-native-picker-select#22]
I am using your example on an Android and noticed that I cannot call 'this.inputRefs.picker.togglePicker() ' to the reference created in the example.  This works perfectly for IOS but not Android.

**Comment by lfkwtz** [comment]
I'll take a look

**Comment by vza100** [comment]
I have the same issue, cannot open modal when calling 'this.inputRefs.picker.togglePicker() ' .

**Comment by kholiavko-roman** [comment]
I think this is related https://github.com/facebook/react-native/issues/7817

**Comment by lfkwtz** [comment]
@kholiavko-roman is correct. would need a workaround to trigger the picker programmatically on android.

**Comment by lfkwtz** [comment]
closing this issue as it will live in the feature request board

**Comment by mazenchami** [comment]
@lfkwtz do we have an update on this?

**Comment by lfkwtz** [comment]
No. Same issue exists - using the native Android `Picker` element exposes no API to programmatically trigger the Picker. There may be a hacky way to simulate it - but I haven't thought too much about it.

**Comment by sinodko** [comment]
any update on this? It would be great to make it work!

**Comment by lfkwtz** [comment]
I haven't looked into it recently. Open to prs.

**Comment by Rodrigo816** [comment]
any updates on this?

**Comment by vannestepieter** [comment]
Still not working... maybe the hacky way?

**Comment by aprilmintacpineda** [comment]
This is not related to react-native. I can call the `ref.current.togglePicker()` and I can see the `showPicker` state changing from `true` to `false` and vice-versa. This is because the `togglePicker` has nothing to do with android, it only changes the `showPicker` but that's not really being used by android as seen here https://github.com/lawnstarter/react-native-picker-select/blob/71ba0b5781f9f3885261e9bce400aefb44c1ac71/src/index.js#L511 so it doesn't matter if you call that, so how do we manually toggle the picker on android?

**Comment by xXFracXx** [comment]
Any update on this?

**Comment by bryanboyko** [comment]
Same request here - any updates?

**Comment by timeturnback** [comment]
any updates ?

**Comment by lfkwtz** [comment]
Open to PRs. I won't be looking into this anytime soon.

**Comment by mpasalic** [comment]
https://github.com/react-native-picker/picker/pull/258 has a fix to expose an focus / blur API. If the dependency is upgraded to 1.16.7 it would be pretty easy to access the pickerRef through the customPickerProps prop. See issue here:
https://github.com/lawnstarter/react-native-picker-select/issues/456

**Comment by tara-singh-danu** [comment]
Any updates

**Comment by Dahan-Schuster** [comment]
Any updates?

**Comment by shoki61** [comment]
[https://github.com/lawnstarter/react-native-picker-select/issues/424#issuecomment-851065179](https://github.com/lawnstarter/react-native-picker-select/issues/424#issuecomment-851065179)
this solution worked
