### ISSUE TITLE
Extend with datepicker support

### ISSUE THREAD

**Issue by sbauch** [lawnstarter/react-native-picker-select#221]
**Is your feature request related to a problem? Please describe.**
This is a *feature request* to be able to use a datepicker in a similar manner.

I've been trying to set up https://github.com/wix/react-native-keyboard-input to use an ios native datepicker as a "keyboard" for an input. Really struggling with getting that to work. Found this project, which solves general pickers wonderfully, but would love to also find a better solution for a datepicker.

**Describe the solution you'd like**
I may be willing to try to implement this, but I'm pretty new to RN. Seems like the approach is to sort of fake a keyboard on ios with a `<Modal/>`. Seems like it wouldn't be super challenging to render a datepicker instead of a `Picker`, but if I could chat with someone on the LS team about how to approach this, gotchas, etc it would be super helpful! 

I think this may work better as a separate component?

**Describe alternatives you've considered**
Been messing with `react-native-keyboard-input`, and have also just dumped a datepicker at the bottom of a scrollview when a date field gets focus.

**Additional context**
I'm just trying to build some forms where inputs are usually text, but can support other pickers. 

![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 12 19](https://user-images.githubusercontent.com/923033/64021759-ad565480-cb02-11e9-98f7-bdcda25717f4.png)

I'd also be curious to know how LS is solving this issue in your app - I'd imagine folks need to pick a date / time for lawn services, so if you have other suggestions I'm cetainly interested.

**Comment by lfkwtz** [comment]
Thanks for the detailed feature request. I'll think about this a bit more / leave the issue open a bit for discussion.

Since you asked, [this post](https://medium.com/lawnstarter-engineering/react-native-one-year-later-what-weve-learned-c23dc13cec80) talks a bit about how we've handled dates.

**Comment by lfkwtz** [comment]
Thanks for the detailed feature request. I'll think about this a little / leave the issue open for discussion for a bit.

Since you asked, [this post](https://medium.com/lawnstarter-engineering/react-native-one-year-later-what-weve-learned-c23dc13cec80) talks about how we've handled dates.

**Comment by sbauch** [comment]
Oh interesting!! Seems you're maybe just a bit further along on this journey than me - I similarly have felt that using the native elements was best, but you make a compelling case in the post. Will noodle on it myself!

**Comment by lfkwtz** [comment]
will throw this onto the feature request board. certainly out of the core scope of this library - but depending on the implementation it could work.
