### ISSUE TITLE
Custom picker with description to the left and value to the right

### ISSUE THREAD

**Issue by fgagneten** [lawnstarter/react-native-picker-select#222]
I've made a custom selector so I could set a description to the left and display the picker to the right. I couldn't. I don't think is a problem of the style, is just the picker doesn't allowed it.
This is my custom selector I've implemented:

```

import React from "react";
import { CommonStyle } from "../styles/Common";
import { Picker } from "react-native";
import { View, Text, StyleSheet, Platform } from "react-native";
import RNPickerSelect, { defaultStyles } from "react-native-picker-select";
import Ionicons from "react-native-vector-icons/Ionicons";
import Colors from "../styles/Colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row"
  },
  description: {
    flex: 0.6
  },
  picker: {
    flex: 0.4
  }
});

export const Select = overrideProps => {
  const props = {
    label: "",
    ...overrideProps
  };

  return (
    <View style={styles.container}>
      <Text style={styles.description}>{props.label}</Text>
      <RNPickerSelect
        placeholder={{}}
        style={[
          styles.picker,
          {
            iconContainer: {
              right: 15,
              top: Platform.OS == "ios" ? 0 : 13
            }
          }
        ]}
        Icon={() => {
          return <Ionicons family={"Ionicons"} name={"md-arrow-dropdown"} color={Colors.grisOscuro} size={20} />;
        }}
        {...props}
      />
    </View>
  );
};


```

This is how it looks:
![image](https://user-images.githubusercontent.com/14353978/64066076-21205c00-cbec-11e9-9c17-5c982d2ffca1.png)
![image](https://user-images.githubusercontent.com/14353978/64066097-6e043280-cbec-11e9-849b-811a45d33c13.png)

Moreover, If I tap on the arrow dropdown, nothing happens, it is like click listener doesn't work anymore. 

Any suggestion?

Thanks

**Comment by Andrea-Arguello** [comment]
Have you tried clicking on another part of the select component? I've had issues with the icon not being clickable, but anywhere else inside the RNPicker does detect the onPress action

**Comment by fgagneten** [comment]
Yes. I clicked everywhere and nothing happens.

**Comment by fgagneten** [comment]
Any solution for that?

**Comment by Andrea-Arguello** [comment]
I've noticed you don't have neither the value nor the onValueChange attributes passed down to the picker. Take a look at the sample code in the snack project https://snack.expo.io/@lfkwtz/react-native-picker-select

**Comment by lfkwtz** [comment]
Please edit and/or reopen following the bug report template. Code samples need to be fully reproducible

**Comment by fgagneten** [comment]
I've just added how I use the custom Select Picket. Please, try it out and you will see that there is no way to set the value to the right and the text to the left.

**Comment by lfkwtz** [comment]
Can you reproduce it on snack.expo.io for me?

Otherwise, I need a full code sample (for ex - yours isn't including props used) so I can just copy-paste and see the problem immediately without having to take guesses on reproduction.

**Comment by citizen-dror** [comment]
my solution:

```
import React, { useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import RNPickerSelect from 'react-native-picker-select';

const MyPickerSelect = ({ data, title, value, setValue, width }) => {
   const pickerWidth = (width) ? width : 200;
   return (
      <View style={styles.lineContainer}>
         {(title)?<Text style={styles.label}>{title}</Text>:null}
         <View style={{ width: pickerWidth }}>
            <RNPickerSelect
               value={value}
               onValueChange={(val) => setValue(val)}
               items={data}
            />
         </View>
      </View>
   );
}

export default MyPickerSelect

const styles = StyleSheet.create({
   label: {
      marginLeft: 10,
      marginRight: 15,
      fontSize: 18,
      width: 130,
   },
   lineContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      paddingHorizontal: 15,
      paddingTop: 6,
   },
})
```
result :

![image](https://user-images.githubusercontent.com/342644/101780470-41350f80-3aff-11eb-84f1-adf5ef122d47.png)
