### ISSUE TITLE
Why can't handle onOpen in Android??

### ISSUE THREAD

**Issue by JongGyuChoi** [lawnstarter/react-native-picker-select#223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lfkwtz** [comment]
no API is available to programmatically trigger the picker on android - so we have no way to determine when it has been opened. this is related to #22. could potentially detect certain changes on the screen to determine if it has been opened.
