### ISSUE TITLE
Unable to remove the icon

### ISSUE THREAD

**Issue by aidshon** [lawnstarter/react-native-picker-select#228]
**Describe the bug**<br />
I removed the Icon prop from the Component but it still renders. I can't even change its color or add any other styling.

**To Reproduce**<br />
1. install the library
2. insert the code below
3. see the icon still displaying

**Expected behavior**<br />
I expected the icon not to display anymore.

**Screenshots**<br />
<img width="126" alt="Screen Shot 2019-09-05 at 3 47 29 PM" src="https://user-images.githubusercontent.com/39763991/64331536-c83e3280-cff4-11e9-8c83-a4bc2df57efb.png">

**Additional details**<br />
-   Device: iPhoneX
-   OS: iOS 12.0
-   react-native-picker-select version: ^5.2.5
-   react-native version: 0.60.3
-   react version: 16.8.6

**Reproduction and/or code sample**<br />
`      <RNPickerSelect
        placeholder={{}}
        items={rangeModeOptions}
        onValueChange={rangeMode => {
          this.setState({
            rangeMode
          });
        }}
        style={{
          inputAndroid: {
            backgroundColor: 'transparent',
            color: 'white',
            fontSize: 18,
            lineHeight: 21,
          },
          inputIOS: {
            color: 'white',
            fontSize: 18,
            lineHeight: 21,
            alignItems: 'center'
          },
        }}
        value={this.state.rangeMode}
        useNativeAndroidPickerStyle={false}
        textInputProps={{ underlineColorAndroid: 'cyan' }}
        onDonePress={() => this.handleSelectedOption()}
      />`

**Comment by lfkwtz** [comment]
Old version
