### ISSUE TITLE
textInputProps not working as expected

### ISSUE THREAD

**Issue by Andrea-Arguello** [lawnstarter/react-native-picker-select#231]
**Describe the bug**<br />
I want the picker to ellipsize text that is too long. 

**To Reproduce**<br />
I am using the RNPickerSelect inside of a styled component. It also uses an Icon, which after reading some of the other issues, could be a source of the problem.

**Expected behavior**<br />
After adding the  ``` textInputProps  = {{numberOfLines: 1, ellipsizeMode: 'tail'}} ``` I expected the issue to go away. However, it doesn't work as expected, but it does not lead to any further errors.

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/31134106/64549537-249f9b80-d2ee-11e9-96c8-bddc2e80b226.png)

**Additional details**<br />
- Android emulator
- If I set the useNativeAndroidPicker to true, it does ellipsize. However, the icon does not respond to being clicked.
- Adding numberOfLines or ellipsizeMode to the styleSheet throws error.

**Reproduction and/or code sample**<br />
```
<RNPickerSelect
          placeholder={{
            label: `${i18n.t('selectABoard')}`,
            value: null,
          }}
          items={items}
          onValueChange={
            value => {
              if (value != null && value !== selected) {
                if (boards.find(board => board.name === value.name)) {
                  onBoardSelected(value);
                } else {
                  onCommitteeSelected(value);
                }
              }
            }
          }
          value={selected}
          style={stylesPicker}
          Icon={() => (
            <IconContainer>
              <Entypo
                name="chevron-down"
                color={colors.PRIMARY_BLUE}
                size={20}
              />
            </IconContainer>
          )}
          useNativeAndroidPickerStyle={false}
          textInputProps={{numberOfLines: 1}}
        />

const stylesPicker = StyleSheet.create({
  placeholder: {
    color: colors.PRIMARY_BLUE,
  },
  inputIOS: {
    color: colors.PRIMARY_BLUE,
    height: NAVBAR_HEIGHT,
    paddingLeft: 16,
    paddingRight: 16,
  },
  inputAndroid: {
    color: colors.PRIMARY_BLUE,
    height: NAVBAR_HEIGHT,
    paddingLeft: 16,
    paddingRight: 16,
  },
  iconContainer: {
    alignItems: 'center',
    height: NAVBAR_HEIGHT,
    justifyContent: 'center',
    paddingRight: 16,
  }
});
```

**Comment by lfkwtz** [comment]
`ellipsizeMode ` is not a supported prop

https://facebook.github.io/react-native/docs/textinput.html

**Comment by Andrea-Arguello** [comment]
I read a comment that suggested placing numberOfLines inside of the textInputProps. If this is not the solution, what could I do?

**Comment by lfkwtz** [comment]
add more padding to the right of the input

**Comment by Andrea-Arguello** [comment]
That dod not fix the issue. I attach an image in a different emulator. The text to be displayed in this case is "Nahual Prueba NGO - Finance Committee"
![image](https://user-images.githubusercontent.com/31134106/64564229-47da4300-d30e-11e9-849a-4643a4f76a77.png)

**Comment by lfkwtz** [comment]
you'll need to reproduce the issue on snack.expo.io for me to help - i have no idea what other styling you have on that screen that could be affecting the component.

**Comment by Andrea-Arguello** [comment]
I have included the styles used in the code above. The picker select is inside a component called BoardNameContainer, with the following styling.
```
const BoardNameContainer = styled.View`
  flex: 1;
  height: ${NAVBAR_HEIGHT};
`;
```

**Comment by lfkwtz** [comment]
https://github.com/facebook/react-native/issues/14845

**Comment by Ramaraju1992** [comment]
@Andrea-Arguello, @lfkwtz  i am also facing the same issue.
but i found some TextInput prop that can show the selected text from starting.

`textInputProps={{
     selection: {
           start: 0
      }
}}
`

but unfortunately for `ellipsizeMode: 'tail'` Repository Team has to help.
