### ISSUE TITLE
ANDROID -selected value longer than selector width aligns text to the right

### ISSUE THREAD

**Issue by pani7** [lawnstarter/react-native-picker-select#232]
**Describe the bug**<br />
When the text of selected item is too long for selector width on android it positions text to the end. This is happening because under renderTextInputOrChildren() you are using textInput for value text and on android position is like we wrote long text in input.

**To Reproduce**<br />
Try to write long text in android selector and you will see wrong positioning

**Expected behavior**<br />
Even when we have long items in picker, selected value should show text from start until the width of selector with ellipsize='tail' same like on IOS.

**Screenshots**<br />

![image](https://user-images.githubusercontent.com/20878788/65506863-e4831000-decc-11e9-9b4d-e4b84fec0305.png)

**Additional details**<br />
-   react-native-picker-select version:6.3.3
-   react-native version:0.59.4
-   react version: 16.9

**Reproduction and/or code sample**<br />
` <View style={[dropdownContainer, style && style.width && { width: style.width }]}>
          <PickerSelect
            ref={ref => {
              this.pickerSelect = ref;
            }}
            items={dropdownList}
            onValueChange={newValue => this.listItemSelected(newValue)}
            style={{ ...pickerSelectStyles }}
            useNativeAndroidPickerStyle={false}
            value={value ? value : null}
            hideDoneBar={false}
            placeholder={placeholder ? placeholder : {}}
            doneText={I18n.t('UI.confirm')}
            Icon={() => {
              return <Icon name="chevron-down" size={FONTS.sizes.f18} color={COLORS.primary.light} style={iconStyle} />;
            }}
          />
        </View>`

**Comment by lfkwtz** [comment]
https://github.com/facebook/react-native/issues/14845

**Comment by Shahnewaj** [comment]
add the followings 
`textInputProps={{ selection: { start: 0 } }}`
