### ISSUE TITLE
How to Style the Placeholder Text

### ISSUE THREAD

**Issue by zdavodi6990** [lawnstarter/react-native-picker-select#233]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lfkwtz** [comment]
View the sample, if that doesn’t help - use stackoverflow

**Comment by zdavodi6990** [comment]
thanks for your attention .i see sample and i read a code but it is not any
props to set style,
