### ISSUE TITLE
[Android] Unable to change dropdown icon color on Android.

### ISSUE THREAD

**Issue by gourav-singhal** [lawnstarter/react-native-picker-select#235]
On The Android app unable to change dropdown icon color.

Can you suggest how I can do this?

Expected behavior

Dropdown color must be changed as in iOS using 'borderTopColor' property

Smartphone (please complete the following information):

Device: All of them
OS: Android
react-native-picker-select version: 4.4.0
react-native version: 0.59.5
react version: 16.8.6

**Comment by lfkwtz** [comment]
Old version
