### ISSUE TITLE
How to display the dropdown value by default

### ISSUE THREAD

**Issue by harikanammi** [lawnstarter/react-native-picker-select#238]
**Describe the bug**<br />
I am running sample application. I am using this module it is working fine. My question is how to display the value by default without selection using dropdown.

**To Reproduce**<br />
Steps to reproduce the behaviour:
I placed the code value={"Picked"} by default. But it is not displaying in dropdown section.

**Expected behaviour**<br />
I want to display the value by default in without selection using dropdown.

**Screenshots**<br />
![Screen Shot 2019-10-12 at 4 52 17 PM](https://user-images.githubusercontent.com/31063894/66700661-b301a580-ed10-11e9-9270-45479ec47aed.png)

**Additional details**<br />
-   Device: All devices
-   OS: 10.13.6 (Mac)
-   react-native-picker-select version: 6.3.3
-   react-native version: 0.60.5
-   react version: 16.8.6

**Reproduction and/or code sample**<br />

```
  <RNPickerSelect
                onValueChange={value => this.onValueChange(value)}
                dropdownValues={dropdownValues}
                value={"Picked"}
              />
```

**Comment by lfkwtz** [comment]
dropdownValues isn’t a prop

Look through the sample expo app and documentation

**Comment by harikanammi** [comment]
hi @lfkwtz, thank you for your reply. I am using child component for Picker **dropdownValues** contains in parent class. **value** is worked for me. My mistake is child to parent passing values incorrectly. Now i am using callback function it's working fine.
