### ISSUE TITLE
Prop to set limit of label length to display with "..."

### ISSUE THREAD

**Issue by suraneti** [lawnstarter/react-native-picker-select#244]
**Is your feature request related to a problem? Please describe.**
Yes, I want to set a label length limit. for example, set to 8 after limit should display "..."

**Describe the solution you'd like**
Prop to set a label limit.

**Comment by lfkwtz** [comment]
https://github.com/facebook/react-native/issues/14845
https://github.com/lawnstarter/react-native-picker-select/pull/234
