### ISSUE TITLE
Support for iOS Dark Mode

### ISSUE THREAD

**Issue by alexborton** [lawnstarter/react-native-picker-select#245]
Currently, the default styling of the Modal itself is Light in colour. with iOS 13, there is a new dark mode that turns all native elements darker (Alerts, other modal popups and theming). 

If a device is able to detect Dark Mode, we should allow the `select` modal to be switched to a default "dark" style to fit with other elements that are likely to be present on the screen.

Looks like you could add some manual styling to the modal (which works, other than the Text style)

```
            modalViewMiddle: {
              backgroundColor: '#000000',
            },
            modalViewBottom: {
              backgroundColor: '#000000',
              color: 'pink', // this does not effect the select text which remains black
            }
```

Note: Dark mode can be pulled using some other modules and is available in Expo also (for v35).

**Comment by lfkwtz** [comment]
moving to feature request board

**Comment by sebinq** [comment]
any news on this?

**Comment by lfkwtz** [comment]
not on my priority list, but open to prs

**Comment by emilmammadov** [comment]
Any news? Any workarounds for now? It is very urgent.

**Comment by maitham** [comment]
Turns out the color prop is on on items. When you create items {label: "", value: "", color:""}

**Comment by alexandrughinea** [comment]
> Turns out the color prop is on on items. When you create items {label: "", value: "", color:""}

You my friend are Amazing. It works as expected. 
Thank you!

**Comment by octagonalsquare** [comment]
> moving to feature request board

It has been over a year since this was started and promptly ignored. Could you at least allow the merge so we can get one last good update before you quit on this project?

**Comment by sophie-li** [comment]
@lfkwtz there is an open and approved PR for this https://github.com/lawnstarter/react-native-picker-select/pull/463. can we please merge it?
