### ISSUE TITLE
Done button props not available (AllowFontScaling)

### ISSUE THREAD

**Issue by cesar-bookee** [lawnstarter/react-native-picker-select#247]
**Describe the bug**<br />
When the accesibility text is set to a larger text size on ios the Done label is too big for the done section,

**To Reproduce**<br />

1.  Go to the device accesibility settings
2.  Change the font size to the largest possible
3.  Go to your app and open the picker
4.  See error

**Expected behavior**<br />
Be able to pass down the AllowFontScaling to the Done text so it doesn't resize with the rest of the text

**Screenshots**<br />
![Issue](https://user-images.githubusercontent.com/42519553/67762959-7935dc00-fa3e-11e9-99d6-6e2f28bb60cb.png)

**Additional details**<br />
-   Device: iPhone X
-   OS: iOS 13
-   react-native-picker-select version: 6.3.0
-   react-native version: 0.60.4
-   react version: 16.10.1

**Comment by lfkwtz** [comment]
`style.done`

https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L351

**Comment by lfkwtz** [comment]
i'm thinking we can just set that as a default

**Comment by lfkwtz** [comment]
handled in #247

**Comment by lfkwtz** [comment]
fixed in 6.3.4

**Comment by Praxey** [comment]
Is there any way to turn the fontscaling off for the placeholder text? I tried this: textInputProps={{allowFontScaling:false}}, but no luck.
