### ISSUE TITLE
rtl isnt supported

### ISSUE THREAD

**Issue by shachardevops** [lawnstarter/react-native-picker-select#249]
IOS modal doesn't look very good with RTL

**Comment by shachardevops** [comment]
![Screen Shot 2019-11-03 at 16 15 05](https://user-images.githubusercontent.com/36663539/68086469-2ea8cb00-fe55-11e9-8e42-ce6efb761714.png)

**Comment by lfkwtz** [comment]
thanks for the heads up. interested in submitting a PR for this?

**Comment by shachardevops** [comment]
sorry but i dont have time for this.
i just used 
chevronUp: { opacity: 0 },
    chevronDown: { opacity: 0 },

**Comment by lfkwtz** [comment]
can you post a screenshot of what the 'select' menu looks like when you click the dropdown on [this](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) page?

**Comment by lfkwtz** [comment]
![IMG_3310](https://user-images.githubusercontent.com/1746853/69290875-eb758880-0bc6-11ea-891d-10fb0dc0d053.PNG)

**Comment by lfkwtz** [comment]
moving to feature request board
