### ISSUE TITLE
Android: Not working with Parent View {flexDirection:'row'}

### ISSUE THREAD

**Issue by rohitkum28** [lawnstarter/react-native-picker-select#250]
### YOU MUST FILL OUT EVERY SECTION. INCOMPLETE BUG REPORTS WILL BE CLOSED.

**Describe the bug**<br />
I want to use <RNPickerSelect./> with <TextInput/> in a single row. So, when I make the Parent <View> flexDirection: row, I see only the arrow and no text. Even if I remove the <TextInput/> I don't see any text.

**To Reproduce**<br />

Below is the code to reproduce this on Android

    import React, { Component } from 'react';
    import {
        StyleSheet,
       View,
    } from 'react-native';
    import RNPickerSelect from 'react-native-picker-select';

    type Props = {}

    const countryCode = [
    {
    label: '+91',
    value: '+91',
    },
    {
     label: '+1',
     value: '+1',
    }
    ];

    export default class PickerTest extends Component<Props> {
  
        constructor() {
	  super()
	  this.state = {
		  phoneNumber: "",
		  countryCode: ""
	   }
       }
 
    render() {
    return (
        <View style={{flexDirection:'row'}}>
            <View paddingVertical={5}>
            {/* and hiding the InputAccessoryView on iOS */}
            <RNPickerSelect
            placeholder={{}}
            items={countryCode}
            style={pickerSelectStyles}
            onValueChange={value => {
              this.setState({
                countryCode: value,
              });
            }}
            InputAccessoryView={() => null}
            style={pickerSelectStyles}
            value={this.state.countryCode}
            />
            </View>
        </View>
     );
    }
    }

    const pickerSelectStyles = StyleSheet.create({
    inputIOS: {
    fontSize: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 4,
    color: 'black',
    paddingRight: 30, // to ensure the text is never behind the icon
    },
    inputAndroid: {
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 0.5,
    borderColor: 'purple',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30, // to ensure the text is never behind the icon
    },
    });

**Expected behavior**<br />
I want the text to be seen when I change flexDirection to 'row'

**Screenshots**<br />

![image](https://user-images.githubusercontent.com/11205673/68124974-9125c800-ff36-11e9-9499-31a0e9427385.png)

**Additional details**<br />
-   Device: Android Simulator
-   OS: Android Pie
-   react-native-picker-select version: 6.3.3
-   react-native version: 0.61.2
-   react version: 16.9.0

**Reproduction and/or code sample**<br />
https://snack.expo.io/H1vBssTqS

**Comment by lfkwtz** [comment]
this is an upstream issue: https://snack.expo.io/HkygCqhsr

options:
1. `useNativeAndroidPickerStyle` prop
2. set `width` and `height` with `inputAndroid` style prop

**Comment by SufianBabri** [comment]
I solved it by wrapping the `RNPickerSelect` inside a View like this:
```
<View style={{ flex: 1 }}>
	<RNPickerSelect
		items={items}
		onValueChange={onValueChange} />

```
