### ISSUE TITLE
Only icon clickable

### ISSUE THREAD

**Issue by MebDevelop** [lawnstarter/react-native-picker-select#253]
**Is your feature request related to a problem? Please describe.**

I have so many pickers in the scroll view and when I scroll down sometimes picker shows modal.
I want to not show modal.

**Describe the solution you'd like**

So, I want to show modal when clicking the icon, not the content.

**Describe alternatives you've considered**

I checked the module but I am not sure how can I solve this. please suggest me a solution.

**Additional context**

![signal-attachment-2019-11-25-013117](https://user-images.githubusercontent.com/46660632/69686742-806bfc00-1075-11ea-9aaf-29a75c0d7be3.jpeg)

As you can see in this picture there are so many pickers so when I scrolling down sometimes picker open modal. I want to dismiss it.

Please give me a solution.

**Comment by lfkwtz** [comment]
you can currently handle this by using headless mode. otherwise, the base pickers are fully wrapped in touchables. moving to feature request board.
