### ISSUE TITLE
placeholder color prop not working

### ISSUE THREAD

**Issue by suraneti** [lawnstarter/react-native-picker-select#259]
**Describe the bug**<br />
When I set a color object in placeholder prop not work but set though placeholderTextColor prop worked perfect (it's deprecated).

**To Reproduce**<br />

1.  Set a color object in placeholder prop.

**Expected behavior**<br />
Placeholder text color changed.

**Additional details**<br />
-   Device: [iPhone8]
-   OS: [iOS13.1]
-   react-native-picker-select version: [6.3.3]
-   react-native version: [0.59.10]
-   react version: [16.8.3]

**Reproduction and/or code sample**<br />
```js
 <RNPickerSelect
placeholderTextColor = "red" // worked
placeholder = {
    {
        label: 'EN',
        value: 'EN',
        color: 'red' // not worked
    }
}
items = {
    [{
        label: 'TH',
        value: 'TH'
    }]
}
onValueChange = {
    (value) => {
        if (value) {
            strings.setLanguage(value)
            this.setState({})
        }
    }
}
style = {
    pickerSelectStyles
}
InputAccessoryView = {
    this.inputAccessoryViewSendAsset
}
ref = {
    (el) => {
        this.inputRefs = el
    }
}
/>
```

**Comment by lfkwtz** [comment]
`style` prop

**Comment by suraneti** [comment]
@lfkwtz thanks for responding, I still facing this problem.



I have set color: 'red' though style prop, default value still lightgray color as below screenshot.

<img width="339" alt="Screen Shot 2562-12-10 at 12 38 18" src="https://user-images.githubusercontent.com/26770227/70498803-2c1f4c80-1b4a-11ea-9d3b-2643384e00aa.png">

but it's effect with the second value.

<img width="337" alt="Screen Shot 2562-12-10 at 12 38 28" src="https://user-images.githubusercontent.com/26770227/70498939-91733d80-1b4a-11ea-86f7-b15fd386c678.png">

Solution for me is set though `placeholderTextColor` prop but it's deprecated.

**Comment by lfkwtz** [comment]
`style.placholder.color` will do the exact same thing as `placeholderTextColor`

**Comment by kramaresh1** [comment]
did not understand could u please give an example of code where to use
