### ISSUE TITLE
Multi Select

### ISSUE THREAD

**Issue by dstvishnu** [lawnstarter/react-native-picker-select#260]
**Is your feature request related to a problem? Please describe.**
If this library have the multi select option it would be useful and there is not need for writing the own component or no need to look for other libraries.

**Describe the solution you'd like**
Provide a Multi Select functionality for a picker using which the user can select the multiple items

**Describe alternatives you've considered**
Searched for alternative options.

**Comment by lfkwtz** [comment]
#35
