### ISSUE TITLE
Unable to tap button when picker is open

### ISSUE THREAD

**Issue by dquessenberry** [lawnstarter/react-native-picker-select#261]
**Describe the bug**<br />
When the picker drawer is open I am unable to tap a button on the screen. All taps outside of the picker drawer only close the drawer and do not allow for tap event to be passed on. For example, I have a screen with a RNPickerSelect input field and a save button. When I tap the input field and the drawer opens, I select a value, but when I tap the save button on the screen it only closes the drawer and I have to tap the save button a second time.

**To Reproduce**<br />

1. Create a simple screen with a RNPickerSelect component with some data and a button component (I'm using a react-native-element's Button component, but any Touchable component will work).
2. Add a simple console.log to the Button component's onPress prop to verify when it is pressed.
2. Tap the RNPickerSelect field to open the picker drawer.
3. Select any item
4. Tap the Button component and notice that the picker drawer closes but the Button component's onPress function is not called

**Expected behavior**<br />
I expect to be able to press other Touchable components when the picker drawer is open.

**Screenshots**<br />
![rnpickerselect](https://user-images.githubusercontent.com/10273674/70754721-c919eb00-1cec-11ea-9c12-8bb1d4401a20.gif)

**Additional details**<br />
-   Device: iOS Simulator (iPhone 11) - most likely occurs on all devices
-   OS: iOS13.3
-   react-native-picker-select version: 6.3.3
-   react-native version: 0.61.5
-   react version: 16.9.0

**Comment by lfkwtz** [comment]
Going to move this to feature request board. Currently this isn't possible due to the way this library is built (within a modal) - but I'd like to see this fixed if possible - will need to put some thought into it.
