### ISSUE TITLE
Display value instead of Label

### ISSUE THREAD

**Issue by Billmike** [lawnstarter/react-native-picker-select#263]
Is it possible to display the value rather than label for a selected option using this library? For instance, if I have an array with the following shape:
```
[
  {
    label: 'United State Of America',
    value: 'USD'
  }
]
```
Passing this to the items prop, the displayed label would be United States of America and its corresponding value would be USD. On selecting the United States Of America option, rather than display United States of America, can one display USD instead? Gone through the docs and expo snack, but nothing I've found so far gives me the impression that it's possible.

**Comment by lfkwtz** [comment]
to clarify, you want it to display 'United States of America' in the 'list', but 'USD' in the input - correct?

**Comment by Billmike** [comment]
Correct

**Comment by lfkwtz** [comment]
1. you could currently handle this yourself via headless mode
2. you could possibly try a hacky solution on ios like this: https://snack.expo.io/Hkl7qBIAB
3. adding to feature request board - would be simple enough for the component to handle via a prop
