### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by andordavoti** [lawnstarter/react-native-picker-select#268]
I can style the component so it's dark, but when I open the picker select menu that is using a light theme. Being able to pass a prop called theme to change the look of the picker would be nice.
![IMG_ADB4EAB5761B-1](https://user-images.githubusercontent.com/24613178/71534960-a39efb00-2902-11ea-8bbf-d60546ec3ba0.jpeg)

**Comment by lfkwtz** [comment]
Exists on feature request board
