### ISSUE TITLE
crash when change ITEMS dynamically

### ISSUE THREAD

**Issue by riazXrazor** [lawnstarter/react-native-picker-select#270]
the items are being updated from an api call from server to a redux store, i cant seems to debug it properly,
ATTACHED A VIDEO
[20200118-100529-720x1280.zip](https://github.com/lawnstarter/react-native-picker-select/files/4080125/20200118-100529-720x1280.zip)

any body help plz

**Comment by lfkwtz** [comment]
this looks more like troubleshooting implementation than a bug report - this would be more appropriate for stackoverflow

**Comment by riazXrazor** [comment]
initially me too thought so, but y crash the app in dev mode too, no error nothing, if i change the implementation a little bit it works, but i just wanted to inform abt the crash

**Comment by Alokalearnyst** [comment]
What implementation did you change can you let me know, even I am facing the same issue.
