### ISSUE TITLE
add an action to open the picker

### ISSUE THREAD

**Issue by hmazer** [lawnstarter/react-native-picker-select#272]
**Describe the solution you'd like**
In order to make my app more dynamic, I often focus fields automatically when the user hits a return key or open a screen.
I'd like to be able to add a ref to the RNPickerSelect and call ref.show() or something like that, so the user doesn't have to tap to open.

**Additional context**
I'm currently using .onUpArrow() but I don't think this function was added for that purpose.

**Comment by lfkwtz** [comment]
#22
