### ISSUE TITLE
Programmatically open the picker

### ISSUE THREAD

**Issue by countcain** [lawnstarter/react-native-picker-select#275]
First of all. Thanks for your awesome lib.

**Is your feature request related to a problem? Please describe.**
I use this Picker on the onboarding screen. Users can go through all inputs one-by-one by clicking the next key on the keyboard. When I have this Picker between other inputs, it breaks the inputs navigation flow.

**Describe the solution you'd like**
It would be nice if this Picker expose an API to let us programmatically open up the options.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lfkwtz** [comment]
#22
