### ISSUE TITLE
When updating items, selectedItem is compared to old items

### ISSUE THREAD

**Issue by piet-v** [lawnstarter/react-native-picker-select#28]
Hi, I noticed a bug when using items with translated labels.

When changing the language the item labels are changed which correctly triggers an update of the item state in your component.
The selectedItem label will not be updated correctly due it coming from the old items.

I guess getDerivedStateFromProps should use the updated items instead of the old items to extrapolate the selectedItem from.

**Comment by lfkwtz** [comment]
Can you put together an example of the issue on snack.expo.io?

**Comment by piet-v** [comment]
Tried to keep it as simple as possible:
https://snack.expo.io/@pleasebegentle_/picker-select-bug

**Comment by lfkwtz** [comment]
Super helpful, thanks. Will take a look soon.
