### ISSUE TITLE
No feedback given on iOS when tapping picker

### ISSUE THREAD

**Issue by amankarora** [lawnstarter/react-native-picker-select#282]
When tapping the picker, no feedback is provided to user to indicate that it has been touched. This sometimes means the user does not know where exactly to tap in order to bring up the menu, or requires a few taps before the menu appears.

It would be nice to have some sort of feedback when touching the picker or the radius of it were bigger. 

React Native has TouchableOpacity which would be good to integrate but that does not seem to work.

**Comment by lfkwtz** [comment]
added as a prop in 6.6.0
