### ISSUE TITLE
Error while updating property 'items' of a view managed by: AndroidDialogPicker

### ISSUE THREAD

**Issue by tomthornton** [lawnstarter/react-native-picker-select#285]
**Describe the bug**<br />
Getting an error that crashes the app 

Error while updating property 'items' of a view managed by: AndroidDialogPicker

null

label

**To Reproduce**<br />

1. use React Native Picker Select on android?

**Expected behavior**<br />
It works on iOS but not Android

**Comment by aiveneh** [comment]
I'm experiencing this issue too, please what solution did you come up with ?
@lfkwtz

**Comment by lfkwtz** [comment]
I didn’t - this isn’t a complete bug report

**Comment by tannker** [comment]
I had the same error. I was building the list of options dynamically and after debugging realized that on one case one item was missing the 'label' element. This caused the same error. All picker items should always have 'label' and 'value' elements.

**Comment by ReneMoraales** [comment]
I had this problem. My problem was that I was passing a string to the `placeholder` property. In iOS it just throws a warning so I ignored it but it turns out in Android it crashes the app.

**Comment by GleidsonDaniel** [comment]
@tomthornton Probably your items are incomplete or undefined, try to initialize your items with an array, solve the problem, at least here it worked.

Error:
```
<RNPickerSelect
            onValueChange={(value) => console.log(value)}
            items={null || undefined}
        />
```
Works:
```
<RNPickerSelect
            onValueChange={(value) => console.log(value)}
            items={[]}
        />
```

**Comment by tomthornton** [comment]
> I had the same error. My problem was that I was passing a string to the `placeholder` property. In iOS it just throws a warning so I ignored it, but turns out in Android it crashes the app.

You're a lifesaver! That's such a weird error.

**Comment by EltonCarreiro** [comment]
> I had the same error. My problem was that I was passing a string to the `placeholder` property. In iOS it just throws a warning so I ignored it, but turns out in Android it crashes the app.

Thanks a lot for the reply! Saved a lot of time!
