### ISSUE TITLE
Error in expo android.

### ISSUE THREAD

**Issue by duongkhoangiam** [lawnstarter/react-native-picker-select#287]
Android error (IOS nice working)
```
Error while updating property 'items' of a view managed by: AndroidDialogPicker
null
label

```

compoment code
```
<RNPickerSelect
        value={locale}
        placeholder=""
        onValueChange={value => setLocale(value)}
        items={language}
        style={pickerSelectStyles}
      />
```

dependencies

```
"expo": "~36.0.0",
"react": "~16.9.0",


```

**Comment by Matiyeu** [comment]
What did you do to solve it?

**Comment by hwaliashraf** [comment]
facing same issue, solution?

**Comment by anders0l** [comment]
Same for me

Please reopen an issue

**Comment by anders0l** [comment]
Lot's of pull request are still not merged.
So I'll just write description what happens:
Placeholder is not a String, it's object **Item**.
Placeholder must set like this:
```
placeholder={{
 label: 'Your placeholder string',
 value: null
}}
```
Of course you can change a value and set yours.
