### ISSUE TITLE
[WEB] 'ColorPropType' is not exported from 'react-native-web/dist/index'.

### ISSUE THREAD

**Issue by lovetofail** [lawnstarter/react-native-picker-select#290]
Hi. After upgrading to  "react-native-web"  "0.12.2"  there is an error when I try to compile this for web.

```
/node_modules/react-native-picker-select/src/index.js
Attempted import error: 'ColorPropType' is not exported from 'react-native-web/dist/index'.
```
RNW removed this export it seems. https://github.com/necolas/react-native-web/pull/1489

Any chance to fixing this for web? Was working fine on RNW 0.11

**Expected behavior**<br />
Expected to compile for web

**Additional details**<br />
-   Device: Chrome
-   OS: Windows
-   react-native-picker-select version: 6.6.0
-   react-native version: 0.61.4
-   react version: 16.13

**Comment by lfkwtz** [comment]
fixed https://github.com/lawnstarter/react-native-picker-select/pull/304
