### ISSUE TITLE
fontFamily does not work on android

### ISSUE THREAD

**Issue by musmanfaisal** [lawnstarter/react-native-picker-select#292]
Here is my picker object

`<RNPickerSelect
                useNativeAndroidPickerStyle={false}
                style={{
                    inputIOSContainer: styles('p15'),
                    placeholder: { paddingLeft: 10, color: constants.themeColor, fontFamily: 'QuickSand-Bold' },
                    inputIOS: { paddingLeft: 10, color: constants.themeColor, fontFamily: 'QuickSand-Bold' },
                    inputAndroid: { paddingLeft: 10, color: constants.themeColor, fontFamily: 'QuickSand-Bold' }
                }}
                onValueChange={onValueChange}
                items={items}
            />`
It is working fine on ios but not working on android. I have check thoroughly and it looks like this is a bug.
Here is the iOs screen shot

![Simulator Screen Shot - iPhone 11 - 2020-03-23 at 12 52 59](https://user-images.githubusercontent.com/61688410/77293999-41894280-6d05-11ea-911b-5dbb235ca67b.png)

And here is the android screen shot
![Screenshot_1584950074](https://user-images.githubusercontent.com/61688410/77294154-8d3bec00-6d05-11ea-9882-f96b7aef17a0.png)

It can be seen that the fonts are different. And the color change indicates that the styling is being applied. Only the fontFamily is not

**Comment by lfkwtz** [comment]
Use the bug report template
