### ISSUE TITLE
How to show the original placeholder after done is pressed and item is selected

### ISSUE THREAD

**Issue by kharlm** [lawnstarter/react-native-picker-select#296]
I'm trying to show the original place holder after an item is selected not sure how, I even set the displayValue: false in the item array however this did nothing. How do I make the default placeholder show after and item is selected

**Comment by lfkwtz** [comment]
That’s poor ux - but use headless mode.

**Comment by kharlm** [comment]
@lfkwtz what headless mode are you referring to and how do I use it ?

**Comment by lfkwtz** [comment]
read the docs
