### ISSUE TITLE
Deprecated import of Picker from 'react-native'

### ISSUE THREAD

**Issue by mezhik91** [lawnstarter/react-native-picker-select#301]
**Describe the bug**<br />
After migration to RN 0.62 I started to see Warning like on screenshot

**To Reproduce**<br />

1.  Upgrade your app to RN 0.62

**Expected behavior**<br />
No warnings visible

**Screenshots**<br />
<img width="502" alt="Screenshot 2020-04-01 at 14 51 24" src="https://user-images.githubusercontent.com/8568104/78139347-a856dc00-7428-11ea-901e-7a41fd179f5d.png">

**Additional details**<br />
-   Device: [IOS emulator]
-   OS: [13.1]
-   react-native-picker-select version: [e.g. 6.6.0]
-   react-native version: [e.g. 0.62]
-   react version: [e.g. 16.13]

**Reproduction and/or code sample**<br />
Just create app with rn cli and add code from docs into it

**Comment by lfkwtz** [comment]
thank you for clarifying this message is in 0.62 - wasn't aware of that until now 👍

**Comment by lfkwtz** [comment]
going to close out this issue - discussion can live on the pr

**Comment by lfkwtz** [comment]
re-opened for visibility
