### ISSUE TITLE
fontFamily prop passed to inputAndroid doesn't work

### ISSUE THREAD

**Issue by RKuerten** [lawnstarter/react-native-picker-select#302]
**Describe the bug**<br />
fontFamily prop passed to the TextInput style doesn't work on Android (using Expo)

**To Reproduce**<br />

1. Import the fonts you want to use in your app.
2. Use the picker provided by this repository, for example:
```
<RNPickerSelect
   style={pickerStyle}
   onValueChange={(value) => console.log(value)}
   items={[
      { label: 'Football', value: 'football' },
      { label: 'Baseball', value: 'baseball' },
      { label: 'Hockey', value: 'hockey' },
   ]}
/>
```

3.  Create an styleSheet for the inputAndroid style:
``` 
const pickerStyle = StyleSheet.create({
  inputAndroid: {
    color: "#333",
    fontFamily: "FiraSans",
    marginLeft: 7,
    marginBottom: 5,
    paddingRight: 60
  }
});
```

4.  fontFamily prop doesn't apply, but all others do.

**Expected behavior**<br />
TextInput should change the font based on what is passed on the fontFamily prop

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/30464993/78256675-3c7b7e80-74cf-11ea-92ab-4c9f10d7c23c.png)
Top: Picker using the style above
Down: TextInput with the "fontFamily: FiraSans" prop in its style

**Additional details**<br />
-   Device: Redmi 4x
-   OS: Android 7.1.2
-   react-native-picker-select version: 6.6.0
-   react-native version: 0.61 (through Expo SDK 36)
-   react version: 16.9

**Reproduction and/or code sample**<br />
Here's a snack: https://snack.expo.io/@r_kuerten/react-native-picker-select
Local imported font is not recognized by the component, that switchs to one of the backup fonts.

**Comment by RKuerten** [comment]
To be extra clear, using `textInputProps` also doesn't work.

**Comment by lfkwtz** [comment]
**Reproduction and/or code sample**

neither isn't helpful

**Comment by RKuerten** [comment]
I will try to come up with a snack that works, but this is super easy to reproduce in a local environment.

**Comment by RKuerten** [comment]
Updated with a snack @lfkwtz

**Comment by lfkwtz** [comment]
check the docs https://github.com/lawnstarter/react-native-picker-select#android-specific

`style.inputAndroid` requires `useNativeAndroidPickerStyle={false}`

**Comment by RKuerten** [comment]
The docs doesn't help. I'm using expo, so there's no such thing as editing the styles.xml file.

**Comment by lfkwtz** [comment]
no, it isn't

![image](https://user-images.githubusercontent.com/1746853/78265123-a4c76180-74c9-11ea-86ec-d88b8ea6e4ab.png)

**Comment by RKuerten** [comment]
It is. 
Anyway, it doesn't work. Here's what the FiraSans looks like:
https://fonts.google.com/specimen/Fira+Sans

The output is:
![image](https://user-images.githubusercontent.com/30464993/78265879-69359300-74db-11ea-9448-3b3a5ffafc9e.png)

**Comment by lfkwtz** [comment]
alright so you updated the snack to include it.

`style.inputAndroid` just passes props down to TextInput. try again with your non-snack by applying `useNativeAndroidPickerStyle={false}`

**Comment by RKuerten** [comment]
The screenshot was already with using `useNativeAndroidPickerStyle={false}`, otherwise the style would be messed up.

And the snack shows that it doesn't work already. So, how can it be fixed? @lfkwtz

**Comment by lfkwtz** [comment]
can't help you any further. props are directly passed down to the textinput. if something isn't working, it's not due to this library. stackoverflow may be your best bet at this point.
