### ISSUE TITLE
Picker has been extracted from react-native core

### ISSUE THREAD

**Issue by jamieshepherd** [lawnstarter/react-native-picker-select#306]
**Describe the bug**<br />
Not so much a bug, but deprecation warning in the latest version of react native (.62).

> Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker

**To Reproduce**<br />

1.  Create a new react native project, version .62
2.  Run any example
3.  See yellow warning box notifying deprecation

**Expected behavior**<br />
No yellow warning box

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/5076961/79029965-a76e2a80-7b4b-11ea-9fcb-50563ebe7693.png)

**Additional details**<br />
-   Device: Android Emulator, Pixel 2 XL
-   OS: Android N
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.62.1
-   react version: 16.11.0

**Reproduction and/or code sample**<br />
Snack react-native version is 0.53, and it's not possible to update this to 0.62.1.

**Comment by jamieshepherd** [comment]
Can you link the duplicate issue, please - so I can follow it?

**Comment by jcoulaud** [comment]
> Can you link the duplicate issue, please - so I can follow it?

I think it may be related to [this issue](https://github.com/lawnstarter/react-native-picker-select/issues/301) and [this PR](https://github.com/lawnstarter/react-native-picker-select/pull/303)
