### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by voslartomas** [lawnstarter/react-native-picker-select#31]
Would you consider to implement search inside picker?

**Comment by lfkwtz** [comment]
Can you explain in more detail?

**Comment by voslartomas** [comment]
Imagine long list it would be nice to have posibility to filter that list by user input

**Comment by lfkwtz** [comment]
Not currently, but I've added this to the feature request board. Feel free to submit a PR.

**Comment by lfkwtz** [comment]
out of scope of this library
