### ISSUE TITLE
Warning: Picker has been extracted from react-native core

### ISSUE THREAD

**Issue by AregShahbazian** [lawnstarter/react-native-picker-select#310]
**Describe the bug**<br />
Importing and using the Picker component causes the following warning:

`Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker `

**To Reproduce**<br />

Using `"react-native": "^0.62.2"` just import `import RNPickerSelect from "react-native-picker-select"` and render it.

**Expected behavior**<br />
No warning

**Screenshots**<br />
n/a

**Additional details**<br />
-   Device: Android
-   OS: Ubuntu
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.62.2
-   react version: 16.13.1

**Reproduction and/or code sample**<br />
Example app: https://github.com/AregShahbazian/RNPickerSelectBug

**Comment by SanjanaTailor** [comment]
@lfkwtz :  ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker
RNPickerSelect@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:124234:36 
Frequently getting this error on React native version 0.63. what is possible solution ?

**Comment by iqorlobanov** [comment]
I have the same error on RN version 0.63.2.

**Comment by brayoh** [comment]
I have the same error on RN version 0.63.3

**Comment by waterflower124** [comment]
Hi everyone.
Any solution?

**Comment by waterflower124** [comment]
I found a solution.
This module use version 1.6.0 of react-native picker.
"@react-native-community/picker": "1.6.0",
If modify this version to latest version then it will work. In my case the version is 1.8.1.

**Comment by mouhsnimohamed** [comment]
was this bug fixed? I have the same bug

**Comment by IamMasterWayne** [comment]
+1

**Comment by chenop** [comment]
Just upgraded to 8.0.4 - Warning is gone!

**Comment by ganeshkhedkaraa** [comment]
Any update on this issue!!

**Comment by KawaljeetCuelogic** [comment]
@lfkwtz I saw all your related comments on the issues and PR's, but could not really find a potential fix. I am using the latest version of the library and I am using React Native 0.66.3. This warning has turned into an error now.

Kindly help with the fix.

**Comment by KawaljeetCuelogic** [comment]
@ganeshkhedkaraa or @IamMasterWayne How were you able to overcome this?

**Comment by tdinckaya** [comment]
any update ?
