### ISSUE TITLE
Inaccurate README for useNativeAndroidPickerStyle

### ISSUE THREAD

**Issue by vparusheva** [lawnstarter/react-native-picker-select#314]
**Describe the bug**<br />
useNativeAndroidPickerStyle has been changed in the documentation stating it is a component. However, the API and the implementation are clearly showing it's a boolean.

**To Reproduce**<br />

1.  Read the README

**Expected behavior**<br />
useNativeAndroidPickerStyle must be noted as a boolean in the README

**Screenshots**<br />
"n/a".

**Additional details**<br />

**Reproduction and/or code sample**<br />
snack link does not apply for this issue

**Comment by lfkwtz** [comment]
fixed - thank you
