### ISSUE TITLE
Support Styling on React Native Web

### ISSUE THREAD

**Issue by haveamission** [lawnstarter/react-native-picker-select#315]
**Is your feature request related to a problem? Please describe.**<br>
I'd really like to be able to style this on React Native Web. Currently I cannot.

**Describe the solution you'd like**<br>
The default React Native picker supports styling out of the box. I would like this picker to work similarly on React Native Web

**Describe alternatives you've considered**<br>
Currently I am going to have to use separate components for web and native rendering, just so that I can style for the web.

**Additional details**<br>
Styling like the standard React Native Picker for React Native Web would be great.

**Comment by lfkwtz** [comment]
i'll throw this on the feature request board. i don't use rn web so likely not something i'll put time into but would be happy to hear suggestions or prs on this

**Comment by haveamission** [comment]
It's possible I might write a PR at some point for it

**Comment by haveamission** [comment]
Added a PR

**Comment by lfkwtz** [comment]
closing this out due to pr

**Comment by lfkwtz** [comment]
https://github.com/lawnstarter/react-native-picker-select/pull/316
