### ISSUE TITLE
Picker warning in RN 0.62.2

### ISSUE THREAD

**Issue by openwell** [lawnstarter/react-native-picker-select#317]
**Describe the bug**<br />
Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from \'@react-native-community/picker\' instead of \'react-native\'. See https://github.com/react-native-community/react-native-picker',  in RNPickerSelect

**To Reproduce**<br />

1.  install latest react native 0.62.2
2. install react native picker select
3. it shows yellow error

**Expected behavior**<br />
it shows a yellow error. And might be the cause of my app crash

**Screenshots**<br />
Nill

**Additional details**<br />
-   Device: [e.g. iPhone10 simulator]
-   OS: [e.g. iOS9]
-   react-native-picker-select version: [e.g. 6.6.0]
-   react-native version: [e.g. 0.62.2]
-   react version: [e.g. 16.11]

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

**Comment by openwell** [comment]
Hi, @lfkwtz if you call it duplicate... can point me to a reference ticket/issue so I can monitor it. 
or its something you are currently working on.

**Comment by lfkwtz** [comment]
https://github.com/lawnstarter/react-native-picker-select/pull/303
