### ISSUE TITLE
Pass styles to the TouchableOpacity and View inside ViewContainer

### ISSUE THREAD

**Issue by aks1994** [lawnstarter/react-native-picker-select#32]
Hi, thanks for making this library.

It is working well for me, but just had one question/feature request. Is it possible to pass styles to the TouchableOpacity or View of renderTextInputOrChildren inside the ViewContainer?

What I would like to achieve is making both the TouchableOpacity extend to the full area of the ViewContainer (essentially giving it Flex: 1). Currently it only occupies the width of its content.

**Comment by lfkwtz** [comment]
What lines specifically are you referring to where you'd like the styles opened up as props?

Feel free to submit a PR also

**Comment by aks1994** [comment]
Lines 204 and 224. My only goal is to be able to get the touchable area to have Flex: 1 and my child component to also be able to fill the entire parent area. For this I believe both the TouchableOpacity on 204 and the View on 224 need to have Flex: 1

**Comment by lfkwtz** [comment]
204 is a View and 224 is a TouchableWithoutFeedback, which doesn't accept a style prop.

**Comment by aks1994** [comment]
Yeah I mixed that up. But you're right, the TouchableWithoutFeedback doesn't accept style. I think just adding the style prop to the View on 224 should be sufficient.

**Comment by lfkwtz** [comment]
#37
