### ISSUE TITLE
Add testID to component props to easily access component with test libraries

### ISSUE THREAD

**Issue by WilcoBreedt** [lawnstarter/react-native-picker-select#321]
**Is your feature request related to a problem? Please describe.**<br>
The problem I am experiencing is writing tests using detox. I currently have a few selects on a screen and need to tap each one of them in order to set the values, but I am finding it difficult because I cannot specify a custom test id for each of the selects that I use. Another issue I am experiencing is when using stack navigators the previous selects are located that are not visible and I would like a unique way to ensure that I am selecting the correct select when testing.

**Describe the solution you'd like**<br>
Add a testID prop that overrides the following testID's when you provide it:
* android_picker
* ios_touchable_wrapper
* android_touchable_wrapper
So I would like to replace the testID in index.js with something like this:
```
<TouchableOpacity
                testID={testID || 'android_touchable_wrapper'}
```
So when the testID is provided replace it, otherwise keep the original testID.

**Describe alternatives you've considered**<br>
Currently I am selecting all the selects and then accessing them by index, but when you have a lot of selects this gets confusing especially with nested views and navigation stacks

**Additional details**<br>
NONE

**Comment by lfkwtz** [comment]
override with touchableWrapperProps / pickerProps / etc

**Comment by TildeWill** [comment]
Did either of you have an example that works for picking a value? I'm running in to the same issue now.

**Comment by TildeWill** [comment]
We were able to write a test that picked something from the picker. We found that you had to tap twice on the text field to get the picker to open up, like this:

in `index.js`
```javascript
import RNPickerSelect from 'react-native-picker-select'
...
<RNPickerSelect
  touchableWrapperProps={{testID: "myUsStatePicker"}} 
  ... 
/>
```
in `happyPath.spec.js`:

```javascript
describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative()
  })

  it('lets the user pick a US state from the picker', async () => {
    ...
    await element(by.id('myUsStatePicker')).tap() //tap once to focus the text input
    await element(by.id('myUsStatePicker')).tap() //tap a second time to open the picker modal
    await element(by.text('Alabama')).tap() //can only pick one of the first three-ish values because they are the ones that are visible when the picker is opened, otherwise you could maybe scroll
    await element(by.text('Done')).tap()
    ...
  })
})
```
cc @stupakov

**Comment by TildeWill** [comment]
As a follow up, having to do the double tap was hard to discover. I'd love to see a future version of this component eliminate the need for the extra tap.

**Comment by dustinyoste** [comment]
Not entirely proud of this solution, but if someone else ends up on this issue because they cannot get any of the testIDs to work with Detox on android, here's a crude temporary approach. 

You'll definitely want to add a timeout or safety count to the while loop.
`item` and `scrollview` are both objects returned from `element()`

```
const scrollToAndSelect = async (item, scrollview) => {
    scrollview = scrollview || element(by.type('androidx.appcompat.app.AlertController$RecycleListView'));

    while (true) {
        await scrollview.swipe('up', 'slow', 1, NaN, 0.25);
        try {
            await item.tap();
            break;
        } catch {
        }
    }
}
```

**Comment by dustinyoste** [comment]
> Another way of scrolling would be doing:
> 
> ```
> const picker = element(by.id("ios_picker"));
> await expect(picker).toBeVisible();
> await picker.tap();
> picker.setColumnToValue(0, "Desired Value");
> ```

@chenop 
Thank you! 

Thanks to the ios input, we put this together for android and ios 

```
const scrollToAndSelectAndroid = async (item) => {
    const scrollview = element(by.type('androidx.appcompat.app.AlertController$RecycleListView'));

    let loopTimedOut = false;
    const timeout = setTimeout(() => { loopTimedOut = true; }, 15000);

    while (!loopTimedOut) {
        await scrollview.swipe('up', 'slow', 1, NaN, 0.25);
        try {
            await item.tap();
            clearTimeout(timeout);
            break;
        } catch {
        }
    }
}

const pickerSelect = async (itemText) => {
    if(device.getPlatform() === 'ios') {
        const picker = element(by.id("ios_picker"));
        await expect(picker).toBeVisible();
        await picker.tap();
        await picker.setColumnToValue(0, itemText);
        await element(by.id('done_text')).tap();
    } else { // android
        await scrollToAndSelectAndroid(element(by.text(itemText)));
    }
}
```

Example in use:
```
    await element(by.id('id-of-input-form')).tap(); // to open the picker
    await pickerSelect('text of item to select');
```
