### ISSUE TITLE
Error while updating property 'colors' of a view managed by AndroidTextInput in react-native-picker when using useNativeAndroidPickerStyle={false}

### ISSUE THREAD

**Issue by akhilsanker** [lawnstarter/react-native-picker-select#330]
**Describe the bug**<br />
When using `useNativeAndroidPickerStyle={false}`, getting error as
`Error while updating property 'colors' of a view managed by AndroidTextInput in react-native-picker` on selecting a picker item.

**Screenshots**<br />

![Screenshot_2020-06-04-12-16-30-850_com test](https://user-images.githubusercontent.com/32122016/83724322-b5c55800-a65d-11ea-964a-f880f30cff1e.png)

**Additional details**<br />
-   Device: xiaomi redmi note 4
-   OS: Android 6
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.59.8
-   react version: 16.8.3

**Reproduction and/or code sample**<br />

             <RNPickerSelect
	        	useNativeAndroidPickerStyle={false}
	            onValueChange={(value) => console.log(value)}
	            items={[
	                { label: 'Football', value: 'football' },
	                { label: 'Baseball', value: 'baseball' },
	                { label: 'Hockey', value: 'hockey' },
	            ]}
	        />

**Comment by gsevla** [comment]
+1

**Comment by lfkwtz** [comment]
you'll need to provide a more thorough reproduction than that. the example snack utilizes `useNativeAndroidPickerStyle={false}` on multiple instances without issues.

**Comment by ryanm** [comment]
@akhilsanker I encountered this bug. The solution was to set a color property on the inputAndroid style object. The value of the color property can't be an abbreviated hex code like '#000', it has to be like '#000000' or 'black'.

**Comment by taekkuda** [comment]
> countered this bug. The solution was to set a color property on the inputAndroid style object. The value of the color property can't be an abbreviated hex code like '#0', it has to be like '#0' or 'black'.

can you share more detailed code for the fixing sir?

**Comment by ryanm** [comment]
@taekkuda I re-read my comment (from over a year ago). It looks like GitHub's comment parser changed what I wrote in single quotes. This:
> ...an abbreviated hex code like '#0', it has to be like '#0' or 'black'.

should be:
> ...an abbreviated hex code like `#000`, it has to be like `#000000` or `black`.

Even now I see GitHub's comment parser has added a black circle which I am not intending.

I do not remember any more about the solution than that. Hope this helps you.
