### ISSUE TITLE
Error: While trying to resolve module `react-native-picker-select` from file 

### ISSUE THREAD

**Issue by RubenJj** [lawnstarter/react-native-picker-select#333]
BUG

error: Error: While trying to resolve module `react-native-picker-select` from file `C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\src\components\Form.js`, the package `C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js`. Indeed, none of these files exist:

  * C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)

**To Reproduce**<br />

1.  Add the: import RNPickerSelect from 'react-native-picker-select';
2.  Compile or save the file, and the Android emulator will show up the attached error below.

**Expected behavior**<br />
Im just simply copy/pasting the code example from here:

 https://www.npmjs.com/package/react-native-picker-select

**Screenshots**<br />

![image](https://user-images.githubusercontent.com/38173365/86613139-76b65980-bfb1-11ea-932d-7cfdf25adbc3.png)

**Additional details**<br />
-   Device: [HP Spectre 13]
-   OS: [Windows Home 10]
-   react-native-picker-select version: [ 7.0.0]
-   react-native version: [0.61]

**Reproduction and/or code sample**<br />
import React from "react";
import RNPickerSelect from 'react-native-picker-select';

import {
  StyleSheet,
  View,
  TextInput,
} from 'react-native';
import colors from "../utils/colors";

export default function Form(){
    return (
        <View style = {styles.viewForm}>
            <View style={styles.viewInputs}>
                <TextInput 
                    placeholder="Cantidad a pedir"
                    keyboardType="numeric"
                    style={styles.input} 
                />
                <TextInput 
                    placeholder="Interes %"
                    keyboardType="numeric"
                    style={[styles.input, styles.inputPercentage]} 
                />
            </View>

            <RNPickerSelect
            onValueChange={(value) => console.log(value)}
            items={[
                { label: 'Football', value: 'football' },
                { label: 'Baseball', value: 'baseball' },
                { label: 'Hockey', value: 'hockey' },
            ]}
        />
        </View>
    );

}

const  styles=StyleSheet.create({
    viewForm: {
        position:"absolute",
        bottom: -90,
        width: "85%",
        paddingHorizontal: 50,
        backgroundColor: colors.PRIMARY_COLOR_DARK,
        borderRadius:30,
        height: 180,
        justifyContent:"center"

    },
    viewInputs: {
        flexDirection:"row",
    },
    input: {
        height:50,
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: color.PRIMARY_COLOR_DARK,
        borderRadius: 5,
        width:'60%',
        marginRight: 5,
        marginLeft: -5,
        marginBottom: 10,
        color: "#000",
        paddingHorizontal: 20,

    },
    inputPercentage: {
        width:'40%',
        marginLeft: 5,
    }

});

**Comment by RubenJj** [comment]
I tried adding the library as explained here for a very similar issue, although another library, but didnt work:

https://github.com/react-native-community/react-native-image-picker/issues/1165

**Comment by Meninas** [comment]
The same,
` ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Unexpected token (19:21)
File: node_modules\react-native-picker-select\src\index.js:19:21
failed Building development bundle - 4.125s`

Greetings

**Comment by ArvindNikam76** [comment]
Facing Same Issue Error: While trying to resolve module `react-native-picker-select` from file

**Comment by ArvindNikam76** [comment]
> BUG
> 
> error: Error: While trying to resolve module `react-native-picker-select` from file `C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\src\components\Form.js`, the package `C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js`. Indeed, none of these files exist:
> 
> * C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> * C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\react-native-picker-select\src\index.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
>   at ResolutionRequest.resolveDependency (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:65:15)
>   at DependencyGraph.resolveDependency (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
>   at Object.resolve (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\lib\transformHelpers.js:267:42)
>   at C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
>   at Array.map ()
>   at resolveDependencies (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
>   at C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
>   at Generator.next ()
>   at asyncGeneratorStep (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
>   at _next (C:\Users\Ruben\Desktop\mobiledev\cotizadorprestamos\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Add the: import RNPickerSelect from 'react-native-picker-select';
> 2. Compile or save the file, and the Android emulator will show up the attached error below.
> 
> **Expected behavior**
> 
> Im just simply copy/pasting the code example from here:
> 
> https://www.npmjs.com/package/react-native-picker-select
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/38173365/86613139-76b65980-bfb1-11ea-932d-7cfdf25adbc3.png)
> 
> **Additional details**
> 
> * Device: [HP Spectre 13]
> * OS: [Windows Home 10]
> * react-native-picker-select version: [ 7.0.0]
> * react-native version: [0.61]
> 
> **Reproduction and/or code sample**
> 
> import React from "react";
> import RNPickerSelect from 'react-native-picker-select';
> 
> import {
> StyleSheet,
> View,
> TextInput,
> } from 'react-native';
> import colors from "../utils/colors";
> 
> export default function Form(){
> return (
> 
> 
> 
> <TextInput
> placeholder="Interes %"
> keyboardType="numeric"
> style={[styles.input, styles.inputPercentage]}
> />
> ```
>         <RNPickerSelect
>         onValueChange={(value) => console.log(value)}
>         items={[
>             { label: 'Football', value: 'football' },
>             { label: 'Baseball', value: 'baseball' },
>             { label: 'Hockey', value: 'hockey' },
>         ]}
>     />
>     </View>
> );
> ```
> 
> }
> 
> const styles=StyleSheet.create({
> viewForm: {
> position:"absolute",
> bottom: -90,
> width: "85%",
> paddingHorizontal: 50,
> backgroundColor: colors.PRIMARY_COLOR_DARK,
> borderRadius:30,
> height: 180,
> justifyContent:"center"
> 
> ```
> },
> viewInputs: {
>     flexDirection:"row",
> },
> input: {
>     height:50,
>     backgroundColor: "#fff",
>     borderWidth: 1,
>     borderColor: color.PRIMARY_COLOR_DARK,
>     borderRadius: 5,
>     width:'60%',
>     marginRight: 5,
>     marginLeft: -5,
>     marginBottom: 10,
>     color: "#000",
>     paddingHorizontal: 20,
> 
> },
> inputPercentage: {
>     width:'40%',
>     marginLeft: 5,
> }
> ```
> 
> });

did You get solution for this?

**Comment by ArvindNikam76** [comment]
Any update on this? this blocker for me.

**Comment by pouriabagheri** [comment]
same for me.

**Comment by lfkwtz** [comment]
check if fixed by v8.0.0

**Comment by deddikation** [comment]
change the import of the picker to '@react-native-community/picker' in the react-native-picker-select/src/index.js
