### ISSUE TITLE
TypeError: Cannot read property 'Item' of undefined [Android Only]

### ISSUE THREAD

**Issue by sathwik77** [lawnstarter/react-native-picker-select#335]
**Describe the bug**<br />
Implementing RNPickerSelect with the example given from docs, throws the above mentioned error in Android, works fine in IOS

**To Reproduce**<br />

```
                <RNPickerSelect
                    onValueChange={(value) => console.log(value)}
                    placeholder={{
                        label: 'Select a sport...',
                        value: null,
                        color: '#9EA0A4',
                    }}
                    items={[
                    { label: 'Football', value: 'football' },
                    { label: 'Baseball', value: 'baseball' },
                    { label: 'Hockey', value: 'hockey' },
                ]}
                />
```

**Expected behavior**<br />
To work fine as it works in IOS

**Screenshots**<br />
![WhatsApp Image 2020-07-13 at 10 47 56 AM](https://user-images.githubusercontent.com/26072324/87269111-6abd2100-c4f6-11ea-87a0-c2b65f64348a.jpeg)

**Additional details**<br />
-   Device: Android 9.0.0
-   OS: 13.3
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.63
-   react version: 16.11.0
-   Expo version: 38.0

**Comment by schieck0** [comment]
Try uninstall @react-native-community/picker

**Comment by sathwik77** [comment]
Its not showing anything on screen if I uninstall @react-native-community/picker

**Comment by schieck0** [comment]
RNPickerSelect dont worked for me with @react-native-community/picker installed. Unistalling than worked fine

**Comment by aqeebimtiaz** [comment]
Same error for me. Landed here to find that the very package isn't working! WOW!
