### ISSUE TITLE
Warning: Picker has been extracted from react-native core and will be removed in a future release.

### ISSUE THREAD

**Issue by silencer07** [lawnstarter/react-native-picker-select#338]
**Describe the bug**<br />
[Fri Jul 24 2020 09:45:43.178]  ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker 
RNPickerSelect@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:226164:36

**To Reproduce**<br />
1. create new app
2. install this library
3. see console logs for error

**Expected behavior**<br />
Use the extracted community picker instead from the /react-native one

**Screenshots**<br />
n/a

**Additional details**<br />
-   latest react-native 0.63.2

**Reproduction and/or code sample**<br />
n/a

**Comment by caiobiodere** [comment]
having the same issue here, are you guys aware of this problem?

**Comment by GoktuqCan** [comment]
Having same issue with react-native 0.63.2

**Comment by caiobiodere** [comment]
@lfkwtz do you think you can fix this soon? it will be awesome to actually know before forking to fix this

**Comment by lfkwtz** [comment]
#301

**Comment by lfkwtz** [comment]
@caiobiodere you can use this fork if you feel the need: https://github.com/lawnstarter/react-native-picker-select/pull/303

**Comment by caiobiodere** [comment]
@lfkwtz any plans on merging that request?
