### ISSUE TITLE
label indicating the current selected value won't change when props change

### ISSUE THREAD

**Issue by begoat** [lawnstarter/react-native-picker-select#34]
I met some problems when try to change state after component mounted.
* [here is the minimum repo, it doesn't work](https://github.com/begoat/temp-repreduce.git) the label indicating the current selected value won't change when props change
* [here is the online version, it works with the same code](https://snack.expo.io/H16PMK3eQ) I don't know why
I've spent much time on it but in vain, could you give me a hand? 
Thanks in advance

**Comment by lfkwtz** [comment]
Can you try with the the version currently on master and see if that fixes it? This sounds exactly like the bug fix I merged in yesterday. 

https://github.com/lawnstarter/react-native-picker-select/pull/33

**Comment by begoat** [comment]
I am afraid it is still not working with version 3.1.1

**Comment by lfkwtz** [comment]
Version isn't what's important. Are you pulling the repo from master or from npm?

**Comment by begoat** [comment]
i pulled from npm just now, i will try the former one.

**Comment by begoat** [comment]
i clone this repo and install the npm dependency from file but it doesn't work

**Comment by lfkwtz** [comment]
try 3.1.2

**Comment by begoat** [comment]
lastest master branch doesn't solve the problem

**Comment by lfkwtz** [comment]
Your expo snack example doesn't change the props at any point. You'll need to reproduce the issue for me again, otherwise I don't know what's wrong.

**Comment by begoat** [comment]
Sorry for the confusing problem description. I mean when run it in expo online the component works well, but when i use it in my repo, the label won't change, i don't know why so i issue it.

**Comment by lfkwtz** [comment]
You need to be using v2 or earlier. See the readme.

**Comment by begoat** [comment]
Thank you, I tried and it worked. Sorry for not reading README carefully:)
