### ISSUE TITLE
Error:  Warning: Picker has been extracted from react-native core and will be removed in a future release.

### ISSUE THREAD

**Issue by SanjanaTailor** [lawnstarter/react-native-picker-select#343]
** Warning: Picker has been extracted from react-native core and will be removed in a future release.**<br />

**To Reproduce**<br />

1.  Installed plugin to "react-native-picker-select": "^7.0.0"'
4.  See error on Metro server

**"react-native-picker-select": "^7.0.0",**<br />
 ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker
RNPickerSelect@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:124413:36
RCTView
TouchableWithoutFeedback@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:70097:36
RCTView
RCTView
TouchableWithoutFeedback@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:70097:36
DismissKeyboard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:124029:26
SelectionPickerComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:124000:41
RCTView
RCTScrollView
ScrollView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:63188:36
ScrollView
KeyboardAwareScrollView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:126237:38
RCTView
RCTView
SafeAreaView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:72914:41
NewEvent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:118019:26
SceneView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:102366:36
RCTView
RCTView
RCTView
CardSheet@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:116202:23
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:60223:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:106567:38
PanGestureHandler@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:110928:34
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:60223:24
AnimatedComponentWrapper
RCTView
Card@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:113803:36
CardContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:113459:22
RCTView
MaybeScreen@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:111625:24
RCTView
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:111612:23
CardStack@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:111178:36
KeyboardManager@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:116396:36
RNCSafeAreaView
SafeAreaProvider@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:110773:24
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:116899:24
GestureHandlerRootView
GestureHandlerRootView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:107120:24
StackView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:110352:36
StackView@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:117132:26
Navigator@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:99858:38
NavigationContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:103814:38
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:67809:22

**Screenshots**<br />
Add screenshots to help explain your problem. If screenshots aren't applicable to this issue, write "n/a".

**Additional details**<br />
-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   react-native-picker-select version: "^7.0.0"
-   react-native version:  0.63.0
-   react version: 16.13.1

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

**Comment by lfkwtz** [comment]
duplicate

**Comment by SanjanaTailor** [comment]
@lfkwtz  : what is solution for the above issue ?

**Comment by lfkwtz** [comment]
v8

**Comment by cenaHara** [comment]
hi @lfkwtz  v8 still with version 0.63.3

**Comment by chenop** [comment]
Just upgraded to 8.0.4 - Warning is gone!
