### ISSUE TITLE
select multiple option

### ISSUE THREAD

**Issue by ltsharma** [lawnstarter/react-native-picker-select#35]
Is there any plans to add support for multiple select options?

**Comment by lfkwtz** [comment]
Not currently, but I've added this to the feature request board. Feel free to submit a PR.

**Comment by IntelliJAbhishek** [comment]
@lfkwtz  any update on this?

**Comment by ycldz** [comment]
It would be great if you could add a multi-selection feature.

**Comment by ycldz** [comment]
It would be great if you could add a multi-selection feature
