### ISSUE TITLE
Incorrect Icon position after device was rotated

### ISSUE THREAD

**Issue by oleg-moseyko** [lawnstarter/react-native-picker-select#356]
**Describe the bug**<br />
Incorrect Icon position after device was rotated. I think it related with  maxWidth: 500.
```javascript
const pickerSelect = {
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30, 
    maxWidth: 500, // ?????????????????????????
      
};
const pickerSelectStyles = StyleSheet.create({
    inputIOS: {
        ...pickerSelect,       
    },
    inputAndroid: {
        ...pickerSelect,        
    },
    iconContainer: {
        top: 11,
        right: 12,
    },
});
```
**To Reproduce**<br />

 Rotate device 

**Expected behavior**<br />
Icon must be inside RNPickerSelect. Also I noticed that place which is marked by red rectangle is still touchable and opens picker.

**Screenshots**<br />

<img width="331" alt="Знімок екрана 2020-08-26 о 10 07 14" src="https://user-images.githubusercontent.com/25344716/91272389-53738380-e784-11ea-9274-83e33821f52b.png">
<img width="686" alt="Знімок екрана 2020-08-26 о 10 07 32" src="https://user-images.githubusercontent.com/25344716/91272401-58383780-e784-11ea-88b3-2075ccbb7ac3.png">

**Additional details**<br />

-   OS: iOS/Android
-   react-native-picker-select version: "^7.0.0",
-   react-native version: "0.62.0",
-   expo sdk version:  n/a

**Reproduction and/or code sample**<br />
https://snack.expo.io/@olegmoseyko/privileged-edamame

**Comment by lfkwtz** [comment]
correct - the input is a sibling of the icon, you'll likely have better luck using `inputIOSContainer` for your width management
