### ISSUE TITLE
Typescript missing togglePicker method

### ISSUE THREAD

**Issue by smaccoun** [lawnstarter/react-native-picker-select#357]
**Describe the bug**<br />
When calling `togglePicker` on a picker ref, Typescript complains that `Property 'togglePicker' does not exist on type 'Picker'`

**To Reproduce**<br />
```
import * as React from 'react';
import { Text, View, StyleSheet, TouchableOpacity } from 'react-native';
import Constants from 'expo-constants';

import RNPickerSelect from 'react-native-picker-select'


export default function App() {
  const pickerRef = React.useRef<RNPickerSelect | null>()

  return (
      <View>
       <TouchableOpacity onPress={() => {
           if (pickerRef.current) {
             pickerRef.current.togglePicker(true)
           }
        }}>
        <Text>Edit</Text>
      </TouchableOpacity>
      <RNPickerSelect
          ref={r => pickerRef.current = r}
          value={3}
          placeholder={{ label: '3', value: '3' }}
          onValueChange={() => console.log('change')}
          items={[{label: 'test', value: 3}]}
        />
      </View>
   )
}
```

1.  Set ref on picker
2.  Call ref's current value with `togglePicker` and TS complains

**Expected behavior**<br />
`togglePicker` should be an available method on the ref

**Screenshots**<br />
Add screenshots to help explain your problem. If screenshots aren't applicable to this issue, write "n/a".

n/a

**Additional details**<br />
-   Device: [e.g. iPhoneX]
-   OS: [e.g. iOS13]
-   react-native-picker-select version: [e.g. 8.0.0]
-   react-native version: [e.g. 0.63]

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

https://snack.expo.io/nTnz2oJFg

**Comment by lfkwtz** [comment]
want to open a PR?
