### ISSUE TITLE
[Android] java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles() when calling getSubscriptions() or getProducts()

### ISSUE THREAD

**Issue by sbrighiu** [lawnstarter/react-native-picker-select#359]
**Describe the bug**<br />
[Android] java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles() when calling getSubscriptions() or getProducts()

**To Reproduce**<br />
Call getSubscriptions() or getProducts() and see the crash

**Expected behavior**<br />
To not crash

**Screenshots**<br />
n/a

**Additional details**<br />
Is this a bug? Or is it because i use

```
dependencies {
    implementation "com.android.billingclient:billing:3.0.0"
   ...
}
```
instead of

```
dependencies {
    implementation "com.android.billingclient:billing:2.0.3"
   ...
}
```
The app crashes when i pull subscriptions from the Play Store. I implemented the whole payment process, but at one point if started crashing on android when pulling subscription details. It loads for a long time and then crashes with

`java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in .apk`

**Reproduction and/or code sample**<br />
Is this a bug or a misconfiguration?

**Comment by lfkwtz** [comment]
this doesn't look at all related to this package

**Comment by sbrighiu** [comment]
tons of sorry's :(

**Comment by lfkwtz** [comment]
all good. best of luck figuring it out.
