### ISSUE TITLE
Error while updating property color of a view managed by: AndroidTextInput

### ISSUE THREAD

**Issue by tattivitorino** [lawnstarter/react-native-picker-select#361]
**Describe the bug**<br />
If I set the prop useNativeAndroidPickerStyle={false} I get this error when selecting an option from the picker. No matter what I do, just by setting it to false I have this error. Has anyone had this problem?

**To Reproduce**<br />

```
               <RNPickerSelect
                  placeholder={{
                    label: "Select the Line",
                    value: null,
                  }}
                  useNativeAndroidPickerStyle={false}
                  onValueChange={(line) => this.setState({ line })}
                  value={this.state.line}
                  items={[{ label: "Line 911", value: "911" }]}
                  style={{ ...pickerStyles }}
                  Icon={() => (
                    <Ionicons
                      name="md-arrow-dropdown"
                      size={25}
                      color={colors.text}
                    />
                  )}
                />
```

1.  Set useNativeAndroidPickerStyle to false
2. Select an option
3. Pops the error

**Expected behavior**<br />
Option should be selected

**Screenshots**<br />
![Screenshot_1599158809](https://user-images.githubusercontent.com/5480296/92156087-d8067780-edfe-11ea-9294-01f89ac2e8d3.png)

**Additional details**<br />
-   Device: [e.g. Samsung A10]
-   OS: [e.g. Android 10]
-   react-native-picker-select version: [e.g. ^8.0.0]
-   react-native version: [e.g. 0.62.2]
-   expo sdk version: [e.g. 38] - Bare WorkFlow

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

**Comment by lfkwtz** [comment]
#330

**Comment by tattivitorino** [comment]
@lfkwtz thanks a lot for the reply! problem solved!

**Comment by tarunnurat** [comment]
@tattivitorino could you give me some kind of code example as to how you fixed this issue?
