### ISSUE TITLE
onValueChange is not a function in android

### ISSUE THREAD

**Issue by karna419** [lawnstarter/react-native-picker-select#362]
**Describe the bug**<br />
I have xxxxx.android.js file
when I click an item from the selection list, getting 

TypeError: onValueChange is not a function. (In 'onValueChange(value, index)', 'onValueChange' is undefined)

But I can see the select value in the input section. Previously I used like xxxxx.js file.m It also had an issue which is when selecting an item from the list, the selected item disappears right after a second any item was selected. But it's gone after using xxxx.android.js.

**To Reproduce**<br />
I am assuming it can't be reproduced. Correct me if there is a way

 ```
<RNPickerSelect              
                onValueChange={(value) => console.log(value)}
                items={getTypes(materials)}
                useNativeAndroidPickerStyle={true}
                value={trainingType}
                placeholder={{
                  label: "Select training type",
                  value: null,
                  color: "grey",
                }}
              />
```
**Expected behavior**<br />
Able to get selected value on the callback 

**Screenshots**<br />
n/a

**Additional details**<br />
  Binaries:
    Node: 10.19.0 
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by karna419** [comment]
It was my mistake. onValueChange()  function working correctly.Thanks. 
But the onValueChange function called twice.

**Comment by karna419** [comment]
I have mentioned

>>It also had an issue which is when selecting an item from the list, the selected item disappears right after a second any item was selected

it is not showing selected item (instead showing blank input box) when using useNativeAndroidPickerStyle -> true. But i use useNativeAndroidPickerStyle->false, i can see the selected item.

I have noticed one thing was that if I try useNativeAndroidPickerStyle to true->false->true, I can see in the android view that I can't see right after the initial rendering.

**Comment by lfkwtz** [comment]
you'll have to help me with a repro or some more details. i'm not clear what the problem is.

**Comment by karna419** [comment]
The snippet is same that i shared in this issue. Once i select any item from the list, it is not reflect input. Rather shows blank(actually item was selected). As you can see in the images. If i try nativedriver(true) -> nativedriver(false) -> nativedriver(true). It reflects the selected (One of the image with Ground as input). 
![20200919_142739-1](https://user-images.githubusercontent.com/43859501/93663732-983ec180-fa87-11ea-9947-b152ab0dbf5a.jpg)
![20200919_142704-1](https://user-images.githubusercontent.com/43859501/93663743-ad1b5500-fa87-11ea-8fe2-5fd099387769.jpg)
![20200919_142610-1](https://user-images.githubusercontent.com/43859501/93663751-bb697100-fa87-11ea-97b0-dc02c0e1e8c4.jpg)

**Comment by karna419** [comment]
This happened in android app

**Comment by lfkwtz** [comment]
please re-open a new bug report if that other issue is still present. sounds like the onValueChange was solved.
