### ISSUE TITLE
Change InputAccessoryView

### ISSUE THREAD

**Issue by Catnais88** [lawnstarter/react-native-picker-select#379]
**Describe the bug**<br />
Hello,

I try to change the default Input Accessory View by mine. But when I provide one, the default one disappears and there is nothing else.

**To Reproduce**<br />

1.  Create a new inputAccessoryView
2.  Add it to prop InputAccessoryView in RNPickerSelect
3. Click on the picker in the screen
4.  See nothing above the keyboard

**Expected behavior**<br />
I expected to see my inputAccessoryView above the keyboard.

**Screenshots**<br />
![simulator_screenshot_06D24EE9-2F34-4EAA-8C30-A4218ADFC103](https://user-images.githubusercontent.com/31761109/96111858-130dc780-0ee2-11eb-93ad-93602774bff8.png)

**Additional details**<br />
-   OS: iOS
-   react-native-picker-select version: 7.0.0
-   react-native version: 0.63.9
-   expo sdk version: 39

**Reproduction and/or code sample**<br />
`const PickerSelect = () => {
  const inputAccessoryView = () => {
    return (
      <View>
        <InputAccessoryView>
          <TouchableWithoutFeedback
            style={styles.inputAccessoryView}
            onPress={() => {
              Keyboard.dismiss();
            }}
          >
            <Text style={styles.textInputAccessoryView}> OK </Text>
          </TouchableWithoutFeedback>
        </InputAccessoryView>
      </View>
    );
  };

  return (
    <View style={containerStyle}>
      <RNPickerSelect
        {...(Platform.OS === "ios" && {
          pickerProps: { style: { height: 214, overflow: "hidden" } },
        })}
        useNativeAndroidPickerStyle={false}
        InputAccessoryView={inputAccessoryView}
      />
    </View>
  );
});

export default PickerSelect;

const getStyles = () =>
  StyleSheet.create({
    inputAccessoryView: {
      backgroundColor: "#d5d8de",
    },
    textInputAccessoryView: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 15,
      textAlign: "right",
      color: "#147EFB",
      fontSize: 18,
    },
  });`

**Comment by lfkwtz** [comment]
code sample is incomplete. missing closing tag for TouchableWithoutFeedback - looks like more is missing. will re-open if you fix this.

**Comment by dsc-jerome-dc** [comment]
I need to change the gray color to something else please share if someone find a way
