### ISSUE TITLE
Error: "No command found with name setTextAndSelection"

### ISSUE THREAD

**Issue by Filippinifra** [lawnstarter/react-native-picker-select#380]
**Describe the bug**<br />
When RNPickerSelect is rendered and i try to change the selection an error occurred and tell me: 
_No command found with name setTextAndSelection_

**To Reproduce**<br />
Steps to reproduce the behaviour:

1. Create an expo repo
2. Render this Dropdown's example:

import React from "react";
import RNPickerSelect from "react-native-picker-select";

export const Dropdown = () => (
...<RNPickerSelect
......onValueChange={() => {}}
......items={[
.........{ label: "Football", value: "football" },
.........{ label: "Baseball", value: "baseball" },
.........{ label: "Hockey", value: "hockey" },
......]}
.../>
);

3. Open a simulator or use the expo app to render the code in you mobile device
4. Click on Dropdown when is rendered
5. Scroll options and on hover an option the error appears

**Expected behaviour**<br />
Error should not occurred

**Screenshots**<br />
![photo_2020-10-18 13 23 34](https://user-images.githubusercontent.com/31794601/96366011-28366080-1145-11eb-9514-9bb9f893de17.jpeg)

**Additional details**<br />
-   Device: [Phone 11]
-   OS: [iOS14.0.1]
-   react-native-picker-select version: [e.g. 8.0.2]
-   react-native version: [sdk-39.0.3]
-   expo sdk version: [38.0.8]

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

I think is so easy to reproduce so we don't need a snack

**Comment by lfkwtz** [comment]
works fine on the sample app https://snack.expo.io/@lfkwtz/react-native-picker-select

need to actually provide reproducible code
