### ISSUE TITLE
Mode prop is not working.(Android)

### ISSUE THREAD

**Issue by caglardurmus** [lawnstarter/react-native-picker-select#382]
**Describe the bug**<br />
Mode prop is not working. 

**To Reproduce**<br />

1.  setting mode='dropdown'
2.  Clicking component
3.  It opens with 'modal'

**Expected behavior**<br />
It needs open with 'dropdown'.

**Screenshots**<br />
[Screenshot_1603356644](https://user-images.githubusercontent.com/39800322/96848530-380fb680-145d-11eb-927f-074905630435.png)

**Additional details**<br />
-   Device: Android Simulator
-   OS: Android 9 
-   react-native-picker-select version: 8.0.0
-   react-native version: 0.63.3
-   @react-native-community/picker: ^1.8.1

**Reproduction and/or code sample**<br/>
```
<RNPickerSelect
                    mode="dropdown"
                    onValueChange={(value) => console.log(value)}
                    items={[
                                { label: 'Football', value: 'football' },
                                { label: 'Baseball', value: 'baseball' },
                                { label: 'Hockey', value: 'hockey' },
                    ]}
                    style={{
                        inputIOS: styles.inputStyle,
                        inputAndroid: styles.inputStyle,
                        iconContainer: Platform.OS == 'ios' ? null : styles.iconContainer,
                    }}
                    Icon={() => <CustomIcon
                        name="arrow-drop-down"
                        type="MaterialIcons"
                        style={styles.dropdownIcon}
                    />}
                    doneText={'Ok'}
/>

```

**Comment by lfkwtz** [comment]
`pickerProps`

**Comment by saravanatm** [comment]
Any solution for this issue..I'm also facing the same issue
