### ISSUE TITLE
Scrolling when I have duplicate value in items

### ISSUE THREAD

**Issue by wenit123** [lawnstarter/react-native-picker-select#386]
**Describe the bug**<br />
I have duplicate value in the items array.
When I select the one I want, it show the selected one in the screen.
But in drop down will scroll automatically to the last one of the same value.

**To Reproduce**<br />

1.  Go to 'screen'
2.  Click on 'drop down'
3.  Scroll down to ' Wyoming 0%'
4.  See error,  the value show on the screen is right, but in dropdown it jump to 'Montana 0%'

**Expected behavior**<br />

**Screenshots**<br />
![image](https://user-images.githubusercontent.com/16068081/97915790-e7bf1100-1d06-11eb-86eb-eb7fc504f02f.png)

<img width="425" alt="Screen Shot 2020-11-02 at 12 18 42 PM" src="https://user-images.githubusercontent.com/16068081/97915518-73846d80-1d06-11eb-9c41-b50403292c90.png">

**Additional details**<br />
-   Device: Iphone 11
-   OS: IOS14
-   react-native-picker-select version: ^8.0.0
-   react-native version: ^0.63.2
-   expo sdk version: [e.g. 38 or n/a]

**Reproduction and/or code sample**<br />

```<RNPickerSelect
                  placeholder={{
                    label: 'Select tax rate...',
                    value: 0,
                  }}
                  onValueChange={(itemValue, itemIndex) => this.setState({ selectedTax: itemValue })}
                  items={this.state.taxRates.map(obj =>
                    ({
                      label: obj.name + ' ' + obj.rate + '%',
                      value: obj.rate,
                    })
                  )}
                  style={{
                    inputIOS: { color: 'gray' },
                    inputAndroid: { color: 'gray' },
                  }}
                />```

**Comment by lfkwtz** [comment]
look for `itemKey` in the docs
