### ISSUE TITLE
Style viewContainer is not working on Android

### ISSUE THREAD

**Issue by alimoli** [lawnstarter/react-native-picker-select#389]
**Describe the bug**<br />
While `viewContainer` for iOS is effective, on Android no changes. 

**To Reproduce**<br />

1.  Set a style with `viewContainer`
2.  Check the differences on the two platforms (iOS and Android)

**Expected behavior**<br />
Same `viewContainer` style for both platforms, not only iOS.

**Screenshots**<br />
n/a

**Additional details**<br />
-   Device: Android simulator
-   OS: Android
-   react-native-picker-select version: 8.0.2
-   react-native version: 0.63.2
-   expo sdk version: n/a

**Reproduction and/or code sample**<br />
n/a

**Comment by lfkwtz** [comment]
**Reproduction and/or code sample** is not optional

**Comment by seaerchin** [comment]
hey, @lfkwtz i just encountered this and the problem was with the `viewContainer` not being spread across the component for `renderAndroidHeadless`; i'll submit a minor bugfix for this but let me know if you require a new issue or putting it here would be ok
