### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker

### ISSUE THREAD

**Issue by erikaperugachi** [lawnstarter/react-native-picker-select#390]
**Describe the bug**<br />
Show this message: Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker

**To Reproduce**<br />
1) Install react-native-picker-select@^8.0.2 in your project
2) Run yarn start(ios-android) of your project
3) show this message: Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker
4) install @react-native-community/picker@^1.8
5) run yarn start. And this is ok!

BUT
6) If other member, download the current project with my changes and run yarn install and yarn start
7) show this message: Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker
8) They have to install again the 1.8 of @react-native-community/picker to work again.

**Expected behavior**<br />
Dont show the message: Invariant Violation: Tried to register two views with the same name AndroidDropdownPicker

**Screenshots**<br />
you now what I mean

The solution is: in this repo in this package.json should be the version of @react-native-community/picker on ^1.6 or 1.8.1

**Additional details**<br />
-   Device: Pixel XL
-   OS: Android API29
-   react-native-picker-select version: 8.0.2
-   react-native version: 0.62.2
-   expo sdk version: n/a

**Comment by Yashirathore11** [comment]
Facing the same issue.

**Comment by lem0n43** [comment]
I did solution at #3114, but it still didn't work.

**Comment by milennaj** [comment]
This is not fixed in version 8.0.3 still.

  "dependencies": {
        "@react-native-community/picker": "1.6.0",
        "lodash.isequal": "^4.5.0"
    },

@react-native-community/picker is still set to have an exact version 1.6.0

**Comment by znoland3** [comment]
having same issue

**Comment by jehajj** [comment]
+1

**Comment by Hirurgo** [comment]
same issue

**Comment by azaidivl** [comment]
+1

**Comment by CoreyBurkhart** [comment]
I'm getting a very similar error on iOS: `Invariant Violation: Tried to register two views with the same name RNCPicker`.

As a workaround, using version `7.0.0` doesn't throw the error

**Comment by mouhsnimohamed** [comment]
having save issue, has some one fix this please?

**Comment by erikaperugachi** [comment]
My temporal solution was, using this library https://callstack.com/blog/say-goodbye-to-old-fashioned-forks-thanks-to-the-patch-package/ to change in package.json this: ` "@react-native-community/picker": "1.6.0"`, to `"@react-native-community/picker": "**^**1.6.0"`.
Firsy first the last version of @react-native-community/picker should be installed before.

**Comment by lfkwtz** [comment]
now defaulting to `"@react-native-picker/picker": "^1.8.3",` with clearer instructions in the readme

**Comment by PatrickVuscan** [comment]
Hi, I've tried many different combinations of what you've got above, for hours. Could anyone please give me an idea of the best guess of how to fix this?

I'm currently on expo SDK 40.0.0, and this is what my package.json looks like right now...

`"dependencies": {
   ...
    "@react-native-community/picker": "^1.6.0",
    "@react-native-picker/picker": "^1.8.3",
    ...
    "expo": "^40.0.0",
    "expo-font": "~8.4.0",
    ...
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz",
    ...
    "react-native-picker-select": "^7.0.0",
    ...
    "react-native-web": "~0.13.12",
    ...
  },`

Any ideas?
