### ISSUE TITLE
React Native Picker select: are there any callbacks available for Android

### ISSUE THREAD

**Issue by AahilShahzad** [lawnstarter/react-native-picker-select#392]
**Is your feature request related to a problem? Please describe.**<br>

**Describe the solution you'd like**<br>
I'm using react-native-picker-select in my React Native app, and the two main callbacks I'm using for iOS are onClose() and onDonePress(). However, these are iOS only. Is there some approach you can use with Android to trigger a function when the user has closed the picker or pressed Done? I know you can use onValueChange(), but this doesn't get triggered when the user is done, just when they iterate through the options in the picker

**Describe alternatives you've considered**<br>

**Additional details**<br>

**Comment by lfkwtz** [comment]
if it's not in the docs it doesn't exist

**Comment by rollsroyc3** [comment]
https://stackoverflow.com/questions/61648616/react-native-picker-select-are-there-any-callbacks-available-for-android
