### ISSUE TITLE
[Expo SDK 40 Support] Migrate to @react-native-picker/picker 

### ISSUE THREAD

**Issue by nandorojo** [lawnstarter/react-native-picker-select#397]
**Is your feature request related to a problem?** 

Expo SDK 40's beta is released. It includes a PR (https://github.com/expo/expo/pull/11029) by @brentvatne changing to `@react-native-picker/picker`. I believe this means this library isn't working with SDK 40.

**Describe the solution you'd like**

Change the picker dependency from `@react-native-community/picker` to `@react-native-picker/picker`

**Describe alternatives you've considered**

Not upgrading to SDK40, or using `patch-package` to replace the imports.

**Additional details**

Expo SDK 40 release notes can be found here: https://github.com/expo/expo/blob/master/CHANGELOG.md

Thank you!

**Comment by arunpugahz** [comment]
yes Kindly migrate.
Tried to use react-native-picker-select and @react-native-picker/picker for different components got the following error
`Invariant Violation: Tried to register two views with the same name RNCPicker`

**Comment by lfkwtz** [comment]
handled in 8.0.4

**Comment by PatrickVuscan** [comment]
Still happening in Expo SDK 40 for me - should probably be reopened?

**Comment by brentvatne** [comment]
@PatrickVuscan - are you using the version that @lfkwtz mentioned above?

**Comment by PatrickVuscan** [comment]
@brentvatne I’ve tried every single combination of different versions that I’ve seen on this thread and many others... 

I’m not sure if it’s because I’m using NativeBase, but when I try any of the versions of this, 7.0.0 - ^8.0.3, it tells me that  react-native-picker/picker is missing. Once I install it because it’s missing with npm  install, it gives me an invariant violation because two RNCPicker components are being registered...

Any advice?

**Comment by brentvatne** [comment]
react-native libraries shouldn't include other react-native libraries with native dependencies as dependencies. so, if nativebase includes @react-naitve-picker/picker as a dependency, that is a problem and they should make it a peer dependency instead.

run `yarn why @react-native-picker/picker` to see where it's coming from
use yarn resolutions to force nativebase or whatever other library is including it to use the version you want (https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

**Comment by lfkwtz** [comment]
@brentvatne I added `@react-native-picker/picker` as a dependency to this library - didn't realize it should be a peerDependency - maybe that will fix the issue

**Comment by lfkwtz** [comment]
looking at nativebase they're also using `"@react-native-community/picker": "^1.6.6",` as a dependency - so the issues could be compounding

**Comment by PatrickVuscan** [comment]
@lfkwtz If it seems like its compounding, would you have any idea on how to just make this work?

**Comment by PatrickVuscan** [comment]
@brentvatne 

After running the npm-why (yarn why's duplicate I guess?) I get this:

```
npm-why @react-native-picker/picker

  Who required @react-native-picker/picker:

  team-project-13-lady-ballers-camp-frontend > react-native-picker-select > @react-native-picker/picker@1.9.4
