### ISSUE TITLE
Reset picker value.

### ISSUE THREAD

**Issue by jitenderchand1** [lawnstarter/react-native-picker-select#40]
Is there any way to reset picker value with initial one. For eg: in your example, the default title is 'Select a color...' 

After form submission, I want to reset it.

**Comment by lfkwtz** [comment]
set the `value` prop to equal the value of the placeholder object (defaults as null)

**Comment by jitenderchand1** [comment]
It is always selecting the first option in the list if I reset the value to  null

Option list
![screen shot 2018-06-24 at 11 54 39 pm](https://user-images.githubusercontent.com/19687185/41822243-5f4093ba-780a-11e8-96e5-08591b91468f.png)

```
<RNPickerSelect
            placeholder={{
              label,
              value: null,
            }}
            items={data}
            onValueChange={this.handleChange}
            value={value}
            style={{...placeholderStyle}}
          />
```

**Comment by lfkwtz** [comment]
Reproduce the issue for me on expo.snack.io

**Comment by lfkwtz** [comment]
Any luck reproducing?

https://snack.expo.io/SytsUTA-X

This sets a value after 1 second. Then, 1 second later, sets to `null` and the picker resets.

**Comment by jitenderchand1** [comment]
I think something is wrong with my markup for the function that is causing the issue.  The above example is working fine. 

Many thanks for your effort

**Comment by jitenderchand1** [comment]
The issue is reproducible with the latest version of `RNPickerSelect`.  `"react-native-picker-select": "3.1.2"`

[https://snack.expo.io/rJPm3oeMQ](https://snack.expo.io/rJPm3oeMQ)

**Comment by lfkwtz** [comment]
v3.1.3 seems to fix the issue

**Comment by tlambk2** [comment]
<RNPickerSelect
              placegolder="Chọn địa bàn"
              items={this.state.items}
              value={this.state.value}
              onValueChange={(itemvalue)=>{this.setState({value:itemvalue})}}
            />
set state.value to null whenever you want to init RNPickerSelect

**Comment by aphex3k** [comment]
Important to remember is that setting the value to null is not the same as setting the value to undefined
