### ISSUE TITLE
App crashes in android - bug

### ISSUE THREAD

**Issue by ssthil** [lawnstarter/react-native-picker-select#404]
**Describe the bug**<br />
 ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker 
RNPickerSelect@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:461777:36

**To Reproduce**<br />

1.  Go to the screen where we have this `RNPickerSelect` implementation
2.  Then the app crashes immediately
3.  See error:
 ERROR    Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker 
RNPickerSelect@`http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:461777:36`

**Expected behavior**<br />
The RNPickerSelect should work fine like in IOS. **But for IOS also has the same error.**

ExceptionsManager.js:179 Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker 
    at RNPickerSelect (`http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:458383:36`)

**Screenshots**<br />
App crashes

**Additional details**<br />
-   Device: [e.g. Samsung S8]
-   OS: [e.g. android 9]
-   react-native-picker-select version: [e.g. ^6.3.3]
-   react-native version: [e.g. 0.63.2]

#

**Comment by MSchmidt** [comment]
It won't solve the warning but you can get around the crash by adding `@react-native-picker/picker` (https://github.com/react-native-picker/picker) to your project.

**Comment by ssthil** [comment]
@MSchmidt thanks for your response. But still, there is an error even after I added `@react-native-picker/picker`
Kindly advise, do I need any specific version of @react-native-picker/picker?

**Comment by lfkwtz** [comment]
need the actual "additional details" for your bug report

**Comment by SatalBill** [comment]
Still app is crashing. I installed both packages - "@react-native-picker/picker" and "react-native-picker-select".
Once I click the picker, app crashes. Why this is happening?

**Comment by mchamorro7** [comment]
Same issue here, any solutions?

**Comment by vuletuanbt** [comment]
> Still app is crashing. I installed both packages - "@react-native-picker/picker" and "react-native-picker-select". Once I click the picker, app crashes. Why this is happening?
Same here. Have you resolved it?

**Comment by mchamorro7** [comment]
> > Still app is crashing. I installed both packages - "@react-native-picker/picker" and "react-native-picker-select". Once I click the picker, app crashes. Why this is happening?
> 
> Same here. Have you resolved it?

I resolved that issue by upgrading react-native package to 0.64.2

I have this package versions:
-  "react-native-picker-select": "^8.0.4"
-  "@react-native-picker/picker": "^2.1.0"

**Comment by vuletuanbt** [comment]
> > > Still app is crashing. I installed both packages - "@react-native-picker/picker" and "react-native-picker-select". Once I click the picker, app crashes. Why this is happening?
> > 
> > 
> > Same here. Have you resolved it?
> 
> I resolved that issue by upgrading react-native package to 0.64.2
> 
> I have this package versions:
> 
> * "react-native-picker-select": "^8.0.4"
> * "@react-native-picker/picker": "^2.1.0"

Thanks, it works on my RN 0.66.3

**Comment by ezraamos** [comment]
> Still app is crashing. I installed both packages - "@react-native-picker/picker" and "react-native-picker-select". Once I click the picker, app crashes. Why this is happening?

have you resolved this?

**Comment by ParthShrivastav** [comment]
Still facing the same issue after making the above changes

**Comment by feliciovcm** [comment]
Facing same issue, have tried all solutions above, but the error keeps happening
