### ISSUE TITLE
Multi Select and Search feature

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [lawnstarter/react-native-picker-select#419]
**Is your feature request related to a problem? Please describe.**<br>
I need to multi select. And constantly clicking and picking one is hard and frustrating.

**Describe the solution you'd like**<br>
A search and multi select option with custom tick/check styling option.
Hopefully an option to add an image to the items, too.

**Describe alternatives you've considered**<br>
I couldn't find any alternatives from the documentation. I had to look into other libraries. But the performance of this one is quite good so I'd like to stick to it.

**Additional details**<br>

**Comment by ronmara** [comment]
#35
