### ISSUE TITLE
toggle not working in Android.

### ISSUE THREAD

**Issue by hasn-ab** [lawnstarter/react-native-picker-select#424]
**Describe the bug**<br />

**To Reproduce**<br />

1.  Use TouchableWithoutFeedback
2. `onPress` I am toggling with `this.pickerRef.current.togglePicker(false)`

**Expected behavior**<br />
Should open the picker 

**Screenshots**<br />
 null

**Additional details**<br />
-   Device: Android
-   OS: 10 
-   react-native-picker-select version: 8.0.4
-   react-native version: 0.63.3
-   expo sdk version: [ n/a]

**Reproduction and/or code sample**<br />

```
<RNPickerSelect
          disabled={!editable}
          onValueChange={(v) => this.handleValueChange(v)}
          value={selectedValue}
          style={{ maxHeight: 0 }}
          ref={this.pickerRef}
          onUpArrow={this.onArrowUp}
          InputAccessoryView={this.InputAccessoryView}
          onDownArrow={this.onDownArrow}
          style={{
            chevronUp: {
              fontSize: 0,
              color: 'white',
            },
          }}
          items={values}>
          <View style={{ height: 0 }}></View>
        </RNPickerSelect>

        <TouchableWithoutFeedback
          onPress={() => {
            console.log('toogle');
            this.pickerRef.current.togglePicker(false);
          }}>
          <View style={[styles.inputContainer, style]}>
            {selectedValue.trim().length > 0 ? (
              <>
                <Text style={styles.labelStyle}>{placeholder}</Text>
                <Text style={styles.textInputStyle}>{label}</Text>
              </>
            ) : (
              <>
                <Text style={styles.labelStyle}>{placeholder}</Text>
              </>
            )}
          </View>
        </TouchableWithoutFeedback>
      </>
```

**Comment by vladcorn** [comment]
Also you can reproduce this bug with any onPress function

**Comment by nakullondhe** [comment]
I have the same issue, can anyone help?

**Comment by Soliman13** [comment]
I have the same issue, while this is working fine on iOS.

**Comment by NvIGA** [comment]
I have the same issue

**Comment by bacarybruno** [comment]
@hasnaina-entertainer this should work.
As per this commit https://github.com/react-native-picker/picker/pull/258 (thanks @mateusz1913)
```javascript
     <>
        <RNPickerSelect
          disabled={!editable}
          onValueChange={(v) => this.handleValueChange(v)}
          value={selectedValue}
          style={{ maxHeight: 0 }}
          pickerProps={{ ref: this.pickerRef }}
          ref={this.pickerRef}
          onUpArrow={this.onArrowUp}
          InputAccessoryView={this.InputAccessoryView}
          onDownArrow={this.onDownArrow}
          style={{
            chevronUp: {
              fontSize: 0,
              color: 'white',
            },
          }}
          items={values}>
          <View style={{ height: 0 }}></View>
        </RNPickerSelect>

        <TouchableWithoutFeedback onPress={() => { this.pickerRef.current.focus(); }}>
          {content}
        </TouchableWithoutFeedback>
     </>
```

Short answer (Android only)
```javascript
<RNPickerSelect
   {...otherProps}
   pickerProps={{ ref: this.pickerRef }}
/>
```
and then 

```javascript
<TouchableWithoutFeedback onPress={this.pickerRef.current.focus}>
  {content}
</TouchableWithoutFeedback>
```

To make this work for Android & iOS you can do something like this

```javascript
class PickerSelect extends React.Component {
  pickerRef = React.createRef()

  openPicker() {
    if (Platform.OS === 'android') {
      this.pickerRef.current.focus()
    } else {
      this.pickerRef.current.togglePicker(true)
    }
  }

  render() {
    const { onValueChange, items, value } = this.props
    return (
      <RNPickerSelect
        onValueChange={onValueChange}
        items={items}
        style={{ viewContainer: { height: 0 } }}
        ref={Platform.OS === 'ios' ? this.pickerRef : null}
        pickerProps={{ ref: Platform.OS === 'android' ? this.pickerRef : null }}
        value={value}
      />
    )
  }
}
```

and then

```javascript
const pickerRef = useRef();

<PickerSelect
  ref={pickerRef}
  items={values}
/>

<TouchableWithoutFeedback onPress={pickerRef.current.openPicker}>
  {content}
</TouchableWithoutFeedback>
```

**Comment by valeriashpiner** [comment]
I got message for `pickerProps={{ ref: this.pickerRef }}`: Type '{ ref: React.MutableRefObject<undefined>; }' is not assignable to type 'CustomPickerProps'.
Also, I tried @bacarybruno solution and I always get `undefined is not an object`, when I use `.current.focus()`.

**Comment by romanmatus** [comment]
Hello, this problem still presist on android devices, or is it only for me ?

const handlePickerToggle = () => {
    if (dropDownRef.current) {
      dropDownRef.current.togglePicker();     
    }
  };
  
          <TouchableOpacity className="bg-blue-200" onPress={handlePickerToggle}>
          <View className="h-full flex-row items-center">
            <Image
              className="h-6 w-6 mr-2 ml-2"
              source={getImageSource(nationalPrefix)}
            />
            <DropDown 
              ref={dropDownRef}
              fixAndroidTouchableBug={true}
              useNativeAndroidPickerStyle={false}
              placeholder={{
                label: ".",
                value: ".",
                inputLabel: ".",
              }}
              onValueChange={(value) => {
                setNationalPrefix(value);
                handleValueChange();
              }}
              style={pickerStyle}
              items={[
                { label: "a", value: "+4", inputLabel: "+4" },
                { label: "b", value: "+3", inputLabel: "+3" },
              ]}
              
            />
            
            <Feather
              className="ml-2 mr-2"
              name={"chevron-down"}
              size={20}
              color="#899295"
            />
          </View>
        </TouchableOpacity>
  
  it works perfectly on ios, but on android it is working only if you press inside red square.
  
  
![image](https://github.com/lawnstarter/react-native-picker-select/assets/55752129/46ab21b3-d4fa-4725-84b4-d94dadfd6e3f)

any advice please?

**Comment by lfkwtz** [comment]
#22

**Comment by Ke0x** [comment]
The solution above doesnt work for me,
No matter what i tried i cant open the Picker with the focus function, i dont have any error.

**Comment by vahidd** [comment]
@Ke0x 

```JS
pickerRef.current.togglePicker(true);
```

**Comment by benedusi** [comment]
The proposed focus approach does not work anymore, as focus() is not available:
pickerRef.current.focus is not a function (it is undefined)

**Comment by benedusi** [comment]
Patching the source code to use the `ref.focus()` is the only thing that works for me.

**Comment by gogupaul123** [comment]
I found a fix ( or at the very least it fixed it for me )

I recommend using the Platform conditional, as it started bugging out on ios once I added the ref.togglePicker(). 

<img width="690" alt="Image" src="https://github.com/user-attachments/assets/28bc232f-d6f6-4892-aaa9-38434b821d91" />

**Comment by consuelo-sanna** [comment]
Hi @benedusi, can you expand a little bit more on your solution?
I'm also facing the issue but it's not clear to me where/how to use the ref.focus()

**Comment by benedusi** [comment]
> Hi [@benedusi](https://github.com/benedusi), can you expand a little bit more on your solution? I'm also facing the issue but it's not clear to me where/how to use the ref.focus()

I modified `react-native-picker-select/index.js` added ref to both android `<Picker/>` instances and toggled focus inside the `togglePicker` function.

Here's a patch for version 9.3.1:
https://gist.github.com/benedusi/50b90c220bfc58c5510bf17ac8a77b77
