### ISSUE TITLE
Placeholder text color not able to change

### ISSUE THREAD

**Issue by suresh777** [lawnstarter/react-native-picker-select#446]
I am using this library for picker, but i am not able to change placeholder text color, i tried all ways

placeholderTextColor = "black"
placeholder={{ label: "Select Week", value: null,color:'black' }}

after doing these changes also it is showing in gray color
i checked the code
 static defaultProps = {
        value: undefined,
        placeholder: {
            label: 'Select an item...',
            value: null,
            color: '#9EA0A4',
        },
i found default props

**Comment by mwood23** [comment]
@suresh777 I think the docs are wrong because that way doesn't work. Instead, you need to use the `style` prop except it's an object.

```js
      <RNPickerSelect
        style={{
          placeholder: {
            color: "purple",
            fontSize: 12,
            fontWeight: "bold",
          },
```

**Comment by suresh777** [comment]
this is working fine, thanks

**Comment by SrinivasanJms** [comment]
Am using like this, but it doesn't change the placeholder color

<RNPickerSelect
                                                placeholder = {{label: 'Type', value: ''}}
                                                style={{...pickerSelectStyles}}


const pickerSelectStyles = StyleSheet.create({
  inputIOS: {
    width: width - 80,
    height: 45,
    borderWidth: 1,
    borderRadius: 3,
    borderColor: Colors.inputBorderColor,
    paddingHorizontal: 10 // to ensure the text is never behind the icon
  },
  iconContainer: {
    top: 18,
    right: 10
  },
  placeholder: {
    color: 'lightgray',
    fontSize: 14
  },
  inputAndroid: {
    width: width - 80,
    height: 45,
    borderWidth: 1,
    borderRadius: 3,
    borderColor: Colors.inputBorderColor,
    paddingHorizontal: 10 // to ensure the text is never behind the icon
  },
});

**Comment by aziyatali** [comment]
you can use placeholderTextColor property
```
placeholder="some name"
placeholderTextColor-"some color"
```

**Comment by MatkoMilic** [comment]
> ```js
> style={{
>           placeholder: {
>             color: "purple",
>             fontSize: 12,
>             fontWeight: "bold",
>           },
> ```

This doesn't work for me at the end of 2023 :(

**Comment by MatkoMilic** [comment]
I found the solution for 2023:

<RNPickerSelect
              onValueChange={handleChange("playerType")}
              placeholder={{
                label: "Choose National or Club level:",
                value: null,
                color: "red",
              }}
              onOpen={& here I will even put a condition with state variable to only get different placeholder color when opened}
              style={pickerStyle}
              items={[
                { label: "National", value: "national" },
                { label: "Club", value: "club" },
              ]}
              pickerProps={{ style: { overflow: "hidden" } }}
            />

**Comment by kristian-nst** [comment]
Color doesn't work - RN 81, Expo 54, iOS 26
