### ISSUE TITLE
Defaulting of properties does not trigger onValueChange

### ISSUE THREAD

**Issue by fkrauthan** [lawnstarter/react-native-picker-select#45]
When I pass in a `value` of null but the function that figures out which value is selected changes this the `onValueChange` callback is not called. This leads to my state beeing out of sync of what the UI displays.

E.g.

My State Value: `null`
Value in: `null`
Items in: `{label: 'Orange',value: 'orange', label: 'Green',value: 'green'}`

My State Value: `null`
Label Displayed: `Orange`
`onValueChange` is not called therefor my state does not change to the displayed value `orange`

**Comment by lfkwtz** [comment]
Please reproduce the issue on snack.expo.io

**Comment by fkrauthan** [comment]
Sure but it will take some time until I find time to do this. But I know for sure that this is happening as I looked through the code to fix that other issue.

**Comment by fkrauthan** [comment]
Yes that would fix the issue I saw.
