### ISSUE TITLE
togglePicker() not working on android 

### ISSUE THREAD

**Issue by tiennguyen9988** [lawnstarter/react-native-picker-select#456]
**Describe the bug**<br />
I need trigger open Picker from button. I used togglePicker and it's nice on ios but not working on android. Please help me any solution ?

**Additional details**<br />
-   Device: [SamSung]
-   OS: [Android]
-   react-native-picker-select version: [8.0.3]
-   react-native version: [0.63.4]

**Comment by tiennguyen9988** [comment]
I solved this problem with the solution:
- fork react-native-picker-select package
- update "@react-native-picker/picker": "^1.16.7",
- add action focus() inside togglePicker function for platform Android
Link: https://github.com/tiennguyen9988/react-native-picker-select
I hope the publisher updates this issue for the next release soon.

**Comment by NazimMertBilgi** [comment]
@amos80m thank u, its worked.

**Comment by Moistbobo** [comment]
I've created a patch for those who use patch-package but don't want to fork the repo:

(this is just the index.js from @tiennguyen9988 's forked version)
https://gist.github.com/Moistbobo/2b4bbc5a4a4a0b4c405b44024b5b8c82

**Comment by shoki61** [comment]
[](https://github.com/lawnstarter/react-native-picker-select/issues/424#issuecomment-851065179)
this solution worked

**Comment by lfkwtz** [comment]
#22
