### ISSUE TITLE
styling android not working

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [lawnstarter/react-native-picker-select#47]
![screenshot_1530520610](https://user-images.githubusercontent.com/33291479/42153605-c3e4623e-7e0d-11e8-8266-eb1534955b27.png)

**Comment by lfkwtz** [comment]
Please reproduce the issue on snack.expo.io or share some code. A screenshot doesn't tell me much.

Also read through this issue, it may be related - https://github.com/lawnstarter/react-native-picker-select/issues/30

**Comment by nguyenvanphuc2203** [comment]
i had resovle my issue by use style inputAndoird:{} ! thank guys
