### ISSUE TITLE
Add a way to clear the picker

### ISSUE THREAD

**Issue by DaanKorver** [lawnstarter/react-native-picker-select#474]
**Is your feature request related to a problem? Please describe.**<br>
I have a form that needs to be cleared if its valid and ready to send. The only problem is that I can't seem to clear the picker/reset the state of the picker

**Describe the solution you'd like**<br>
I want a option to programmatically clear the input

**Describe alternatives you've considered**<br>
I tried to use some other packages but this ones looks the best.

**Additional details**<br>
N.A.

**Comment by Hassan426** [comment]
+1

**Comment by EmilyRagan** [comment]
If you are tracking the value in a variable, you can just set that variable to `null` or `undefined` to clear the input.

**Comment by CptFabulouso** [comment]
That won't clear the input, because the `value` prop 
> Will attempt to locate a matching item from the items array by checking each item's value property. If found, it will update the component to show that item as selected. **If the value is not found, it will default to the first item**.

**Comment by DaanKorver** [comment]
Closing this issue since the package isn't being updated anymore.
