### ISSUE TITLE
Element type is invalid: expected a string but got undefined

### ISSUE THREAD

**Issue by anchetaWern** [lawnstarter/react-native-picker-select#479]
**Describe the bug**<br />

**To Reproduce**<br />

1. Install package: `npm install @react-native-picker/picker`
2.  Install native dependency: `npx pod-install`
3.  Add sample code:

```
import RNPickerSelect from '@react-native-picker/picker';

<RNPickerSelect
  onValueChange={value => console.log(value)}
  items={[
    {label: 'Football', value: 'football'},
    {label: 'Baseball', value: 'baseball'},
    {label: 'Hockey', value: 'hockey'},
  ]}
/>
```

**Expected behavior**<br />
It should work.

**Screenshots**<br />
Add screenshots to help explain your problem. If screenshots aren't applicable to this issue, write "n/a".

<img width="350" alt="Screen Shot 2022-04-23 at 3 05 26 PM" src="https://user-images.githubusercontent.com/743603/164884172-8029dc15-33a6-48f1-b78c-929bf321ddd7.png">

**Additional details**<br />
-   Device: iPhone 11 (simulator)
-   OS: iOS 14.4
-   react-native-picker-select version: @react-native-picker/picker 2.41
-   react-native version: 0.67.4
-   expo sdk version: N/A (standard RN project)

**Reproduction and/or code sample**<br />
Provide a link to a reproduction of this issue on https://snack.expo.io **or an explanation why you can not**. Not including a snack link will result in a significant delay in our ability to address this issue.

```
import RNPickerSelect from '@react-native-picker/picker';

<RNPickerSelect
  onValueChange={value => console.log(value)}
  items={[
    {label: 'Football', value: 'football'},
    {label: 'Baseball', value: 'baseball'},
    {label: 'Hockey', value: 'hockey'},
  ]}
/>
```

I can't because the sample code in the existing expo uses the non-react native package in the example: https://snack.expo.dev/@lfkwtz/react-native-picker-select

Docs said to install this package for React Native: `@react-native-picker/picker`
But the sample Snack is using this package: `react-native-picker-select` which doesn't work when I tried. Installing them both causes a conflict in the naming.

**Comment by anchetaWern** [comment]
Works now. There's been a mix up with the existing packages I'm using. Basically I just needed to install both `react-native-picker-select` and the dependency which is `@react-native-picker/picker`

**Comment by projeffboy** [comment]
Documentation was a bit confusing, I thought I only had to install @react-native-picker/picker

**Comment by projeffboy** [comment]
Thanks, the documentation should be a little clearer, I thought I only had to install `@react-native-picker/picker`. Since I have react 18, I had to legacy peer deps install and it told me to install `react-native-gesture-handler` and `react-native-safe-area-context`
