### ISSUE TITLE
InputAccessoryView - Up and Down arrows are not working

### ISSUE THREAD

**Issue by satya-imaginea** [lawnstarter/react-native-picker-select#482]
https://github.com/lawnstarter/react-native-picker-select/blob/ca6488c2eef5c776a8071400c8b7987712d43397/src/index.js#L179

If onDownArrow/onUpArrow prop was provided, the `this.onDownArrow` will be called which closes the selector options instead of moving the selected option up/down. This is happening as we are calling the `this.togglePicker(false, <onDown/UPArrow>)` when we click on the Up/down arrows of InputAccessoryView. 'done' action is working fine as its purpose is to close the selection widget.

**Comment by satya-imaginea** [comment]
> Yea same problem, probably need to make a fork of this project to suit it for your needs...
> 
> Or have you found another solution?

We have hidden the up&down arrows as they are optional :)

**Comment by lfkwtz** [comment]
that's how the picker functions natively on the web - which this project tries to emulate

**Comment by hotaryuzaki** [comment]
> > Yea same problem, probably need to make a fork of this project to suit it for your needs...
> > Or have you found another solution?
> 
> We have hidden the up&down arrows as they are optional :)

how to hidden it? i tried some props but not succeed
