### ISSUE TITLE
Add testId support to picker items

### ISSUE THREAD

**Issue by LoserAntbear** [lawnstarter/react-native-picker-select#495]
**Is your feature request related to a problem? Please describe.**<br>
Picker itself provide testId support, but items do not have it. For the sake of improvement of testing of the components testId support should be added.

**Describe the solution you'd like**<br>
A `testId` prop should be added to the item in renderer method. Interestingly,`PickerItem` component already has it, but `renderItem` method does not propagate it.

**Describe alternatives you've considered**<br>
For now the easies solution is a monkeypatch, but it's the last resort.

**Additional details**<br>
Missing prop propagation
<img width="415" alt="image" src="https://user-images.githubusercontent.com/19800511/210548825-bdc4c006-21c1-4846-ad69-9ef87ac7cb40.png">
Proof of support of testID prop by Item component
<img width="556" alt="image" src="https://user-images.githubusercontent.com/19800511/210549003-7d738eb8-096b-436d-aa1d-ce960d425350.png">

**Comment by LoserAntbear** [comment]
I'd like to commit to this, if approved.

**Comment by lfkwtz** [comment]
#498
