### ISSUE TITLE
Okay I found a workaround to fix it.

### ISSUE THREAD

**Issue by Jewels-Infosystems** [lawnstarter/react-native-picker-select#502]
Okay I found a workaround to fix it. 
In my case I was using npm and there is an issue with peer dependencies and React 18 used on newer versions of React Native.

I have re-install the module with this command  => `npm i react-native-picker-select --legacy-peer-deps`

_Originally posted by @seb-glanum in https://github.com/lawnstarter/react-native-picker-select/issues/486#issuecomment-1266517797_

**Comment by lfkwtz** [comment]
not sure why this is a separate issue
