### ISSUE TITLE
Picker does not re-render when setState is triggered

### ISSUE THREAD

**Issue by willikay11** [lawnstarter/react-native-picker-select#52]
Hi, 

Thank you for making this package. It has helped quite a lot. I however have an issue. When the state of items is updated using this.setState(), the items in the picker do not change.

Thanks

**Comment by lfkwtz** [comment]
Reproduce the issue for me on snack.expo.io - thanks

**Comment by MimiLau** [comment]
if the items are dynamic, it would not change according to props change..

```
items={[
	{
		label: _get(this.props.texts, ['member', 'salutat', 'mrs']),
		value: 'MRS'
	},
	{
		label: _get(this.props.texts, ['member', 'salutat', 'ms']),
		value: 'MS'
	},
	{
		label: _get(this.props.texts, ['member', 'salutat', 'mr']),
		value: 'MR'
	}
]}
```

**Comment by lfkwtz** [comment]
@MimiLau hard to tell what's going on without additional code, but on the surface it looks like bad patterns that aren't triggering a re-render.
