### ISSUE TITLE
Typing doesn't permit arrays when supplying style overrides

### ISSUE THREAD

**Issue by stevebutler2210** [lawnstarter/react-native-picker-select#527]
**Describe the bug**<br />
The `PickerStyle` type definition doesn't allow for arrays of style objects to be passed for any of the properties, requiring unnecessary use of `StyleSheet.flatten()` to satisfy the typings. Passing arrays of style objects is valid syntax (thanks to RN [StyleProp](https://github.com/facebook/react-native/blob/94da17e6425039c7f6a4eafa69daf00d0c23150e/packages/react-native/Libraries/StyleSheet/StyleSheet.d.ts#L22)), and behaves as expected if you ignore the type errors—use of flatten shouldn't be necessary here unless the situation strictly requires it (to flatten nesting etc).

Proposed solution would be to amend the typing of the [PickerStyle](https://github.com/lawnstarter/react-native-picker-select/blob/3b9759d1d315b3b3e2d59195734e008460c56987/index.d.ts#L25-L50) interface to use e.g. `StyleProp<ViewStyle>` instead of `ViewStyle`.

**To Reproduce**<br />
Pass an array of `ViewStyle` objects into the `style.inputAndroidContainer` prop.

Simple reproduction can be seen with the following implementation, or on the snack linked below:

```
import React from "react";
import type { StyleProp, ViewStyle } from "react-native";
import RNPickerSelect from "react-native-picker-select";

interface DropdownProps {
  value: string;
  options: string[];
  editable?: boolean;
}

export const Dropdown: React.FC<DropdownProps> = ({
  value,
  options,
  editable,
}) => {
  const $customInputWrapperStyles: StyleProp<ViewStyle> = [
    $inputWrapperStyles,
    !editable && $inputWrapperDisabledStyles,
  ]

  return (
    <RNPickerSelect
      value={value}
      items={options.map((option) => ({ label: option, value: option }))}
      disabled={!editable}
      style={{
        inputAndroidContainer: $customInputWrapperStyles,
      }}
    />
  );
};

const $inputWrapperStyles: ViewStyle = {
  borderWidth: 1,
  borderRadius: 100,
  borderColor: "black",
  backgroundColor: "white",
};

const $inputWrapperDisabledStyles: ViewStyle = {
  backgroundColor: "gray",
};
```

The styles work, but a type error is raised.

**Expected behavior**<br />
As the style syntax is valid, no type error should be raised.

**Screenshots**<br />
![Screenshot 2023-11-10 at 17 31 01](https://github.com/lawnstarter/react-native-picker-select/assets/25485564/63ea498e-056d-42ed-8ef5-94499def0bbe)

**Additional details**<br />
-   react-native-picker-select version: 8.1.0
-   react-native version: 0.72.4
-   expo sdk version: 49

**Reproduction and/or code sample**<br />
https://snack.expo.dev/@stevebutlerkyan/rnpicker-styleprop-type-error-example

**Comment by lfkwtz** [comment]
Interested in contributing a fix?

**Comment by stevebutler2210** [comment]
@lfkwtz 💯 just wanted to make sure the issue was agreed upon first! If we're on the same page, I'll try and get something raised later today 👍
