### ISSUE TITLE
Is it possible to hide upArrow and downArrow in picker ?

### ISSUE THREAD

**Issue by RajaReddyP** [lawnstarter/react-native-picker-select#538]
**Is your feature request related to a problem? Please describe.**<br>
I want to hide upArrow and downArrow in the picker, because if I am not using those up/down arrows for scrolling items in the picker. 

**Describe the solution you'd like**<br>
If you provide any props to hide and show arrows (up/down) would be good.

**Comment by lfkwtz** [comment]
modalViewMiddle: {justifyContent:'flex-end'}, chevronContainer: {display: 'none'}
