### ISSUE TITLE
Android - icon is not rendered

### ISSUE THREAD

**Issue by kr0000** [lawnstarter/react-native-picker-select#54]
On iOS icon is rendered correctly, on Android no - i check source code and it could be a bug.

**Comment by lfkwtz** [comment]
What version of android?

**Comment by kr0000** [comment]
27

**Comment by lfkwtz** [comment]
I’ll take a look, but the arrow on Android is typically rendered by the Picker component itself.

So if it’s not there - it’s either an RN issue or a difference in Android 27 and/or your manufacturer’s flavor of Android.

If you need it, you’ll have to recreate an input using the Android headless mode.

**Comment by lfkwtz** [comment]
PR #105 and useNativeAndroidPickerStyle should cover this need. moving to done.
