### ISSUE TITLE
How can you style the placeholder ? 

### ISSUE THREAD

**Issue by radjivF** [lawnstarter/react-native-picker-select#57]
Hi I'm having trouble when I try to style the placeholder?

Any idea how? 

Cheers

**Comment by lfkwtz** [comment]
https://github.com/lawnstarter/react-native-picker-select/blob/master/src/index.js#L138

You can change the color using this param on the style object. Is that what you were looking for?

**Comment by radjivF** [comment]
I have try but nothing its changing on the placeholder :/

**Comment by lfkwtz** [comment]
Reproduce the issue for me on snack.expo.io or share code

**Comment by radjivF** [comment]
@lfkwtz  Hey mate, I did  a snack.expo.io https://snack.expo.io/BkOJGX2m7

On the line 54 its where I try to style the placeholder

**Comment by lfkwtz** [comment]
Look at the example files in the repo to see how to correctly style the component’s different elements

**Comment by webmasterdragon** [comment]
How can I style fontSize for placeholder and item?

**Comment by lfkwtz** [comment]
the docs / examples should help answer that question for you. otherwise, styling questions are more appropriate for stackoverflow.
