### ISSUE TITLE
onValueChange double toggle after i selected.

### ISSUE THREAD

**Issue by lyseiha** [lawnstarter/react-native-picker-select#58]

**Comment by JulianKingman** [comment]
This is probably because of the 4.0.0 release, how did you handle it? https://github.com/lawnstarter/react-native-picker-select/releases/tag/4.0.0

**Comment by baqirhabsyi** [comment]
Hey @lyseiha, I encountered the same problem. Did you find out how to fix this behavior?

**Comment by DenisBogatirov** [comment]
This is still an issue.
@JulianKingman Who does need this logic? https://github.com/lawnstarter/react-native-picker-select/releases/tag/4.0.0

You fire change event which fires re-render with new calue, which fires change event again?

I am trying to use it with Redux-Form and it fires change event with old value

**Comment by lfkwtz** [comment]
This change occurred via #45 - it's been out for almost 3mo now and there haven't been issues opened aside from this thread - but I'm interested in how this is negatively impacting you.

I just added some more tests locally and i'm not seeing the issue you're describing @DenisBogatirov  - can you reproduce it somewhere?

I could potentially add a flag to disable this...

**Comment by jarredkenny** [comment]
I am seeing this as well on v8.1.0 and am getting around it by debouncing the on change handler, not ideal.

Would love a flag to turn off this behaviour.
