### ISSUE TITLE
Not re-rendered when value is changed via other component

### ISSUE THREAD

**Issue by YukiOmori** [lawnstarter/react-native-picker-select#70]
Hi, thanks for such a nice component.

I have a trouble updating displayed value.

**Background:**
What I actually want to do is to automatically update the component value of prefecture made of react-native-picker-select when the user input a postalcode which automatically evokes postalcode API and get the address JSON object containing prefecture, city, and street.

However, it did not work, though other values (city and street) which are simple TextInput components are updated and re-rendered.

**What I want to solve here:**
For my simple test, I created a sample project, which has only two components made of react-native-picker-select.
Then, as I was afraid, this sample doesn't work too.

I just want this to work.

**Expected Behavior:**
When the upper value is selected and changed, lower value is also changed, because their value is common state; prefecture.

**Actual Behavior:**
When the upper value is selected and changed, lower value does not change.

![Behavior gif](https://i.imgur.com/C3FQPzT.gif)

Here is my code.
**App.js**
```javascript
import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import RNPickerSelect from 'react-native-picker-select';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      prefecture: '',
    };
  }
  render() {
    const prefectures = [
      {
        label: 'Tokyo',
        value: 'Tokyo',
      },
      {
        label: 'Osaka',
        value: 'Osaka',
      },
    ];
    return (
      <View style={{ paddingTop: 200 }}>
        <RNPickerSelect
          placeholder={{
            label: 'Select',
            value: 'Select',
          }}
          items={prefectures}
          hideIcon
          onValueChange={prefecture => this.setState({ prefecture })}
          style={{ ...pickerSelectStyles }}
          value={this.state.prefecture}
        />
        <RNPickerSelect
          placeholder={{
            label: 'Select',
            value: 'Select',
          }}
          items={prefectures}
          hideIcon
          onValueChange={prefecture => this.setState({ prefecture })}
          style={{ ...pickerSelectStyles }}
          value={this.state.prefecture}
        />
      </View>
    );
  }
}

const pickerSelectStyles = StyleSheet.create({
  inputIOS: {
    fontSize: 14,
    backgroundColor: 'white',
    color: 'black',
  },
});
```

**package.json**
```javascript
{
  "name": "testDatePicker",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-native-picker-select": "^4.2.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.5.0",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by lfkwtz** [comment]
Your React version doesn’t align to the correct version of this component. Read the readme.

**Comment by lfkwtz** [comment]
You'll have to reproduce the error for me on either expo or in a repo.

Using the code you provided, [it works as expected](https://snack.expo.io/S1VNoAIUQ).
