### ISSUE TITLE
Drop-down icon disappears on Android

### ISSUE THREAD

**Issue by FerZablah** [lawnstarter/react-native-picker-select#72]
When setting a backgroundColor for Android, the drop down icon either disappears or it also changes its color to the same backgroundColor, either way making it invisible.
This is the style i'm passing to the style prop on the picker component.
`const pickerstyle = {
  inputAndroid: {
    color: '#494B82',
    backgroundColor: 'white',
    margin: 5
  },
  underline: {
    borderTopWidth: 0
  },
  backgroundColor: 'white'
};`
This is what it looks like on my Galaxy S9+
![whatsapp image 2018-08-28 at 12 39 59 pm](https://user-images.githubusercontent.com/25018310/44740225-81ebf480-aabf-11e8-840c-71f4f46131a1.jpeg)

**Comment by lfkwtz** [comment]
This is an issue with the native Android picker, but not a bug with this component

You have two options here:
1) You _may_ be able to modify the background without losing the arrow via [this method](https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949)
2) You can utilize the headless mode of this component to create an element that is styled and acts the way you want - much in the same way we do this for iOS
