### ISSUE TITLE
How to remove this shadow effect

### ISSUE THREAD

**Issue by AkezhanOb1** [lawnstarter/react-native-picker-select#79]
Hello, I have an issue, I can't remove this white shadow 
![powyl4zsjgm](https://user-images.githubusercontent.com/31239874/45600913-5907b100-ba26-11e8-9465-e95b30e1cb6f.jpg)

here is my style object 
  `const pickerSelectStyles = StyleSheet.create({
    inputIOS: {
        marginHorizontal: 10,
        marginVertical: 5,
        paddingTop: 13,
        paddingHorizontal: 10,
        paddingBottom: 12,
        width: window.width - 30,
        height: 40,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        color: '#fff',
    },
})`

and also a tag 
`                        <RNPickerSelect
                            placeholder={{label: "Pick up your city", value: null}}
                            placeholderTextColor={"white"}
                            hideIcon={true}
                            items={this.state.cities}
                            onValueChange={(value) => {
                                this.setState({
                                    city: value,
                                });
                            }}
                            onUpArrow={() => {
                                this.inputRefs.picker.togglePicker();
                            }}
                            onDownArrow={() => {
                                this.inputRefs.company.focus();
                            }}
                            style={{...pickerSelectStyles}}
                            value={this.state.city}
                        />`

**Comment by lfkwtz** [comment]
Please use the bug report template
