### ISSUE TITLE
focus on picker in scrollview

### ISSUE THREAD

**Issue by BatDroid** [lawnstarter/react-native-picker-select#8]
hi,
anyone knows how we can focus on picker?
i have form that at the end of the form there is this picker and i want to scroll to it

**Comment by BatDroid** [comment]
yes i would like to do it but i cant find any props or solution in document/example of the picker

**Comment by lfkwtz** [comment]
Wrap the component in a view, get the position of the view, and then use scrollto

**Comment by ericmatte** [comment]
Like @lfkwtz said, this can be done easily by wrapping in a view, and then I use trigger `scrollIntoView` method from a parent [KeyboardAwareScrollView](https://github.com/APSL/react-native-keyboard-aware-scroll-view) when the iOS picker opens.
