### ISSUE TITLE
white frames on placeholder text.

### ISSUE THREAD

**Issue by AkezhanOb1** [lawnstarter/react-native-picker-select#80]
**bug**
After changing the color of the input field, an ugly white frame appeared on my inputPlacholder.
![powyl4zsjgm](https://user-images.githubusercontent.com/31239874/45605679-9426d600-ba60-11e8-9c43-3426ef76a65f.jpg)

**My styles are**
`const pickerSelectStyles = StyleSheet.create({`
    `inputIOS: {`
      `  marginHorizontal: 10,`
    `    marginVertical: 5,`
      `  paddingTop: 13,`
       ` paddingHorizontal: 10,`
        `paddingBottom: 12,`
      `  width: window.width - 30,`
       ` height: 40,`
   `     backgroundColor: 'rgba(255, 255, 255, 0.2)',`
       ` color: "#fff"',`
 ` },`
`})`

**Comment by lfkwtz** [comment]
Please use the bug report template. When clicking new issue, you are presented with an option that says Bug Report. Choose that and fill it out completely so I can asses this issue.
