### ISSUE TITLE
Style of selected item does not change

### ISSUE THREAD

**Issue by sojimon** [lawnstarter/react-native-picker-select#85]
**Describe the bug**
The font size and font color does not changes in android(I need to change the font size and font color). 

**To Reproduce**

1. npm installed the plugin
2. copy paste the code as shown in example

**Expected behavior**
I need to change the font size and font color.

**Screenshots**

![screen shot 2018-10-01 at 11 58 53 am](https://user-images.githubusercontent.com/22345185/46273171-112e7100-c572-11e8-9cac-a53bd749c92b.png)

**Smartphone (please complete the following information):**

-  OS: macOS High Sierra 10.13.6
-  react-native-picker-select": "^4.4.0"
-  react-native: 0.56.1 => 0.56.1 
-  react: 16.4.1 => 16.4.1

**Comment by lfkwtz** [comment]
See #30

**Comment by lfkwtz** [comment]
For color -- you can also use the `color` prop with each item -- if you want an easy js-only solution without using the headless mode

`{label: 'Orange',value: 'orange',key: 'orange', color: 'orange'}`
