### ISSUE TITLE
Cannot select any item on headless mod when I upgrade RN to 0.57.2

### ISSUE THREAD

**Issue by isener** [lawnstarter/react-native-picker-select#87]
When we open the select dialog, even we can't touch anywhere on screen so far.

Here is demo:

![untitled](https://user-images.githubusercontent.com/10687714/46634478-b391ba00-cb59-11e8-9e51-d76c688894ef.gif)

**Comment by lfkwtz** [comment]
please re-open using the **Bug Report** template

**Comment by lmichailian** [comment]
@lfkwtz I have the same issue,  It fails with basic impementation like headless example.

**Comment by lfkwtz** [comment]
@lmichailian feel free to open a proper bug report also. thanks.

**Comment by lmichailian** [comment]
@lfkwtz Oh sorry, I resolved it cleaning build cache

**Comment by grissproject** [comment]
> @lfkwtz Oh sorry, I resolved it cleaning build cache

Cleaning build cache worked for me as well, Thanks a lot!
