### ISSUE TITLE
KeyboardAvoidingView triggering

### ISSUE THREAD

**Issue by rickysullivan** [lawnstarter/react-native-picker-select#94]
**Describe the bug**
When using `<KeyboardAvoidingView>`. On iOS, the TextInput, which is used to trigger the picker, is triggering the KeyboardAvoidingView into squashing the view for a split second.

**Steps to reproduce**
Steps to reproduce the behaviour:

1.  Wrap `<RNPickerSelect />` with a `<KeyboardAvoidingView>`
2. Being filling out form, using the keyboard's `Next` key to focus the next TextInput.
3. See KeyboardAvoidingView triggering/flickering when clicking Done on the picker.

It will also flicker when taping the picker item at any point when the keyboard is open.

**Expected behaviour:**
Would be nice to not have the KeyboardAvoidingView trigger.

**Smartphone:**

-   Device: iPhone5
-   OS: iOS 10.3.3
-   react-native-picker-select version: 4.4.0
-   react-native version: 0.55.4
-   react version: 16.3.1

**Reproduction and/or code sample**
https://snack.expo.io/@rickysullivan/keyboardavoidingview

**Possible solution**
Adding `editable={false}` to the TextInput inside `renderTextInputOrChildren()`.

**Comment by lfkwtz** [comment]
wasn't able to replicate, but added `editable={false}` in #91 --- let me know if that fixes it for you

**Comment by rickysullivan** [comment]
Sorry @lfkwtz, been trying to get a project out the door.

I've re-tested using 5.0.1 and it seems to be working nicely.

I'll remove my `setTimeout()` wrappers in my app and see how it goes, but from my initial snack testing, it's all good.

4.4.0|5.0.1
---|---
![picker-flick 4 4 0](https://user-images.githubusercontent.com/437480/47814095-aca14480-ddb1-11e8-8286-3fcb8a1de9b6.gif)|![picker-flick 5 0 1](https://user-images.githubusercontent.com/437480/47814096-af039e80-ddb1-11e8-8436-b04032aa37a8.gif)
