### ISSUE TITLE
Can you add an onDismiss that fires after selection or done  prop?

### ISSUE THREAD

**Issue by weisssean** [lawnstarter/react-native-picker-select#97]
I want to pop a dialog when a certain option is selected. There isn't a simple way to do that.
An onDismiss function would really help.

**Comment by weisssean** [comment]
The main issue is I wanna show another popup with a text prompt and can't do it while the other one is showing.

**Comment by weisssean** [comment]
did, (iOS) I tried it by passing modalProps={onDismiss:()=>{ debugger; }} but it never hit.
Not much documentation either.
Seems like a pretty important function for an api, perhaps you should allow passing it from your component.

**Comment by lfkwtz** [comment]
Are you using v5?

**Comment by weisssean** [comment]
I did, (iOS I tried it by passing modalProps={onDismiss:()=>{ debugger; }}
but it never hit.
Not much documentation either.
Seems like a pretty important function for an api, perhaps you should allow
passing it from your component.

**Comment by weisssean** [comment]
I was using 4.4.0, upgraded to 5 and it works now. Thanks.
