### ISSUE TITLE
How to remove clickable option in the placeholder?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [lawnstarter/react-native-picker-select#98]
**Describe the bug**
The placeholder in android is clickable and returns null value to the state
**To Reproduce**
Just followed example codes. click on the field to open the selection options. Then click on the header/placeholder and returns nulll. How to disable the clickable?

**Smartphone (please complete the following information):**

-   Device: Android Samsung J7
-   OS: [e.g. iOS8.1]
-   react-native-picker-select version: Latest
-   react-native version: 0.57.0

**Comment by lfkwtz** [comment]
Not a bug, but I've added it to the feature request board
