### ISSUE TITLE
Picker Style on Android

### ISSUE THREAD

**Issue by orihero** [lawnstarter/react-native-picker-select#99]
https://snack.expo.io/@bungler/crabby-cookies

On IOS it works fine but on Android fails.

**Comment by sduval215** [comment]
I was having an issue with this not too long ago, particularly when fixing width, border-radius, border-color and border-width. I managed to get this done by conditionally styling the `viewContainer` that seems to wrap around it.

I still haven't had any luck styling the font sizes though....
